### ISSUE TITLE
Charm publishing needs clarification on first time users

### ISSUE THREAD

**Issue by urosj** [juju/docs#1003]
@marcoceppi We need to state some requirements for first time users:
- They need to have USSO and LP accounts.
- They need to login through jujucharms.com first to "register" to the system.
  Only then can they use the charm command.

Also: groups are handled through LP for now, the issue will be addressed in the 16.10 cycle.

**Comment by chuckbutler** [comment]
This was mentioned [here](https://jujucharms.com/docs/devel/authors-charm-store):

> In order to interact with the charm store you will need the latest charm command, an Ubuntu SSO 
> account, and you must have logged in to Launchpad at least once.

I think this could use some updating for more explicit call out, perhaps even encapsulated in a !!! Note: block.
