### ISSUE TITLE
Juju2 Bootstrap Openstack Provider Docs?

### ISSUE THREAD

**Issue by jamesbeedy** [juju/docs#1006]
Where can I find 2.0 docs that outline bootstrapping the Openstack provider?
thx

**Comment by evilnick** [comment]
For OpenStack you need to define the OpenStack cloud first:
https://jujucharms.com/docs/devel/clouds#specifying-additional-clouds

Then you can bootstrap as outlined here:
https://jujucharms.com/docs/devel/getting-started-general#2.-choose-a-cloud

**Comment by jamesbeedy** [comment]
Ugghh .... I hate to be a stickler, but where is the openstack provider tools and metadata specified? Also, how can we build tools and metadata for juju2? Am I the only one who has actually tried this? Bootstrapping the openstack provider is NOT straight forward. Can we have someone manually go run and document the explicit working commands and creds needed to bootstrap the openstack provider from start to finish? I've been trying for weeks to no avail..... Come on guys ......
 E.g
 
## Bootstrap openstack provider

1. Ensure these files exist with this content 
2. Run this set of commands
3. Now your openstack provider is bootstrapped

**Comment by evilnick** [comment]
AFAIK at the moment the metadata generation hasn't changed, and can be specified at bootstrap with the '--metadata' switch. I see what you mean though, we need to update the private cloud instructions also.

**Comment by matthewhelmke** [comment]
Closed via #1323
