### ISSUE TITLE
clouds.md should reference how to manage multiple controllers, ie switch && /charms-environment is incorrect

### ISSUE THREAD

**Issue by arosales** [juju/docs#1008]
https://jujucharms.com/docs/devel/getting-started-general does a good job of linking to "/clouds" to help users understand how to further manager their clouds.  However, on /clouds there is no link for further information on how to manage multiple controllers within or across clouds, ie the juju switch command. 

There is 
https://jujucharms.com/docs/master/charms-environments
However that is incorrect for juju 2.0

Thus, this bug is to update https://jujucharms.com/docs/master/charms-environments and to add a link off /clouds to the appropriate page the describes how to use "juju switch"

-thanks,
Antonio

**Comment by pmatulis** [comment]
I could stuff some `juju switch` usage in to the multi-user section I'm currently writing.

**Comment by pmatulis** [comment]
- Some `juju switch` usage was added to the new Users section.
- The charms-environments file was removed (PR pending at this moment) and a new file under Models section called 'Managing' will take its place (nothing written yet)
- I'm going to close this issue and open a new one about populating the above file.
