### ISSUE TITLE
Documentation leaves you at a dead end

### ISSUE THREAD

**Issue by bac** [juju/docs#1012]
Originally reported by @warsaw as https://github.com/CanonicalLtd/jujucharms.com/issues/253

When you follow the getting started guide at https://jujucharms.com/docs/devel/getting-started and finish playing around, you'd like to then play with deploying charms at https://jujucharms.com/docs/devel/charms

However, one of the last things the getting started guide instructs you to do is:

```
Note: To remove all the services in the model you just created, it is often quickest to destroy the model with the command 'juju destroy-model default` and then create a new model.
```

It doesn't really tell you how to create a new model.  But now when you `juju deploy mediawiki` you get the following error:

```
% juju deploy mediawiki
Added charm "cs:trusty/mediawiki-5" to the model.
Deploying charm "cs:trusty/mediawiki-5" with the charm series "trusty".
ERROR cannot add service "mediawiki": model "default" is no longer alive
```

You cannot `juju create-model default` because it already exists.  Thus it's not clear what state the default model is in, nor how to proceed.

**Comment by evilnick** [comment]
the links to the models docs, amongst some other 'next steps' are just below that, but I have added a specific link in the note now. thanks

The non-disappearing default model is a bug in the beta of Juju. As a workaround for beta, just create a model with a different name.

**Comment by warsaw** [comment]
@evilnick Thanks; I'll do that.  Will it eventually be possible to clean up the default model?  I want to be able to return to a null state.

**Comment by evilnick** [comment]
@warsaw I certainly hope so! There are bugs around the cleanup of old containers and models that will certainly be fixed before release.

**Comment by cherylj** [comment]
The problem of destroyed models hanging around has been fixed in beta5.  See bug: https://bugs.launchpad.net/juju-core/+bug/1534627
