### ISSUE TITLE
ERROR ambiguous relation

### ISSUE THREAD

**Issue by warsaw** [juju/docs#1015]
The charms page https://jujucharms.com/docs/devel/charms provides this step:

```
juju add-relation mediawiki mariadb:db
```

but this produces an error:

```
% juju add-relation mediawiki mariadb:db
ERROR ambiguous relation: "mediawiki mariadb:db" could refer to "mediawiki:db mariadb:db"; "mediawiki:slave mariadb:db"
```

**Comment by evilnick** [comment]
thx, fixed (the :db is in the wrong place)

    juju add-relation mediawiki:db  mariadb
