### ISSUE TITLE
Juju devel beta release nodes include an error

### ISSUE THREAD

**Issue by mbruzek** [juju/docs#1027]
I was trying to find some information in the docs and my google search returned the temp-release-notes page that seems to have an error in one of the headings.

Please see attached photo.
![devel_docs_error](https://cloud.githubusercontent.com/assets/6385185/14792783/82b2c3d8-0ae1-11e6-8d3c-d2ee532929a0.png)

**Comment by mbruzek** [comment]
I pulled the current master of the docs in an attempt to fix this problem but I could not find the offending text in the temp-release-notes.md file. Did someone else fix it recently?

**Comment by mbruzek** [comment]
It looks like this was introduced in https://github.com/juju/docs/commit/0f2fa23cbc01ae22c02f4f0d2ce67eb4a44606e8  but I don't see it in the latest code. I still see it on the web site so I am just trying to figure out how to fix this.

**Comment by pmatulis** [comment]
Looks like the link got split in two by PR #996 . I can fix it but then the fix will probably be overwritten the next time these notes are updated.
