### ISSUE TITLE
juju set-env is an unrecognized command

### ISSUE THREAD

**Issue by warsaw** [juju/docs#1037]
https://jujucharms.com/docs/master/juju-offline-charms talks about how to set the default series, but it doesn't work in juju 2.0 beta6:

```
% juju set-env "default-series=xenial"
ERROR unrecognized command: juju set-env
```

**Comment by cherylj** [comment]
For reference, the command is juju set-model-config in 2.0.

**Comment by evilnick** [comment]
Hi, sorry about that, that page is awaiting updates as per #1006 and #1023
