### ISSUE TITLE
2.0 should have a section on advanced bootstrap

### ISSUE THREAD

**Issue by evilnick** [juju/docs#1047]
i expect adding to the controllers-creating page is best

There are a lot of options people want/need to set at bootstrap time. e.g. the timeout for MAAS
There should be some info on these config options on that page, and possibly a table of values (maybe in reference section?)

**Comment by battlemidget** [comment]
Also to note that some of those options apply to creating new models as of beta6 they don't inherit the same options from the bootstrapped controller.

see http://pad.lv/1575895 for an example

**Comment by evilnick** [comment]
yeah. we also have a list of things that we asked the core-devs to sort into controller and model, so when we get that back we can update this stuff

**Comment by evilnick** [comment]
This has largely been addressed by more specific examples and a table of known options. Closing this for now - if there are specific omissions they should be opened as individual issues
