### ISSUE TITLE
Document a way to get to controller for developers

### ISSUE THREAD

**Issue by mbruzek** [juju/docs#1060]
While trying to diagnose a problem I needed the log files from the controller unit. I didn't know how to refer to the controller machine using Juju commands. @LiftedKilt explained the process to me in #juju so I want to make sure we document that procedure in case someone else needs it in the future.

To ssh to the controller issue the following commands:
```
juju switch admin
juju ssh 0
```

**Comment by evilnick** [comment]
Tip: If you  put 'Fixes #1060' in your PR, this gets closed automatically when it is merged
