### ISSUE TITLE
Table of Contents Broken for "devel" Docs

### ISSUE THREAD

**Issue by ericsnowcurrently** [juju/docs#1078]
When I go to the "devel" docs, the table of contents on the left side of the page is almost completely missing.  (The "stable" and "1.25" docs are working correctly.)

For instance, on https://jujucharms.com/docs/devel/authors-charm-metadata:

![image](https://cloud.githubusercontent.com/assets/1152074/15046151/9a79fe52-129b-11e6-9109-b1314f7e5b2d.png)

If I inspect the DOM, I see the following:

    <div class="jujudocs-menu" hidden="hidden" id="jujudocs-nav-0" style="display: none;">...

The same DOM element in the 1.25 docs:

    <div class="jujudocs-menu" id="jujudocs-nav-0">

My client:  Google Chrome "Version 47.0.2526.106 unknown (64-bit)" (from Google) on trusty

**Comment by evilnick** [comment]
you happened along at the wrong five minutes, it should be working fine now

**Comment by ericsnowcurrently** [comment]
confirmed!
