### ISSUE TITLE
Charm Metadata Docs Out of Date

### ISSUE THREAD

**Issue by ericsnowcurrently** [juju/docs#1079]
The page on charm metadata [1] is missing mention of some sections, including resources (2.0+) and payloads (1.25+).  There may be other out-of-date info.  For the authoritative source:

1.25:  https://github.com/juju/charm/blob/v5/meta.go#L669
master (2.0):  https://github.com/juju/charm/blob/v6-unstable/meta.go#L803

----
[1] 
https://jujucharms.com/docs/1.25/authors-charm-metadata
https://jujucharms.com/docs/devel/authors-charm-metadata

presumably, respectively:
https://github.com/juju/docs/blob/1.25/src/en/authors-charm-metadata.md
https://github.com/juju/docs/blob/master/src/en/authors-charm-metadata.md

**Comment by chuckbutler** [comment]
@evilnick - the attached branches/PR's LGTM. once merged this should be good to close :cake:

**Comment by pmatulis** [comment]
Fixed via #1100
