### ISSUE TITLE
404 for jujucharms.com/docs/stable/authors-charm-interfaces/

### ISSUE THREAD

**Issue by frankban** [juju/docs#1108]
See https://github.com/CanonicalLtd/jujucharms.com/issues/267

**Comment by pmatulis** [comment]
@marcoceppi File [authors-charm-interfaces.md](https://github.com/juju/docs/blob/1.23/src/en/authors-charm-interfaces.md) exists for 1.23. Should this be used in 1.25?

**Comment by chuckbutler** [comment]
@pmatulis - as this targets the author docs, i think its fine to forward port the 1.23 docs for 1.25.  Ideally the dev docs will supplant this and the interface-layers will essentially take over the job of explaining this.

**Comment by matthewhelmke** [comment]
The above fixes the issue for 2.0 docs. Still need to fix for 1.x.

**Comment by matthewhelmke** [comment]
And, #1406 fixes this for 1.25.

**Comment by evilnick** [comment]
fixed
