### ISSUE TITLE
https://jujucharms.com/docs/devel/getting-started has some extra uneeded steps

### ISSUE THREAD

**Issue by frankban** [juju/docs#1109]
Moved from https://github.com/CanonicalLtd/jujucharms.com/issues/259

**Comment by matthewhelmke** [comment]
It is possible that I am missing something. When I tested the procedure, omitting the section titled Prepare ZFS and going straight from the Install the Software section to the Initialise LXD section, I get the following:

`$ sudo lxd init --auto --storage-backend zfs --storage-pool lxd
error: Invalid ZFS pool: cannot open 'lxd': dataset does not exist
`
To proceed, please let us know precisely which steps may be omitted and which must be retained. Thanks!

**Comment by evilnick** [comment]
If you leave out the extra configuration from init, it does use an
interactive mode to set up zfs.

**Comment by matthewhelmke** [comment]
That makes sense, but for a novice user, our audience for a "Getting Started" page, how will they know how to respond to the interactive mode requests?

**Comment by pmatulis** [comment]
Seconded. The decision is whether a getting-started page should be prescriptive, as it is now, or not. The interactive method sounds more user friendly but it does require knowledge that a casual user may not have. IMO, the way it is now is more appropriate. We can add explanation of the interactive method but that involves more text which may be seen as a minus in this document.
