### ISSUE TITLE
clarity around how to specify revision in the charm

### ISSUE THREAD

**Issue by anastasiamac** [juju/docs#1115]
As per [LP #1583934](https://bugs.launchpad.net/juju-core/+bug/1583934), there needs to be better communication about revision file in charm directory - where it is, how to use it and what it is used for.

**Comment by matthewhelmke** [comment]
According to these, the revision file is deprecated. We will need more info to figure out how and where to specify details about a revision if we are to write to this.

* https://jujucharms.com/docs/2.0/authors-charm-components
* https://jujucharms.com/docs/1.25/authors-charm-components

**Comment by matthewhelmke** [comment]
The language quoted in the LP bug is found in the commands.md page, but that is auto-generated from help output. This is the context of the quote in the LP bug:

> Deploying from a path is intended to suit the workflow of a charm author working on a single client machine; use of this deployment method from multiple clients is not supported and may lead to confusing behaviour. Each local charm gets uploaded with the revision specified in the charm, if possible, otherwise it gets a unique revision (highest in state + 1).

It seems the first thing to be done is get clarity from development on what is going on and then update the help text. Our team would be happy to assist with help text language, once the understanding is clear.

**Comment by kwmonroe** [comment]
@anastasiamac @pmatulis Based on the quote above, I did a quick test to see how 'revision' affects local deployments, and sure enough, it sets the charm rev in things like `juju status`:

```bash
ubuntu@61c39b1d82f5:~/charms/trusty/pig$ echo '11' > revision
ubuntu@61c39b1d82f5:~/charms/trusty/pig$ juju deploy . --series trusty
Deploying charm "local:trusty/pig-11".
ubuntu@61c39b1d82f5:~/charms/trusty/pig$ juju status
...
App  Version  Status   Scale  Charm  Store  Rev  OS      Notes
pig           blocked      1  pig    local   11  ubuntu
```

So, is this actually useful?  I think not, because check this out -- i'm gonna forcefully drop the 'revision' down and upgrade the charm:
```
ubuntu@61c39b1d82f5:~/charms/trusty/pig$ echo '5' > revision
ubuntu@61c39b1d82f5:~/charms/trusty/pig$ juju upgrade-charm --path=. pig
Added charm "local:trusty/pig-12" to the model.
ubuntu@61c39b1d82f5:~/charms/trusty/pig$ juju status
...
App  Version  Status   Scale  Charm  Store  Rev  OS      Notes
pig           blocked      1  pig    local   12  ubuntu
```

If juju is going to increment the deployed revision and ignore the 'revision' file on upgrade, I'm struggling to see the value in specifying anything in that file in the first place.

Happy to hear of a use case where this is useful, but if there isn't one, i recommend we change the `upgrade-charm` docs like this:
```patch
- Each local charm gets uploaded with the revision specified in the charm, if possible, otherwise it gets a unique revision (highest in state + 1).
+ Each local charm gets uploaded with a unique revision (highest in state +1).
```

**Comment by mitechie** [comment]
I expected this to not actually set the deployed revision but set metadata
that could be pulled about the charm specific data. The revision
deployed/from the store is a completely different chunk of data that the
git/vcs information.

**Comment by pmatulis** [comment]
Since the revisions file is deprecated is there anything related to revisions that needs to be clarified in the documentation?

**Comment by kwmonroe** [comment]
@pmatulis fwiw, i'm +1 on making `revision` docs a no-op (beyond what we already state: the `revision` file is deprecated).

@mitechie it is odd to me that `charm release` puts a `revision` file in the store.  Is that just a cargo'd thing?  ie, there is no `revision` in k8s nor bigdata charm sources, yet it's there in every charm we release:

https://api.jujucharms.com/charmstore/v5/~containers/kubernetes-master/archive/revision
https://api.jujucharms.com/charmstore/v5/hadoop-namenode-46/archive/revision

**Comment by pmatulis** [comment]
@kwmonroe As your second point is not a documentation issue you may want to bring it up in another forum. I suggest the [Discourse "Charming" category](https://discourse.jujucharms.com/c/charming).

I'm closing this current issue if that's ok.
