### ISSUE TITLE
Policy Update: Propritary applications must use terms and resources when possible

### ISSUE THREAD

**Issue by arosales** [juju/docs#1120]
I would like to suggest to update the Charm Store policy to require Charm deploying proprietary applications to use terms, and when possible use resources.

**Comment by marcoceppi** [comment]
I second this motion, but we need to have this discussion on the mailing list to the community at large.

**Comment by arosales** [comment]
> I second this motion, but we need to have this discussion on the mailing list to the community at large.

Very good point I'll mail the list on it.

**Comment by arosales** [comment]
Mail list reference:
https://lists.ubuntu.com/archives/juju/2016-May/007244.html

**Comment by matthewhelmke** [comment]
It has been more than 7 months. Did this ever happen?

**Comment by chuckbutler** [comment]
We haven't made the doc contribution to my knowledge. But we did however, bring it up on the list. We should probably re-ping the list that this is going to enact as policy and move towards that goal. I think this warrants additional follow-up by @arosales to ensure we're still on path with the original goal of this bug.

**Comment by arosales** [comment]
@chuckbutler we didn't get any additional feedback or negative comments on resources and terms. Thus, I think we should update policy, documentation, and tools to reflect this. We have held off on this as we update the review queue to be more automated.  Once we had this we would update process, policy, and documentation.

**Comment by matthewhelmke** [comment]
@chuckbutler and @arosales , we on the docs team get questions occasionally about policies, etc. based on the https://jujucharms.com/docs/stable/authors-charm-policy page. We cannot answer them, but the implication in the queries is that the page and the automated procedures in the charm store do not match. We have no way of knowing one way or another. Any chance you could go through this page right away to make sure it is currently accurate to what exists today, even as you look to future updates?

**Comment by chuckbutler** [comment]
@matthewhelmke I highly doubt I'll be able to get to that this week, but I'm happy to try and circle back at the beginning of next week. I'm going to ping some additional heavyweights for potential eyeballs on this issue.

cc @kwmonroe @johnsca @castrojo

**Comment by pmatulis** [comment]
This issue has gone dormant and will now be expired. Please re-open if this is still important.
