### ISSUE TITLE
document interface layers

### ISSUE THREAD

**Issue by marcoceppi** [juju/docs#1121]
scope, esp

**Comment by matthewhelmke** [comment]
This issue is old enough that I think a quick check to confirm that what is mentioned above is adequate is likely to close the issue.

**Comment by chuckbutler** [comment]
Thanks for taking a look into it @matthewhelmke. If there's any follow up action, tag me and I'll try to cycle in and close the issue out before it becomes even staler than it already is.

**Comment by matthewhelmke** [comment]
I've read through the page a few times. The issue mentioned in the title and original description are no longer valid. If future improvements are desired, we can open new issues. I'm going to close this now.
