### ISSUE TITLE
juju centos docs need updating

### ISSUE THREAD

**Issue by evilnick** [juju/docs#1129]
outdated references and use of old style repository/local deploy

**Comment by pmatulis** [comment]
@evilnick I'm wondering whether CentOS should just be removed from the documentation.

**Comment by evilnick** [comment]
I don't think we can unilaterally decide we don't support CentOS

**Comment by pmatulis** [comment]
affects [juju-centos.md](https://github.com/juju/docs/blob/master/src/en/juju-centos.md)

**Comment by pmatulis** [comment]
I couldn't get very far with this.
https://paste.ubuntu.com/26490488/
