### ISSUE TITLE
https://jujucharms.com/docs/devel left hand nav-bar gone

### ISSUE THREAD

**Issue by arosales** [juju/docs#1141]
When I go to look at the devel version of the docs I loose the left tool bar. I verified this with others in #juju.

https://jujucharms.com/docs/devel/getting-started
 - no left nav bar

I have seen this on Chrome as well as Firefox.

-thanks,
Antonio

**Comment by evilnick** [comment]
yes. I submitted a fix for the nav file a few minutes ago, so it should be live shortly

**Comment by evilnick** [comment]
thanks for reporting it!

**Comment by evilnick** [comment]
Hmmm. there were some minor syntax glitches in the nav code, but I have fixed those and it still seems to be broken. A run through W3c lint suggests all the nav code is valid. will have to escalate with web folks

**Comment by evilnick** [comment]
@matthewhelmke as you still have hours on the clock would you mind following up on this

**Comment by matthewhelmke** [comment]
Fix confirmed.
:cake:
