### ISSUE TITLE
Possibly add a "tips and tricks" section

### ISSUE THREAD

**Issue by petevg** [juju/docs#1147]
I'm not sure that "Tips and Tricks" is the best name for it, but I think that the Juju docs could use a section on some of the more practical aspects of writing and debugging charms.

The first thing a developer might do is deploy some charms to their local LXD environment, and play around with them a bit. It's useful to be able to know that they can do the following to cleanup and get a fresh environment:

```
juju destroy-model default
juju add-model <name>
```

There are invocations that I find myself using in my day to day work that aren't necessarily covered by the other sections in the documentation.

The risk is that a "Tip and Tricks" section would be cluttered, or accumulate notes that really should live elsewhere.

Do people think that such a section would be a good idea? If so, I can put together a draft and submit a PR ...

**Comment by pmatulis** [comment]
@petevg It sounds like you are in the position of documenting a workflow that you find useful. We can take a look and possibly make use of it. I'm sorry for the time it has taken to respond to this issue. The title threw me.

**Comment by pmatulis** [comment]
Barring any forthcoming information I'm closing this for now. Please re-open if you have anything to add.
