### ISSUE TITLE
"juju deploy local:trusty/vanilla" is no longer a supported invocation in juju 2.0

### ISSUE THREAD

**Issue by petevg** [juju/docs#1148]
In the "Getting Started" section of the Developer docs (https://jujucharms.com/docs/devel/developer-getting-started) we instructed people to run `juju deploy local:trusty/vanilla`. This will fail with the following error message:

`ERROR unknown schema for charm URL "local:trusty/vanilla"`

The correct invocation is 

`juju deploy $JUJU_REPOSITORY/trusty/vanilla`

Putting together a PR shortly ...

**Comment by petevg** [comment]
PR here: https://github.com/juju/docs/pull/1149

**Comment by matthewhelmke** [comment]
Fixed via #1149
