### ISSUE TITLE
Note that Charms can now declare a minimum Juju version

### ISSUE THREAD

**Issue by matthewhelmke** [juju/docs#1162]
This needs to be noted somewhere in our Charms section.

There is a new (optional) top level field in the metadata.yaml file
called min-juju-version. If supplied, this value specifies the minimum
version of a Juju server with which the charm is compatible. When a
user attempts to deploy a charm (whether from the charmstore or from
local) that has min-juju-version specified, if the targeted model's Juju
version is lower than that specified, then the user will be shown an
error noting that the charm requires a newer version of Juju (and told
what version they need). The format for min-juju-version is a string
that follows the same scheme as our release versions, so you can be as
specific as you like. For example, min-juju-version: "2.0.1-beta3" will
deploy on 2.0.1 (release), but will not deploy on 2.0.1-alpha1 (since
alpha1 is older than beta3).

Note that, at this time, Juju 1.25.x does *not* recognize this field, so
charms using this field will not be accepted by 1.25 environments.

**Comment by evilnick** [comment]
fixed by #1213
