### ISSUE TITLE
Add note about the current controller indicator to controllers.md

### ISSUE THREAD

**Issue by matthewhelmke** [juju/docs#1171]
To list the controllers that you have created, we use:

    juju list-controllers

      CONTROLLER    MODEL         USER         CLOUD/REGION
      mycontroller* controller    admin@local  joyent/us-east-3
      test          default       admin@local  AWS/eu-west-1

The current controller is indicated with an *.

**Comment by pmatulis** [comment]
This is given here:
https://jujucharms.com/docs/devel/commands#list-controllers

And here:
https://jujucharms.com/docs/devel/users-sample-commands

I'm not sure we need to keep repeating here too:
https://jujucharms.com/docs/devel/controllers#list-controllers

**Comment by matthewhelmke** [comment]
If I were using Juju 2.0 for the first time and wanted to know how to find a list of all controllers, where might I look first? The answer to that question is also the location where we want to have the information.
