### ISSUE TITLE
Expand info about creating new models

### ISSUE THREAD

**Issue by matthewhelmke** [juju/docs#1174]
This would be useful in models.md.

Controller admin users can create new models without needing to specify
any additional configuration:

    juju add-model mynewmodel

In such cases, the new model will inherit the credentials and authorized
ssh keys of the admin model.

Where a cloud requires credentials, non-admin users, and admin users if
they wish, are required to specify a named credential (so that resources
created by the new model are allocated to the cloud account of the model
creator), as well as authorized keys:

     juju add-model mynewmodel --credential mysecrets
        --config authorized-keys="ssh-rsa ...."

Additional model config just for the new model may also be specified:

    juju add-model --config image-stream=daily

**Comment by pmatulis** [comment]
Non-admin-created models was deliberately left out. This may become an official feature of 2.1.

**Comment by matthewhelmke** [comment]
Interesting that it is detailed in the release notes, though.
