### ISSUE TITLE
Docs should use a consistent style

### ISSUE THREAD

**Issue by pmatulis** [juju/docs#1179]
When possible, docs should be consistent by using the style that is in place for 'controllers', 'models', and 'users' (foldouts and referring to commands.md). This will reduce clutter and avoids repetitive explanations for the same command (which requires future updates in multiple places).

To offset the more concise nature of this style, the concept of "walkthroughs" or "journeys" can be employed (hopefully in a Walkthroughs section).

**Comment by evilnick** [comment]
Can we have specific issues instead of general ones? An issue needs to be specific and actionable.
There is no way of 'closing' this issue because it's scope isn't clear or defined
