### ISSUE TITLE
Charm icon docs should be updated

### ISSUE THREAD

**Issue by galgalesh** [juju/docs#1187]
The template from [charm icon docs](https://jujucharms.com/docs/devel/authors-charm-icon) doesn't play well with the new store UI. The inner shadow filter of the template is the biggest issue.

With inner shadow

![with_shadow](https://cloud.githubusercontent.com/assets/1492981/16122876/27dbec4c-33e9-11e6-8866-2d94991fc314.png)

Without inner shadow

![without_shadow](https://cloud.githubusercontent.com/assets/1492981/16122852/07a44d3e-33e9-11e6-9fa4-30e193f04110.png)

**Comment by evilnick** [comment]
Thanks for pointing this out. We can update the guide and tweak the template. I wonder if it might be also useful to tweak the way the icons are used to stop this happening to the umpty-ump ones already in the store?

**Comment by galgalesh** [comment]
This is fixed by the referenced PR
