### ISSUE TITLE
Private clouds require both metadata-source parameter for bootstrap and the image-metadata-url in environments.yaml

### ISSUE THREAD

**Issue by anastasiamac** [juju/docs#1199]
This is certainly true for 1.25

**Comment by anastasiamac** [comment]
@evilnick, 
This bug came about as part of the resolution for https://bugs.launchpad.net/juju/+bug/1594977
Clarification in manual would be very helpful \o/

**Comment by evilnick** [comment]
Hi. are we saying that at some point the 1.25 documentation has at some point become wrong?

**Comment by matthewhelmke** [comment]
@anastasiamac 
Is this saying that we need to add info about specifying the metadata-source in the environments.yaml? I can't see any foundation in the LP bug for an argument that this is needed, only that NOT having the (already documented) image-metadata-url parameter is a problem.

While I have your attention, is there any indication that both (either?) are needed for Juju 2.0, as the tools now live in the controller?

**Comment by anastasiamac** [comment]
metadata-source is used for both tools and images metadata.
The bug was that metadata-source did not work. It does now. It can point to a local directory rather than being served from a web server.
Image-metadata-url specifies a URL for image metadata only. This always worked.

I think that it will be worthwhile to make this distinction very obvious in the documentation. 

As it stands, the title of the issue is no longer correct: you do not need both metadata-source and image-metadata-url.
@evilnick and @matthewhelmke - thank you for following this up \o/

**Comment by matthewhelmke** [comment]
Closed via #1514
