### ISSUE TITLE
network-get hook environment tool undocumented

### ISSUE THREAD

**Issue by stub42** [juju/docs#1200]
Juju 2.0 seems to have just grown a network-get hook environment tool, and it is not yet listed on https://jujucharms.com/docs/devel/reference-hook-tools

In particular, I'd like to know if this is blessed over unit-get for things like retrieving the local IP addresses, and if we actually get an IP address or maybe something else like a DNS name. IPv4 and IPv6 may be mentionable too.

**Comment by dimitern** [comment]
It's currently being documented, with examples, etc. for the 2.0 release. Until done, `juju help-tool network-get` is a way to get help.
