### ISSUE TITLE
Need Private OpenStack Setup docs for Juju 2.0

### ISSUE THREAD

**Issue by arosales** [juju/docs#1205]
We currently have 2.0 docs on how to set up Juju and a Private OpenStack to work together:
https://jujucharms.com/docs/devel/howto-privatecloud

and we have a few lines and adding a cloud:
https://jujucharms.com/docs/devel/clouds#specifying-additional-clouds

but as Jason and the OIL team have found we don't have instructions on how to howto-privatecloud for Juju 2.0

**Comment by evilnick** [comment]
#1139
