### ISSUE TITLE
Pick one: "command line" or "command-line" or "commandline"

### ISSUE THREAD

**Issue by matthewhelmke** [juju/docs#1225]
All three variants can be found in our docs. We need to pick one and be consistent.

**Comment by pmatulis** [comment]
Don't forget "CLI".

**Comment by matthewhelmke** [comment]
The OED uses "command line". If there are no objections by tomorrow morning, I will change references to use this. I'll also look for instances of "CLI" and see what, if anything, should be done in those locations.

**Comment by mbruzek** [comment]
I am +1 to "command line". Possible other cases that could be normalized are "terminal", "command", "shell".

**Comment by matthewhelmke** [comment]
Ah, yes! Thank you. I'll check instances of those key words as well.
