### ISSUE TITLE
Document the automatic retry policy and how to turn it off

### ISSUE THREAD

**Issue by mbruzek** [juju/docs#1235]
It would be great if we could document the retry policy of failed hooks and how to turn it off. I don't know much about it other than the emails I read on the juju-dev mailing list.

https://lists.ubuntu.com/archives/juju-dev/2016-June/005718.html

**Comment by mbruzek** [comment]
https://jujucharms.com/docs/devel/developer-debugging#retrying-failed-hooks

**Comment by evilnick** [comment]
Should add note to https://jujucharms.com/docs/devel/developer-debugging#retrying-failed-hooks
pointing to ./models-config#retrying-failed-hooks
