### ISSUE TITLE
Missing manual provider docs

### ISSUE THREAD

**Issue by chuckbutler** [juju/docs#1240]
In the devel docs we appear to be missing manual provider documentation.

https://jujucharms.com/docs/devel/credentials

**Comment by evilnick** [comment]
The page is there, it is just not linked from the credential page because you don't use credentials with a manual cloud:
https://jujucharms.com/docs/devel/clouds-manual

I recently added links to all these pages back into the navigation too

**Comment by chuckbutler** [comment]
So glad this was PICNIC and not a bug in the docs. Thanks nick :)
