### ISSUE TITLE
Constraints document needs updating

### ISSUE THREAD

**Issue by nskaggs** [juju/docs#1249]
The current constraints docs were last updated in 1.20. It's missing the list of valid options for constraints, as well as examples of machine type constraints. For example, constraints around containers, virt-type, machine properties, etc.

**Comment by nskaggs** [comment]
@anastasiamac perhaps you can help here?

**Comment by anastasiamac** [comment]
@nskaggs Sure thing \o/ I'll update it as part of the work I am currently doing for fixing virt type in image constraints :D Thank you for heads up!

**Comment by evilnick** [comment]
any progress on this @anastasiamac ? Would be useful to have a list if you have one, otherwise we will have to go on a hunt through the code again...

**Comment by anastasiamac** [comment]
@evilnick
I can give you all information I have. It's a little bit jumbled and I would really appreciate if you could polish and make it understandable \o/ It's applicable to current Juju 2.0-beta16.

These are all possible constraints that can be specified:
    * "arch";
    * "container";
    * "cpu-cores";
    * "cpu-power"
    * "mem";
    * "root-disk";
    * "tags";
    * "instance-type";
    * "spaces";
    * "virt-type".
Different providers will support different constraints and, sometimes, different values for these. Different providers also dictate different conflicting constraints, i.e constraints attributes that can not be used in combination.

###Azure Provider:
    * Unsupported: [cpu-power, tags, virt-type]
    * Valid values: arch=[amd64]; instance-type=[defined on the cloud]
    * Conflicting constraints: [instance-type] vs [mem, cpu-cores, arch]

###Cloudsigma (currently behind development flag):
    * Unsupported: [container, instance-type, tags, virt-type]

###EC2 Provider:
    * Unsupported: [tags, virt-type]
    * Valid values: instance-type=[defined on the cloud]
    * Conflicting constraints: [instance-type] vs [mem, cpu-cores, cpu-power]

###GCE Provider:
    * Unsupported: [tags, virt-type]
    * Valid values: instance-type=[defined on the cloud]; container=kvm
    * Conflicting constraints: [instance-type] vs [arch, cpu-cores, cpu-power, mem, container]

###Joyent Provider:
    * Unsupported: [cpu-power, tags, virt-type]
    * Valid values: instance-type=[defined on the cloud]

###LXD Provider:
    * Unsupported: [cpu-cores, cpu-power, instance-type, tags, virt-type]
    * Valid values: arch=[host arch]

###MAAS Provider:
    * Unsupported: [cpu-power, instance-type, virt-type]
    * Valid values: arch=[defined on the cloud]

###Manual Provider:
    * Unsupported: [cpu-power, instance-type, tags, virt-type]
    * Valid values: arhc=[for controller - host arch; for other machine - arch from machine hardware]

###Openstack Provider:
    * Unsupported: [tags, cpu-power]
    * Valid values: instance-type=[defined on the cloud]; virt-type=[kvm,lxd]
    * Conflicting constraints: [instance-type] vs [mem, root-disk, cpu-cores]

###VSphere Provider:
    * Unsupported: [tags, virt-type]

**Comment by matthewhelmke** [comment]
@anastasiamac I see we used to support a `networks` constraint, only on MAAS. Is that one gone?

**Comment by anastasiamac** [comment]
@matthewhelmke I'll confirm for you today/tomorrow. I did not see it in the code but maybe it's been done by magic somehow \o/

**Comment by dimitern** [comment]
The networks constraint is gone for a while now, replaced by the spaces constraint.

**Comment by matthewhelmke** [comment]
@anastasiamac @dimitern Thank you!

**Comment by matthewhelmke** [comment]
Closed via #1336
