### ISSUE TITLE
docs/devel/authors-charm-store: Add callout for migration from LP ingestion to Charm Push for charms

### ISSUE THREAD

**Issue by arosales** [juju/docs#1264]
As we move to a non LP-ingestion charm store we need to migrate existing Launchpad Charms to a charm push model.  Whenever an update is made to an existing charm we need to take the following actions to migrate that existing LP charmers branch charm to an appropriate lp:<app>-team and then charm push.

Thus, this bug is to document the following procedure to migrate an existing LP charm which was under a auto LP-ingestion model to a charm-push model.

I would suggest we have a call out at:
https://jujucharms.com/docs/devel/authors-charm-store

A maintainer would need to do the following:
1. Create a new LP team at https://launchpad.net/people/+newteam
2. Name the team <application-name>-team
3. Add maintainer(s) to the membership of the newly created team
4. Log out/in of charm and jujucharms.com
5. bzr branch the latest of the charm from LP into the current working directory
6. cd into branch and run `charm push . <application>-team/<charm-name>`
7. Ping in #juju for promulgation. Only needed until new review queue is running.

Also note in step 5 the user could then use a different DCVS such as github to house the code.

**Comment by marcoceppi** [comment]
This seems heavy for the push docs where the majority of people will be pushing to a personal branch. Not everyone will need to create a team.

**Comment by johnsca** [comment]
I agree that the default instructions should be for a personal namespace, but we do need to document the team procedure so that we do it consistently.

We should also address moving the repository, since, as I understand it, we no longer want charm repos to live under lp:charms/<series>/<charm> and they should instead have their own LP project, which also addresses how to handle repos for multi-series charms.

**Comment by arosales** [comment]
**todo**: Also need to document maintainer responsibilities, specifically reviewing charms.

**Comment by arosales** [comment]
We also need to inform the maintainer to move the bugs from lp:charms to the new target destination.
