### ISSUE TITLE
Manual Provisioning broken link

### ISSUE THREAD

**Issue by nskaggs** [juju/docs#1265]
We're missing documentation on configuring manual provider for 2.0.

We're redirecting https://jujucharms.com/docs/stable/ to 2.0 docs, thus causing this link in particular is now a 404 https://jujucharms.com/docs/stable/config-manual.

**Comment by evilnick** [comment]
Where is the link directing people to https://jujucharms.com/docs/stable/config-manual ?

There are docs for setting up a manual cloud https://jujucharms.com/docs/stable/clouds-manual
These are including in the main navigation and referenced from other pages within the 2.0 docs

If this is a link from an external source, we should either change it if possible, or set up a redirect

**Comment by nskaggs** [comment]
https://jujucharms.com/docs/1.25/config-manual, https://jujucharms.com/docs/1.24/config-manual has a banner at the top as well.

Weird I couldn't find it. I would simply redirect https://jujucharms.com/docs/stable/config-manual  to https://jujucharms.com/docs/stable/clouds-manual then.

**Comment by evilnick** [comment]
Okay, I will take a scrub through the old docs as well, they shouldn't reference stable/devel for precisely this reason!

**Comment by evilnick** [comment]
The archive docs banner thing is a jujucharms.com issue. I filed https://github.com/CanonicalLtd/blues_browser/issues/1320

**Comment by evilnick** [comment]
Aha! Sorry, I have just twigged. You are saying that when looking at the page in the 1.25 docs, you click on 'stable' above the navigation menu and you get a 404?

That's completely the JS on the jujucharms site - it should, if there is no equivalent page, be crossed out with no link. We can make a redirect for this case and maybe some of the other config pages, but in general the behaviour is wrong. I will raise another issue for that

On the plus side, I *did* find some wrongly specific links in the 1.25 docs, so thanks!

**Comment by evilnick** [comment]
I don't think the Jujucharms code has been corrected, but we have redirects for all the old pages so from a docs perspective this is closed.
