### ISSUE TITLE
Incorrect channels documented

### ISSUE THREAD

**Issue by stub42** [juju/docs#1272]
https://jujucharms.com/docs/stable/charms-deploying lists channels as stable, candidate, beta and edge. However, 'charm push' supports stable and development

**Comment by evilnick** [comment]
These are the channels that were decided on in Vancouver. Are you sure it is not a bug with charm push?

**Comment by marcoceppi** [comment]
They are not yet implemented in the charm store, with no clear timeline.

**Comment by evilnick** [comment]
@mitechie do we have any idea when the correct channels are going to be available from the store?

**Comment by mitechie** [comment]
@urosj can speak to deliver timelines. I believe that edge will be a replacement for development in the near future but that the other two are a ways farther out and we should update the documentation to keep to just the two that do work until they get added.

**Comment by urosj** [comment]
This will be release Monday 8/29

**Comment by evilnick** [comment]
thanks @urosj
