### ISSUE TITLE
Developer Getting started mentions reactive but offers no explanation on what it is

### ISSUE THREAD

**Issue by chuckbutler** [juju/docs#1274]
We have done a good job of putting the layer charming approach at the forefront but have not done anything aside from mentioning reactive on the  getting started guide for developers.

We mention it but offer no links to learn more or even a description of what it provides. 

for reference [Developer Getting Started](https://jujucharms.com/docs/stable/developer-getting-started#writing-your-charm)

>  The basic layer provides charm helpers python library and the reactive framework that makes layers possible

We should at bare minimum link to the reactive documentation on pythonhosted.

**Comment by matthewhelmke** [comment]
@chuckbutler I noticed today that we have a paragraph on this topic in the howto-charm-with-docker page. You may find that a copy/paste/edit of that content gives you a quick means of getting something written and placed in the developer getting started page.

**Comment by chuckbutler** [comment]
Fantastic idea @matthewhelmke, thanks for the reference
