### ISSUE TITLE
backport gce changes to 1.25

### ISSUE THREAD

**Issue by evilnick** [juju/docs#1277]
#1276 should be backported to 1.25

**Comment by evilnick** [comment]
@matthewhelmke didn't we do this?

**Comment by matthewhelmke** [comment]
@evilnick I just looked at https://jujucharms.com/docs/1.25/config-gce and it is using the updated graphics, but the text is unchanged. I'm going to say, "No, we didn't."

**Comment by matthewhelmke** [comment]
Closed via #1418
