### ISSUE TITLE
Add changing log level to troubleshooting Juju docs

### ISSUE THREAD

**Issue by galgalesh** [juju/docs#1285]
The logging system [explained on the list](https://lists.ubuntu.com/archives/juju/2013-September/002998.html) should be documented in the docs. A possible place to add this info might be here: https://github.com/juju/docs/blob/master/src/en/troubleshooting.md

**Comment by joseeantonior** [comment]
@matthewhelmke Looks like this was incorrectly referenced in another issue - mind taking a look, please? Thanks!

**Comment by matthewhelmke** [comment]
Thanks, @joseeantonior . I've fixed the reference in the other issue (should have referenced #1284).

**Comment by evilnick** [comment]
was fixed with #1864
