### ISSUE TITLE
interface-layers needs expanded documentation on {{requires:foo}}-relation-{{joined,changed}}

### ISSUE THREAD

**Issue by lazypower** [juju/docs#1288]
These "magic strings" as it were put, is confusing. 

x-ref with: https://bugs.launchpad.net/charm-helpers/+bug/1611024

relevant information:

> There's a lot of templating that is getting expanded behind the scenes, but for a layer user or charm author, this doesn't get exposed in any way that explains what is expected. And since there are strings for interface names, relation names, and service names, it's tempting to just try the cross-product of them when things don't work. This tends to waste time.

This expands a few repositories, and has been addressed in the callout to juju-info here: https://github.com/juju-solutions/interface-juju-info/pull/3

However the developer guide has examples illustrating the usage of these "magic strings" but doesn't offer a detailed insight into what they are actually doing, its more of an implied learning exercise.

This should have a header and at least a brief blurb of what they are doing, and why this is necessary, and what it looks like in a properly formed charm's metadata and reactive code.

**Comment by fengxia41103** [comment]
I agree this is not charmhelpers issue.

We need a document on relation that shows what these special strings are. For example, what is the difference between @hook('myrelation-joined') vs. @hook('{provides:myrelation}-relation-{joined}')?
