### ISSUE TITLE
charm tool page out of date

### ISSUE THREAD

**Issue by bac** [juju/docs#1308]
The page at https://jujucharms.com/docs/2.0/tools-charm-tools is no longer accurate as the subcommands to the charm command have changed.  E.g. `charm publish` is now `charm release`.

Also any discussion of channels needs to change when Juju 2.0 beta 16 is released. Instead of two channels (development and stable) there will now be four: edge, beta, candidate, and release.

**Comment by matthewhelmke** [comment]
This should be fairly quick to read through and check. I think much of this has been done.
