### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by bac** [juju/docs#1313]
At the bottom of 

https://jujucharms.com/docs/stable/developer-layers

```The Getting started guide contains steps on how to build a layer into a charm.```

has a link to https://jujucharms.com/docs/stable/devel/developer-getting-started#assemble-the-layers , which does not exist.

**Comment by bac** [comment]
The links in that file are not relative as they should be, which leads to the 'stable/devel' situation above.

**Comment by marcoceppi** [comment]
Good point, I'll open a new PR
