### ISSUE TITLE
Juju status and other images are outdated

### ISSUE THREAD

**Issue by hatched** [juju/docs#1324]
Originally reported by @nskaggs : https://github.com/CanonicalLtd/jujucharms.com/issues/327

Juju 2.0 has done several UI cleanups over the course of the cycle. The images for example for juju status on https://jujucharms.com/docs/2.0/getting-started-general are now out of date. It would be useful to check images and expected outputs for visual information commands as the layouts have changed.

**Comment by evilnick** [comment]
thanks.
We did notice this earlier in the cycle, but after the first 2 times we changed the images we thought we would wait a bit. I guess it is safe now

**Comment by evilnick** [comment]
Addendum, I believe there are further changes to be made to status, so we may hold off for RC1 on this

**Comment by pmatulis** [comment]
This is done. Closing.
