### ISSUE TITLE
Consider using a "Edit on github" link

### ISSUE THREAD

**Issue by castrojo** [juju/docs#1339]
I was looking something up on the rocket chat documentation, and they have a handy link where each page can link directly to its source page on github:

https://rocket.chat/docs/user-guides/remote-video-monitoring/

That is really handy and might encourage more contributions.

**Comment by evilnick** [comment]
thanks, we'll take a look

**Comment by pmatulis** [comment]
Seeing that this is 12 months old and nothing has been done I'm marking **Invalid** and closing.
