### ISSUE TITLE
channels docs are out of date

### ISSUE THREAD

**Issue by mitechie** [juju/docs#1345]
https://jujucharms.com/docs/stable/authors-charm-store

The channels are different per:
https://blog.jujugui.org/2016/08/30/jujucharms-com-updated-with-new-channel-support/

**Comment by evilnick** [comment]
The user docs for channels are already updated. This section of developer docs need to be updated too, but I'm not sure that the charm tools actually support this yet

https://github.com/juju/charmstore-client/issues/81

**Comment by matthewhelmke** [comment]
Fixed in #1557
