### ISSUE TITLE
There is no "charm publish" command anymore

### ISSUE THREAD

**Issue by anthonydillon** [juju/docs#1348]
The page at https://jujucharms.com/docs/stable/authors-charm-store talks about the `charm publish` command, but that command was replaced by `charm release` in 2.2.0-0ubuntu1~ubuntu16.04.1~ppa2 which is currently in the stable juju ppa.

Moving: https://github.com/CanonicalLtd/jujucharms.com/issues/331

**Comment by matthewhelmke** [comment]
This page also needs charm command updates: https://jujucharms.com/docs/stable/tools-charm-tools

**Comment by matthewhelmke** [comment]
Fixed in #1557
