### ISSUE TITLE
juju login changes should be documented

### ISSUE THREAD

**Issue by matthewhelmke** [juju/docs#1352]
`juju login` now supports external users. If you have identity-url  configured, you must now explicitly specify a user name on the command line to log in as a local user.

When a login expires for local users, you will now be automatically  prompted, rather than getting an error back telling you to run `juju login`.

Macaroons for local users are now stored in the cookie jar, as with  external users. There is a known issue with logout (#1621375) which will be addressed in beta19.

**Comment by anastasiamac** [comment]
beta19 does not exist :) Our next release is 2.0-rc1

**Comment by matthewhelmke** [comment]
Thanks, @anastasiamac ! (That was a copy/paste from the beta18 release notes.)

**Comment by matthewhelmke** [comment]
And, yay! Excited to have an RC.
