### ISSUE TITLE
Layer options are mostly undocumented

### ISSUE THREAD

**Issue by lazypower** [juju/docs#1356]
The charm author docs are missing reference material for layer.yaml options which are a build time construct.

These surface from layer basic and further docs can be extracted from there

**Comment by evilnick** [comment]
@chuckbutler We will happily take a pass at this but would need some eco input on where to find which options can be set

**Comment by chuckbutler** [comment]
@evilnick that's the fun part! It's up to the author to both define both the options and then the down-stream implementor can override them in a very generic way.

I'll see if I can get something pulled together to lend a hand here and your team should be able to massage my broken american-english out of it.

**Comment by marcoceppi** [comment]
https://github.com/juju-solutions/layer-basic#layer-options

**Comment by pmatulis** [comment]
Half of the above resource is already in the docs (copied from there into the docs I imagine) and the other half does not contain any pertinent information. Blocked again.
