### ISSUE TITLE
There's no information about destroying juju environment in charms-destroy page

### ISSUE THREAD

**Issue by anthonydillon** [juju/docs#1374]
Hello,

There's no information about destroying juju environments in juju v2 charms-destroy document although there's a mention about "destroying environments" in the page title which is confusing :
https://jujucharms.com/docs/2.0/charms-destroy

And I know there's no `$ juju destroy-environment` anymore with the juju v2 but I believe people would want to destroy their juju environments still in v2.

I think `$ juju destroy-controller --destroy-all-models -y controller-name` should do the trick for v2.

Migrated from: https://github.com/CanonicalLtd/jujucharms.com/issues/335

**Comment by matthewhelmke** [comment]
We have updated the linked page with links to guide users in destroying models and controllers and have removed the word "environments" from the page.

Thank you.
