### ISSUE TITLE
Azure help pages will need to change - userpass deprecated

### ISSUE THREAD

**Issue by evilnick** [juju/docs#1375]
Currently the guide for configuring Azure uses username/password, but this will no longer be supported.

**Comment by axw** [comment]
@evilnick Also, the steps that talk about registering providers is no longer necessary as of a very recent update. Sorry, I had meant to ping you earlier.

**Comment by evilnick** [comment]
Thanks for the extra info!

**Comment by axw** [comment]
@evilnick And if you haven't seen it yet, I've just emailed the juju@ list with details about a new "interactive" auth-type for Azure.

> To add a credential for Azure, you now do the following:
>  - run "juju add-credential azure"
>  - enter credential name of your choosing
>  - select the "interactive" auth-type
>  - enter your subscription ID [0]
>  - you will now be prompted to open a URL and enter a code, then proceed to authenticate with Azure and authorise Juju to create credentials on your behalf. Once you have given your consent, Juju will do the rest.
>
> [0] your subscription ID can be found in the Azure Portal, under the Subscriptions blade: https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade

**Comment by evilnick** [comment]
@awx thanks! I was just reading the mail to the list. We will try and get this fixed up today
