### ISSUE TITLE
bootstrap rackspace provider docs not accurate

### ISSUE THREAD

**Issue by jamesbeedy** [juju/docs#1377]
Need accurate rackspace bootstrap docs. Currently, following juju 2.0 documentation, the rackspace provider will not bootstrap -> http://paste.ubuntu.com/23189335/

**Comment by axw** [comment]
@jamesbeedy don't set domain-name. The add-credential command should be fixed to stop prompting for it. I've filed https://bugs.launchpad.net/juju/+bug/1624831.

**Comment by matthewhelmke** [comment]
@axw thank you for the info!

@jamesbeedy thank you for reporting the issue. I don't see anything in this docs page that needs to change: https://jujucharms.com/docs/stable/help-rackspace . Since there is now a bug filed on the actual command, perhaps we don't have anything to update docs-wise. Just in case, I wanted to ask you if there was another page you were looking at and I'll give it a review as well.

**Comment by jamesbeedy** [comment]
@axw, @matthewhelmke, not setting the domain name AND providing the correct password worked   for getting past the authentication error :-) Now I'm stuck [here](http://paste.ubuntu.com/23204933/) :-(

Are there docs for generating image metadata for rackspace?

thx

**Comment by matthewhelmke** [comment]
Hmm. I've been researching for a couple hours and haven't found a docs solution. From the error message, it looks like there is no image. See comment 1 in this bug: https://bugs.launchpad.net/juju/+bug/1625243. Perhaps this is related to your problem.

**Comment by matthewhelmke** [comment]
@jamesbeedy ^

**Comment by evilnick** [comment]
@jamesbeedy theoretically, yes, you could generate metadata for images, store them in rax storage and then point to them (which is how we did it up until a few weeks ago before there were proper images). Given some of the comments on the various rackspace issues I'm not sure even that would work right at the moment.

**Comment by jamesbeedy** [comment]
@mathewhelmke, @axe, @evilnick thanks for your insight here. It looks like the appropriate bugs exist for the issues I'm experiencing, hence not a documentation issue - my bad.

**Comment by matthewhelmke** [comment]
@jamesbeedy no worries. I would rather have an unnecessary bug filed and investigated than miss something that needs to be fixed. :smile:

**Comment by evilnick** [comment]
@jamesbeedy that's totally okay - we will likely need to document changes when it *is* working anyway, and we would rather you got some help with your issues even if it isn't necessarily a docs one :smile:
