### ISSUE TITLE
 Pointer to docs for bootstrap process per cloud

### ISSUE THREAD

**Issue by anastasiamac** [juju/docs#1378]
To address https://bugs.launchpad.net/juju/+bug/1624677, we need to have pages describing bootstrap experience per cloud.

**Comment by evilnick** [comment]
Yes, I saw that bug. I think we need to think about the URLs we want to add there - they will need to be versioned and ideally as flat as possible, so I suggest:

https://jujucharms.com/docs/2.0/bootstrap-aws

etc

**Comment by pmatulis** [comment]
We already have individual cloud pages. I updated the LP bug and I'm closing this one.
