### ISSUE TITLE
Leadership docs show invalid code examples

### ISSUE THREAD

**Issue by sparkiegeek** [juju/docs#1379]
The code examples in the [leadership page in the Developer guide](https://jujucharms.com/docs/devel/developer-leadership#...share-one-shot-configuration-among-units?) are poorly formatted and non-idiomatic Python.

Although it's marked up as a `<pre>` the CSS of the block has `white-space: pre-line` which will collapse sequences of white space (albeit breaking at new lines). It should have (the browser default for `<pre>`) of `white-space: pre`

Secondly instead of using `!` to negate the condition, one should use `not` so e.g. instead of `if !valid_settings(leader_get()):` it should read `if not valid_settings(leader_get()):`

**Comment by evilnick** [comment]
Thanks for spotting this! (was rather an easy one so I just went ahead and fixed it)

**Comment by sparkiegeek** [comment]
This has regressed - the code sample in the expanded "...share varying configuration among units?" snippet is still badly formatted (not showing leading whitespace, has some "source markdown" leaking to the webpage

**Comment by pmatulis** [comment]
Related to https://github.com/canonical-webteam-archive/vanilla-docs-theme/issues/10

**Comment by pmatulis** [comment]
For now, I will make a sub-page of these 4 "howto" entries that does not utilize foldouts.
