### ISSUE TITLE
Add additional tags to https://jujucharms.com/docs/stable/authors-charm-metadata

### ISSUE THREAD

**Issue by anthonydillon** [juju/docs#1385]
Hoping we might be able to add additional tags to the charm store.
In this case:
testing XOR continuous-integration (XOR ci or something along those lines)

And it seems like there are some tags that are using underscores and some that use spaces. Which is preferred? It seems like there should be only one way of doing it.

Ported from: https://github.com/CanonicalLtd/jujucharms.com/issues/328

**Comment by evilnick** [comment]
Policy matter, not a documentation issue
