### ISSUE TITLE
Payloads are undocumented

### ISSUE THREAD

**Issue by anthonydillon** [juju/docs#1386]
I think payloads landed sometime in 1.x (?), but are undocumented apart from the generated hook tool documentation. They seem to be using a very odd definition of 'payload', so might be worth starting with what they are in the juju context and why you would use them.

Ported from: https://github.com/CanonicalLtd/jujucharms.com/issues/330

**Comment by evilnick** [comment]
This was blocked pending this bug which I believe is fixed https://bugs.launchpad.net/juju/+bug/1567518

from the release notes:
Payload management for charmers

The new payload management feature allows charmers to more accurately define large and complex deployments by registering different payloads, such as LXC, KVM, and docker, with Juju. This lets the operator better understand the purpose and function of these payloads on a given machine.

You define these payloads in the metadata.yaml of the charm under the payloads section. You create a class for the payload, "monitoring" or "kvm- guest", and assign the type.

payloads:
  monitoring: 
     type: docker 
  kvm-guest: 
     type: kvm 

From your charm hook you can manage your payload with the following commands:

payload-register <type> <class> <ID> [tags] 
payload-unregister <type> <class> <ID> 
payload-status-set <type> <class> <ID> <starting, running, stopping, stopped> 
From the Juju command line you can view your payloads like this:

 juju list-payloads <filter> 
For more information run:
juju help payloads
