### ISSUE TITLE
Anchor tags missing on https://jujucharms.com/docs/stable/commands

### ISSUE THREAD

**Issue by nskaggs** [juju/docs#1387]
For example, https://jujucharms.com/docs/stable/commands#add-ssh-key. Others do seem to exist, so a review might be in order.

**Comment by matthewhelmke** [comment]
Reviewed.

I tested the page in Google Chrome 54.0.2840.27 beta (64-bit) and in Firefox 48.0, both on Ubuntu 16.04LTS and could not reproduce. In my tests, every command has a working anchor.

I read through the source file and an anchor is required to create each of the dropdowns for the commands.

**Comment by nskaggs** [comment]
@matthewhelmke sorry; I tested again this morning to make sure I wasn't crazy, and I didn't see the anchor tag in source. Anyways, I will concur it's just me then. Thanks for checking.

**Comment by matthewhelmke** [comment]
@nskaggs no worries. Better to check unnecessarily than to miss something necessary. :smile:
