### ISSUE TITLE
reference-hook-tools needs to be checked against 2.0

### ISSUE THREAD

**Issue by matthewhelmke** [juju/docs#1398]
While making the updates in #1300 to close #1299, I started to wonder whether this entire page contains instances of outdated documentation, such as old commands. The whole page should be checked and updated as needed for 2.0 now that the commands are stable with the rc release.

**Comment by matthewhelmke** [comment]
I'll give this one last check to be certain. I suspect you are correct, but with all the changes we saw during this release cycle, I want to make sure we don't miss anything.

**Comment by matthewhelmke** [comment]
Missing:
- add-metric add metrics
- application-version-set specify which version of the application is deployed

I will add them to the page.

Out of order
- open-port is listed out of alphabetical order

I will move it.

In the page, but not the list above:
- payload-status-set
- payload-register
- payload-unregister

I will remove them.

**Comment by evilnick** [comment]
Hmmm. there is always the possibility that that list is incorrect - it comes from juju

to check you can deploy a charm then use juju run

**Comment by evilnick** [comment]
it seems likely that payload stuff *should* be there

**Comment by matthewhelmke** [comment]
Perhaps we should wait for confirmation. Who can we ask?? @anastasiamac perhaps?

**Comment by matthewhelmke** [comment]
Rather cryptic...
'''bash
ubuntu@20160921-rc1:~$ juju help-tool add-metric
Usage: add-metric key1=value1 [key2=value2 ...]

Summary:
add metrics
'''

**Comment by matthewhelmke** [comment]
Better:
```
ubuntu@20160921-rc1:~$ juju help-tool application-version-set
Usage: application-version-set <new-version>

Summary:
specify which version of the application is deployed

Details:
application-version-set tells Juju which version of the application
software is running. This could be a package version number or some
other useful identifier, such as a Git hash, that indicates the
version of the deployed software. (It shouldn't be confused with the
charm revision.) The version set will be displayed in "juju status"
output for the application.
```

**Comment by evilnick** [comment]
yes.

I can confirm that:
payload-status-set
payload-register
payload-unregister
are all present in rc1

**Comment by matthewhelmke** [comment]
Thank you. I'll make the updates based on available info for the two new ones, then, and leave the payload stuff alone.

**Comment by evilnick** [comment]
https://bugs.launchpad.net/juju/+bug/1628919

**Comment by matthewhelmke** [comment]
@anastasiamac to add the two missing hook tools to the page, I will need proper examples to include with them, for python and bash, as appropriate. Can you help, please?

- add-metric
- application-version-set

**Comment by evilnick** [comment]
probably more useful to loop in @cmars , @mbruzek and @chuckbutler

**Comment by matthewhelmke** [comment]
Thank you, @evilnick

**Comment by chuckbutler** [comment]
@matthewhelmke 

```python

from charmhelpers.core.hookenv import application_version_set

@hook('update-status')
def update_application_version():
    application_version_set('1.1.10')
```

```shell

@hook 'update-status'
function update_status() {
    application-version-set 1.1.10
}
```

**Comment by chuckbutler** [comment]
re: 

> and leave the payload stuff alone.

Whats the story here? Do we need good examples for this or are we punting on payloads? I haven't implemented the payload components into our k8s charms yet, but have plans on doing so soon for the addon containers so its easy to see at a glance which unit received the run stanza and where they are in the cluster during outages to determine which namespaces are affected...

so I can pitch in here in the next week or so

**Comment by evilnick** [comment]
@chuckbutler you might want to coordinate with @bz2 who I believe is also looking at help-text related bugs

**Comment by evilnick** [comment]
p.s. thanks!

**Comment by matthewhelmke** [comment]
Thank you, @chuckbutler

**Comment by matthewhelmke** [comment]
#1415 added info on add-metric (thanks to @cmars for doing this!).
I am still polishing info on application-version-set.
