### ISSUE TITLE
Juju 2.0 LXD onboarding is unclear and leads to a broken installation

### ISSUE THREAD

**Issue by cmars** [juju/docs#1425]
The instructions here are not very clear: https://jujucharms.com/docs/2.0/clouds-LXD#prerequisites

Several issues with this:
- The latest LXD in ppa:ubuntu-lxc/lxd-stable has compatibility problems with 2.0-rc2
- 15.10 is EOL and users shouldn't even see mention of it here.
- Instructions for installing on Xenial could be much clearer, with the necessary `apt install` command example at the top.
- If Xenial is the only supported distro release for Juju 2.0, documentation should say so.
- If Trusty is supported via backports, documentation should say so.

@mitechie Please clarify on which distro releases Juju 2.0 LXD supports.

**Comment by evilnick** [comment]
Thanks for raising these points. there is actually a refresh of this page in progress which fixes most of these.

**Comment by matthewhelmke** [comment]
Fixed in #1426
