### ISSUE TITLE
details of regions/list-regions need to be added

### ISSUE THREAD

**Issue by evilnick** [juju/docs#1438]
example:
$ juju regions aws
Region
us-east-1
us-west-1
us-west-2
eu-west-1
eu-central-1
ap-south-1
ap-southeast-1
ap-southeast-2
ap-northeast-1
ap-northeast-2
sa-east-1

Try 'show-cloud aws' to see more detail for each region.

**Comment by howbazaar** [comment]
Pretty sure that Region heading isn't there...

$ juju regions aws
us-east-1
us-west-1
us-west-2
eu-west-1
eu-central-1
ap-south-1
ap-southeast-1
ap-southeast-2
ap-northeast-1
ap-northeast-2
sa-east-1

**Comment by evilnick** [comment]
yes, but only because you had @wallyworld  remove it :smiley:

**Comment by matthewhelmke** [comment]
Do we have an ETA for this to arrive in a release, so I can test it before trying to write it up?
