### ISSUE TITLE
The order of the cloud/region and controller name arguments will be swapped

### ISSUE THREAD

**Issue by matthewhelmke** [juju/docs#1439]
From an email from Ian Booth to the Canonical Juju list:

Old:
`$ juju bootstrap mycontroller aws/us-east-1`

New:
`$ juju bootstrap aws/us-east-1 mycontroller`
or now
`$ juju bootstrap aws/us-east-1`

Notice how controller name is optional. It will default to cloud-region.
eg
```
$ juju bootstrap aws
Creating Juju controller "aws-us-east-1" on aws/us-east-1
```

**Comment by evilnick** [comment]
thx :smile:
