### ISSUE TITLE
Wrong command on https://jujucharms.com/docs/2.0/clouds-maas

### ISSUE THREAD

**Issue by bac** [juju/docs#1478]
(copying an issue from https://github.com/CanonicalLtd/jujucharms.com/issues/361)

The following command is wrong on https://jujucharms.com/docs/2.0/clouds-maas:

Now you can create a Juju controller with the bootstrap command:
juju bootstrap prodmaas prodmaas-controller

It should be:

juju bootstrap prodmaas-controller prodmaas

**Comment by matthewhelmke** [comment]
Thank you! I thought I got them all in #1440, but I obviously missed this one. I appreciate you catching it and letting us know.
:cake:

I have fixed it.
