### ISSUE TITLE
Link to Vagrant Workflow is broken on all but the 1.25 version of docs

### ISSUE THREAD

**Issue by anthonydillon** [juju/docs#1489]
The link under User Guide > How to > Vagrant Workflow is broken for all but the 1.25 version of docs.

**OK:**
https://jujucharms.com/docs/1.25/getting-started

**Broken:**
https://jujucharms.com/docs/2.0/howto-vagrant-workflow/
https://jujucharms.com/docs/stable/howto-vagrant-workflow/
https://jujucharms.com/docs/devel/howto-vagrant-workflow/

Ported from: https://github.com/CanonicalLtd/jujucharms.com/issues/356

**Comment by matthewhelmke** [comment]
This is similar to #1284 and will require a fix like #1365. I'll take care of it.
