### ISSUE TITLE
Add local charm example to the bundles page

### ISSUE THREAD

**Issue by szeestraten** [juju/docs#1504]
The Using and Creating Bundles page needs an example of how to deploy local charms.

**Comment by matthewhelmke** [comment]
@szeestraten just confirming that you are working on this. Not trying to rush you...just making sure I understood our conversation correctly.

**Comment by szeestraten** [comment]
@matthewhelmke Got a bit swamped at work so I might not have the opportunity to work on this for a while so please feel free to assign this to someone else.

**Comment by pmatulis** [comment]
This seems to have been satisfied by PR #1869. Closing.

**Comment by szeestraten-ntnu** [comment]
@pmatulis, that PR does not satisfy this issue at all. 
This issue is about deploying local charms from bundles which neither that PR or the current docs cover.

Please reopen.

**Comment by matthewhelmke** [comment]
:tumbler_glass: 
Glad to see this finally sorted. (I received the notification and thought I would use it as an excuse to say hello.)

**Comment by pmatulis** [comment]
Thanks Matthew. I hope you're doing well. Cheers. :tumbler_glass:
