### ISSUE TITLE
Using MAAS with Juju errors

### ISSUE THREAD

**Issue by sparkiegeek** [juju/docs#1505]
https://jujucharms.com/docs/stable/clouds-maas

1. `juju bootstrap prodmaas-controller prodmaas` in final instruction has the cloud name and controller name the wrong way around (IIRC this was a late change in Juju 2.0), the correct invocation is `juju bootstrap prodmaas prodmaas-controller`
2. The example YAML file for `clouds.yaml` spells MAAS incorrectly (mass vs. maas)

**Comment by degville** [comment]
Thank you! The controller/cloud order is fixed in the devel branch (along with the list-clouds output) and needs to be backported to 2.0, and I'll fix the typo in clouds.yaml.
