### ISSUE TITLE
Non-layered walkthrough still surfaced in docs

### ISSUE THREAD

**Issue by johnsca** [juju/docs#1515]
https://jujucharms.com/docs/2.0/authors-charm-writing is linked from the Charm Authors page (https://jujucharms.com/docs/2.0/authors-intro) and also comes up as the second result when searching for "charm docs" (https://www.google.com/search?q=charm+docs).

This should be promoting https://jujucharms.com/docs/2.0/developer-getting-started instead.

**Comment by matthewhelmke** [comment]
@johnsca thank you, I'll get this updated.

**Comment by evilnick** [comment]
This isn't quite such an easy fix. There are loads of 'old' author related docs which were superceded by new stuff which landed, but weren't replaced properly. Some of the old pages are referenced (and required) by the new docs, and some of them aren't.

**Comment by matthewhelmke** [comment]
Mmmmm, okay. Well, step one complete. :-/
