### ISSUE TITLE
Upgrading multi-model controller help clarity

### ISSUE THREAD

**Issue by anastasiamac** [juju/docs#1519]
As per https://bugs.launchpad.net/juju/+bug/1638714, we need to provide user with clearer explanation on how to update multi-model controllers. The distinction between controller model and other models within the controller might benefit from special attention.

**Comment by evilnick** [comment]
Hi, thanks for this. Yes, we should clarify things - as part of the work to fix the actual bug though  is the behaviour going to change? Or is it just that the error message will be updated.

**Comment by anastasiamac** [comment]
@evilnick 
Thank you for asking \o/
I believe that at this stage the behavior will not change. We will be updating error message.
We will keep you informed if we'd change the behavior :D

**Comment by evilnick** [comment]
Fixed in 2.1 and 2.0
