### ISSUE TITLE
Grant and revoke docs

### ISSUE THREAD

**Issue by urosj** [juju/docs#1536]
We need to make better description of grant/revoke mechanism in juju as the one currently in place here [1]. Basically, 

juju grant bob admin my-model
juju revoke bob admin my-model

leaves bob with write and read rights (but not admin anymore). This might surprise people. In order to fully revoke the access to the model one needs to

juju revoke bob read my-model

In order to fully describe consequences, we need to describe that granting affects all roles up to that level (top-down), while revoking affects all roles from that level up (bottom-up). 

[1] https://jujucharms.com/docs/2.0/users-models

**Comment by evilnick** [comment]
this was already fixed :)
https://jujucharms.com/docs/devel/users-models
