### ISSUE TITLE
Many pages still list old `resolved --retry` command

### ISSUE THREAD

**Issue by galgalesh** [juju/docs#1549]
For all occurrences see: https://github.com/juju/docs/search?utf8=%E2%9C%93&q=%22resolved+--retry%22

**Comment by matthewhelmke** [comment]
Is the issue that the 'resolved' command no longer requires/uses the '--retry' flag? Or was this replaced with a different command? Something else?

**Comment by marcoceppi** [comment]
There is no longer a --retry flag, resolved now always retries unless you
specify --no-retry

**Comment by matthewhelmke** [comment]
Thank you. I'll look into this.

**Comment by galgalesh** [comment]
Thanks for fixing this so quickly!
