### ISSUE TITLE
Lack of visual indicators for release notes page

### ISSUE THREAD

**Issue by voidspace** [juju/docs#1561]
When I navigate to the release notes page (firefox on Xenial - all current) the release note sections do not have a visible indicator that they expand. I believe there is supposed to be an arrow to the left of each section, but that is not rendering.

Hovering over them does not provide the normal visual indicator (pointer change) that they are clickable. So to me the page looks like a list of releases with no actual release notes. Clicking on the release numbers *does* expand the release notes, but I only discovered that by accident after spending some time frustrated that the page appeared to be useless. 

https://jujucharms.com/docs/2.0/reference-release-notes

**Comment by mitechie** [comment]
This shows and works for me on Chrome so I wonder if there's a browser issue that we need to get details of. @voidspace can you fill out distro/browser/version details on this? 

Thanks
![juju_release_notes___documentation___juju_](https://cloud.githubusercontent.com/assets/75915/20965860/f20535a2-bc77-11e6-8946-07088b0060c6.png)

**Comment by mitechie** [comment]
Or I'm a moron that can't read and the details are there so this is a pointer that there's definitely a browser issue.

**Comment by matthewhelmke** [comment]
I've been thinking about this today. Would the solution be as simple as adding a short note? Something like this, perhaps?

The versions covered here are (for details, click to expand):

**Comment by matthewhelmke** [comment]
Assuming it is not a browser/function fail issue...

**Comment by evilnick** [comment]
It is a browser issue. The expander triangles are standard HTML5, but Firefox doesn't implement them properly. There should be a js shim to fix this, but apparently it has gone wrong, so we will need to shift this issue to jujucharms.com

**Comment by evilnick** [comment]
moved to https://github.com/CanonicalLtd/jujucharms.com/issues/385
