### ISSUE TITLE
Error in network-get documentation in 2.0 release notes

### ISSUE THREAD

**Issue by voidspace** [juju/docs#1562]
https://jujucharms.com/docs/2.0/reference-release-notes
The documentation for network-get says that a "-r" flag is used to specify the binding name. This is incorrect, it's a positional argument not a flag (and using the flag is an error).

Also, where is "network-get" officially documented? This problem may need fixing in more than one place.  I'm afraid that the sphinx search provided on the online docs won't actually search for "network-get" and always decomposes it into a search for network and get, so I failed to find where the *actual* docs for network-get lives.

**Comment by matthewhelmke** [comment]
`network-get` is documented in the hook tools page: https://jujucharms.com/docs/stable/reference-hook-tools.

**Comment by matthewhelmke** [comment]
Thank you for pointing this out to us, @voidspace 
I've removed the flag from the release notes page. It wasn't in the hook tools page, so hopefully the info we have been given and used there is accurate. If you notice anything else with this that needs to be fixed, feel free to reopen.
