### ISSUE TITLE
Docs for model-defaults do not mention -m

### ISSUE THREAD

**Issue by Cluedrew** [juju/docs#1565]
In the list of possible opinions for model-defaults -m/--model is not given. However it is used twice in the list of examples and the default model is stated to be the current model.

There is also no mention of how specifying a model interacts with giving a cloud/region.

**Comment by evilnick** [comment]
Hi, thanks for reporting this, I can see how it could be confusing - it should be listed with the other options.

This isn't a bug in the docs per se, the command listing is derived from juju's own help text, which seems to be at fault. I will file a bug against that and see if we can't get it fixed before 2.1.
