### ISSUE TITLE
close-port/ open-port no xrange in python3

### ISSUE THREAD

**Issue by mattyw** [juju/docs#1570]
https://jujucharms.com/docs/2.0/developer-hook-tools#close-port

https://jujucharms.com/docs/2.0/developer-hook-tools#open-port

Both sections mention looping using xrange. In python3 (which layers uses by default) there is no xrange

**Comment by chuckbutler** [comment]
Looks like xrange was replaced with range for syntax purposes. In fact it was python2's range() function that was deprecated.

This should be a couple character cleanup.

**Comment by matthewhelmke** [comment]
Closed by #1584
