### ISSUE TITLE
Add a simple graphic to explain controllers on different clouds

### ISSUE THREAD

**Issue by szeestraten** [juju/docs#1575]
It would be great with a simple graphic to illustrate the concept that one needs to bootstrap different controllers for each cloud/substrate. It is easy to think one just needs to bootstrap one single controller which can talk to multiple clouds.

**Comment by matthewhelmke** [comment]
That is an interesting idea we can look into. Thank you! Did you have a specific page in mind when you had the idea? That might spark our creativity even further.

**Comment by szeestraten** [comment]
Maybe https://jujucharms.com/docs/stable/about-juju and/or https://jujucharms.com/docs/stable/clouds

Was thinking about something like: https://imgur.com/SAoFvqn but ya'll might have a better idea.

**Comment by pmatulis** [comment]
I consider this satisfied by PRs #2368 and #2394. Closing this.
