### ISSUE TITLE
getting juju 2 from brew should be preferred

### ISSUE THREAD

**Issue by mitechie** [juju/docs#1576]
https://jujucharms.com/docs/stable/reference-releases

Juju 2.0 is now in brew and able to be installed with brew install juju-2.0 and possibly even juju? 

The instructions for OSX users should lean that way as an easier way than a link to the tarball.

**Comment by degville** [comment]
Thanks for the heads-up. We'll give this a try on OSX and update the docs.

**Comment by evilnick** [comment]
The trouble with this is that the brew release is often significantly delayed from the actual release. Giving brew instructions can therefore be misleading for just released versions. The only version we *know* is available is the tarball
