### ISSUE TITLE
Circular doc reference with zero information for Charm-helpers

### ISSUE THREAD

**Issue by ebalduf** [juju/docs#1586]
This page https://jujucharms.com/docs/stable/tools-charm-helpers leads to this page http://pythonhosted.org/charmhelpers/getting-started.html#installing-charm-tools which has a link to this page https://juju.ubuntu.com/docs/tools-charm-tools.html which doesn't exist and then gets redirected here https://jujucharms.com/  which leads you to click on the 'Docs' link which puts you here https://jujucharms.com/docs/stable/getting-started which has a link 'Charm Helpers' which puts you here https://jujucharms.com/docs/stable/tools-charm-helpers (i.e. back where you started).

**Comment by evilnick** [comment]
I'm marking this as "Fix commited" - I have proposed a change to the upstream charm helpers page to fix the URL there

**Comment by evilnick** [comment]
Thanks for reporting this :)

**Comment by evilnick** [comment]
The upstream patch has been landed so I guess this is fixed whenever their docs regenerate
