### ISSUE TITLE
Docs still point to legacy first charm authoring 

### ISSUE THREAD

**Issue by jamesbeedy** [juju/docs#1591]
Possibly this markdown should be updated with the reactive vanilla example - https://jujucharms.com/docs/2.0/authors-charm-writing

**Comment by jamesbeedy** [comment]
I'm thinking we could probably swap most of ^ with -> https://jujucharms.com/docs/2.0/authors-charm-building

**Comment by evilnick** [comment]
There is a load of cruft in the developer section we are hoping to fix up in the next few weeks - a lot of issues relate to out of date pages that weren't pruned properly when the new method of building charms was added.

Thanks for highlighting this though

**Comment by pmatulis** [comment]
This is being tracked by #2160. Closing.
