### ISSUE TITLE
Missing note to add backports when installing on trusty

### ISSUE THREAD

**Issue by anastasiamac** [juju/docs#1595]
According to https://bugs.launchpad.net/juju/+bug/1656027, the instructions to install Juju on https://jujucharms.com/docs/devel/getting-started-general need to have a special note for trusty users.
Namely, 'apt install -t trusty-backports lxd' before 'apt install juju'

**Comment by matthewhelmke** [comment]
@anastasiamac I noticed that the Launchpad example uses ppa:juju/devel. That change from juju/stable is not needed, correct? We only need the addition of backports for LXD. Just confirming.

**Comment by anastasiamac** [comment]
@nskaggs, do you think this change in ppa is needed as per @matthewhelmke's question?
@matthewhelmke, I think the most important thing here is the explicit statement for trusty users about backports for LXD, yes :D

**Comment by nskaggs** [comment]
Yes, do use juju/stable :-)
