### ISSUE TITLE
LXD credentials

### ISSUE THREAD

**Issue by axw** [juju/docs#1636]
In Juju 2.1, we've had to make some changes to cloud credential handling for LXD. If you're just bootstrapping and adding models on your laptop there is no change in workflow, but there is a change if you want to add models from another machine.

Users are now expected to have a "certificate" credential for creating LXD models. If you're on the LXD host, bootstrap and add-model will both auto-generate a credential as needed, assuming you have access to the LXD Unix socket.

If you intend to add LXD models from another machine (i.e. not the LXD host), you must add credentials to that other machine manually. On the LXD host, you can run `juju autoload-credentials` and select the LXD/localhost option. Then export the credential from the LXD host using `juju credentials localhost --format=yaml > localhost-credentials.yaml`, copy that to the remote host, and on the remote host run `juju add-credential localhost -f <localhost-credentials.yaml>`.

**Comment by degville** [comment]
Thanks for the heads-up, and for the detailed description (and link!).

**Comment by degville** [comment]
Couple of questions @axw - this is with juiju beta 5, so I'm guessing these my be non-issues in rc1 :

- is there any documentation on setting up remote access to hosted LXD Juju? I'd assumed `lxc config set` ... on the host and `lxc remote add` on the client followed by adding this to the remote client's clouds.yaml, but this didn't work:

```yaml
clouds:
  lxd:
      type: lxd
      endpoint: <lxd host endpoint}
```
- juju autoload-credentials doesn't list LXD/localhost as an option in juju b5. I get only 1.    (new). When selected this doesn't list clouds, but it does allow be to generate credentials if I enter localhost manually.

**Comment by axw** [comment]
@degville 

> is there any documentation on setting up remote access to hosted LXD Juju? I'd assumed lxc config set ... on the host and lxc remote add on the client followed by adding this to the remote client's clouds.yaml, but this didn't work:

The specific scenario that was broken by beta5 is this:

On the LXD host:
 - juju bootstrap localhost
 - juju add-user graham
 - juju grant foo add-model

On another host:
 - juju register <blob>
 - juju add-model foo

Before beta5 that would work fine. As of beta5, it complains because the client on that remote host has nothing in its credentials.yaml. So, to work around that (as of rc1), you can perform the following additional steps:

On the LXD host:
 - juju autoload-credentials, selecting the localhost/LXD credential
 - juju credentials --format=yaml localhost > localhost-credentials.yaml
 - copy localhost-credentials.yaml to the remote host

On the remote host:
 - copy localhost-credentials.yaml to ~/.local/share/juju/credentials.yaml before running "add-model"

> juju autoload-credentials doesn't list LXD/localhost as an option in juju b5. I get only 1. (new). When selected this doesn't list clouds, but it does allow be to generate credentials if I enter localhost manually.

Right, support for this is in rc1.
