### ISSUE TITLE
Missing storage documentation from bundles page

### ISSUE THREAD

**Issue by chuckbutler** [juju/docs#1655]
There is support for storage in the bundle spec

https://github.com/juju/charm/blob/v6-unstable/bundledata.go

per @mitechie "I don't believe it can create pools, but can use them via constraints and such. "

**Comment by chuckbutler** [comment]
I haven't been able to dig up any further information on this.... so I think its dead in the water.

**Comment by axw** [comment]
@chuckbutler it is as @mitechie syas: you can use storage constraints in bundles, but there is no place to define storage pools. e.g.

```
postgresql:
    storage:
        pgdata: 100G
```

When deploying, you can override the storage constraints like so:

```
juju deploy my-postgresql-bundle.json --storage postgresql:pgdata=200G
```
