### ISSUE TITLE
LXC loopback mounts need more documentation

### ISSUE THREAD

**Issue by cholcombe973** [juju/docs#1660]
I found that lxc loopbacks are now supported since this [commit](https://github.com/juju/juju/pull/1826/files#diff-abd61728f26e92bea6ee732aa19f7808R17) however it's not clear to me how to enable that functionality.  It mentions in the [docs](https://jujucharms.com/docs/stable/charms-storage#known-limitations) that `allow-lxc-loop-mounts=true` must be set but the question is where?

**Comment by evilnick** [comment]
Hmmm. thanks for that. It seems that this is likely a model config option but it isn't in the table. I guess someone forgot to tell us about it. I will investigate.

In the meantime you can set it like any other model config option <https://jujucharms.com/docs/stable/models-config#getting-and-setting-values>

```
juju model-config allow-lxc-loop-mounts=true
```

**Comment by cholcombe973** [comment]
@evilnick is this only in juju models > 2.0.3?  I'm running 2.0.3 and i get 
```juju model-config allow-lxc-loop-mounts=true
WARNING key "allow-lxc-loop-mounts" is not defined in the current model configuration: possible misspelling
```

**Comment by evilnick** [comment]
that is a very poor error message from Juju ( which there is a bug about) and doesn't mean anything - the real test is if it works. Let me know if not!

**Comment by evilnick** [comment]
Actually it would be helpful if you let me know either way :)

**Comment by cholcombe973** [comment]
Doesn't seem to work.  Maybe I need to recreate the controller?

**Comment by wallyworld** [comment]
You guys are looking at a Juju 1.x config option. Juju 2.x uses LXD not LXC. Loop mounts are not yet supported in 2.x from memory

**Comment by evilnick** [comment]
ah, thanks for the info!

I will remove the reference from the storage docs then
