### ISSUE TITLE
juju gui command changes

### ISSUE THREAD

**Issue by wallyworld** [juju/docs#1664]
The juju gui command has changed. no-browser is now the default behaviour. It also prints the login credential by default. There is a new --hide-credential option not to show the credential.
The --no-browser option is supported but deprecated (it is effectively a no-op). To bring up a browser, use the --browser option.

Snippet from juju gui --help

Details:
Print the Juju GUI URL and show admin credential to use to log into it:

        juju gui

Print the Juju GUI URL only:

        juju gui --hide-credential

Open the Juju GUI in the default browser and show admin credential to use to log into it:

        juju gui --browser

Open the Juju GUI in the default browser without printing the login credential:

        juju gui --hide-credential --browser

**Comment by evilnick** [comment]
Thanks!
