### ISSUE TITLE
cookies location explanation

### ISSUE THREAD

**Issue by anastasiamac** [juju/docs#1666]
As per https://bugs.launchpad.net/bugs/1634945, please clarify for our users that .go-cookies file location can be controlled by setting an environment variable.

**Comment by evilnick** [comment]
We'll certainly look at this, but as it only effects people running Juju without a writeable home directory set (i.e. landscape and maybe some other automated orchestration) I really have no idea where to put this where it might be discoverable. Any advice gratefully received.

As a minimum we can add it to the ENV reference section, but I'm not sure that will help
