### ISSUE TITLE
details on relation-{list,ids,get} are lacking.

### ISSUE THREAD

**Issue by jrwren** [juju/docs#1669]
I've found this to be useful: https://gist.github.com/jrwren/d19672314703010d60dec10f604cf185

Could someone help me modify it for inclusion in the docs?

**Comment by matthewhelmke** [comment]
Sorry, I intended to come back to this after commenting on #1646, but other projects distracted me. I'll close the other issue and we can continue in this new one.

I will work on this and once I have something ready, I'll create a pull request and tag you as a reviewer to help enhance or correct it.

Thanks again for the good idea! Sorry for dropping the ball.

**Comment by jrwren** [comment]
I'm sorry for double reporting. I must have forgotten that I already
created an issue for this. I was not attempting to nag. Thanks for
following up.
