### ISSUE TITLE
split proxy on vsphere provider

### ISSUE THREAD

**Issue by cnf** [juju/docs#1676]
In order to reach my vsphere API, I need to go through a proxy. To reach http://cloud-images.ubuntu.com/releases/streams/v1/index.sjson however, I need to connect directly to the internet.

I have a pac config to do this in my browser, but this obviously doesn't work with the juju command.

When I follow the documentation at https://jujucharms.com/docs/stable/help-vmware I get the following error:

```
$ juju bootstrap myvscloud myvscontroller
Creating Juju controller "myvscontroller" on myvscloud/dc0
ERROR error cleaning up: destroying instances: Post https://<vsphereip>/sdk: unexpected EOF
ERROR invalid URL "http://cloud-images.ubuntu.com/releases/streams/v1/index.sjson" not found
```

```
$ juju --version
2.0.3-sierra-amd64
```

The documentation is unclear how to solve this. Download the image manually, and place it at a set location maybe?

logged here at @chuckbutler request on irc

**Comment by chuckbutler** [comment]
@cnf - i did a little bit of digging on my own before forwarding this over to the core devs. I think this can be worked around with passing proxy config to the bootstrap command

```
--config http-proxy=http://<ip address>:<port>
--config https-proxy=http://<ip address>:<port>
```

Its not as automagic as a pac file, however if you can extract the information for the proxy into those config flags during the bootstrap process, I do believe this will work (presuming the proxy has the capacity to reach those endpoints)

```
juju bootstrap vpower vsphere --config http-proxy=http://5.5.5.5:5555 --config https-proxy=http://5.5.5.5:5555
```

Can you give that a go and let me know if this resolves the issue? If not, we'll need to dig deeper and see what else might unblock this.

**Comment by kwmonroe** [comment]
Drive by comment to build on what @chuckbutler said -- there are 2 places to configure proxies during bootstrap.  One is for the bootstrap machine itself (using `--config` as mentioned above).

The other is for the models that you'll create after bootstrapping.  This can be set with `--model-defaults` during bootstrap and may be needed if charms you plan to deploy need to be proxied.  For example, some charms fetch stuff from pypi, so they'll need internet access.

To handle both of these, I do the following on my juju client (my laptop):

```bash
### On my laptop, in my .bashrc:
...
# no proxy for localhost, my eth0 ip address, and a subnet which i do not want proxied
export no_proxy=`echo localhost 10.245.67.130 10.44.139.{1..255} | sed 's/ /,/g'`
export http_proxy=http://squid.internal:3128
export https_proxy=http://squid.internal:3128
...
```

And now, the bootstrap command I run, again on my laptop:
```bash
$ juju bootstrap \
--config http-proxy=$http_proxy \
--config https-proxy=$https_proxy \
--config no-proxy=$no_proxy \
--model-default http-proxy=$http_proxy \
--model-default https-proxy=$https_proxy \
--model-default no-proxy=$no_proxy \
<cloud> <name>
```

**Comment by cnf** [comment]
Thanks @kwmonroe, I have set http_proxy on my client.

The problem is that I MUST go through the proxy to get to the vsphere API. And I MUST NOT go through that proxy to get to  http://cloud-images.ubuntu.com. 

So when I have http_proxy set, I can not download the cloud image, and when I unset it, I can't access the vsphere api.

**Comment by jameinel** [comment]
You can use:
 --no-proxy=cloud-images.ubuntu.com,...

Just whitelist cloud images as not using the proxy. You'll likely also want
to white list things like 'localhost' and '127.0.0.1'

John
=:->

**Comment by pmatulis** [comment]
It looks like this is a non-issue. Closing now but please re-open if necessary.
