### ISSUE TITLE
tools-metadata-url not recognized config field anymore - juju 2.1

### ISSUE THREAD

**Issue by samantha-jian** [juju/docs#1691]
https://jujucharms.com/docs/2.1/howto-privatecloud

tools-metadata-url should be image-metadata-url.

**Comment by axw** [comment]
Thanks @samantha-jian. It should be agent-metadata-url. image-* is for images, agent-* is for the Juju agent binaries.

**Comment by axw** [comment]
And I see I was totally wrong, sorry. It should indeed be image :)
