### ISSUE TITLE
Broken links on Juju 2.1.0 release notes page

### ISSUE THREAD

**Issue by frankban** [juju/docs#1693]
From https://github.com/CanonicalLtd/jujucharms.com/issues/403

There are broken links on Juju 2.1.0 release notes page at https://jujucharms.com/docs/stable/reference-release-notes . Links which are broken:

https://jujucharms.com/docs/stable/2.1/charms-deploying/#deploying-with-binding
https://jujucharms.com/docs/stable/2,1/network-spaces/
https://jujucharms.com/docs/stable/2.1/charms-bundles/#binding-endpoints-of-applications-within-a-bundle

They all result in "Page not found" error message.

**Comment by degville** [comment]
Thanks for letting us know. We'll fix this asap.
