### ISSUE TITLE
Details and examples for spaces, subnets, spaces constraints and endpoint bindings

### ISSUE THREAD

**Issue by frankban** [juju/docs#1695]
Moved from https://github.com/CanonicalLtd/jujucharms.com/issues/379

Provide a more elaborate description (including example use cases) of spaces, subnets, spaces constraints and endpoint bindings, and how they are materialized on MAAS and other cloud/substrate types.

**Comment by pmatulis** [comment]
involves

[charms-deploying.md](https://github.com/juju/docs/blob/master/src/en/charms-deploying.md)
[network-spaces.md](https://github.com/juju/docs/blob/master/src/en/network-spaces.md)
[charms-constraints.md](https://github.com/juju/docs/blob/master/src/en/charms-constraints.md)
[reference-constraints.md](https://github.com/juju/docs/blob/master/src/en/reference-constraints.md)
[reference-release-notes-1.md](https://github.com/juju/docs/blob/master/src/en/reference-release-notes-1.md)
[reference-release-notes.md](https://github.com/juju/docs/blob/master/src/en/reference-release-notes.md)

**Comment by pmatulis** [comment]
See [LP #1747998](https://bugs.launchpad.net/juju/+bug/1747998)
