### ISSUE TITLE
very confusing that the "getting started pages" links you to a "getting started page"

### ISSUE THREAD

**Issue by mitechie** [juju/docs#1703]
https://jujucharms.com/docs/stable/getting-started

"See the general Getting Started page if you're using something other than Xenial."

which leads you to 

https://jujucharms.com/docs/stable/getting-started-general

We should just call the -general page something else witha new name so that it's distinct.

**Comment by matthewhelmke** [comment]
Agreed. We have talked about this as a team, but haven't finalized a new name. I'm putting this on next week's plan for the docs team to change.

**Comment by evilnick** [comment]
I believe this is now addressed by #1826 et al.
