### ISSUE TITLE
Leadership clarification

### ISSUE THREAD

**Issue by anastasiamac** [juju/docs#1709]
Based on an internal conversation and https://bugs.launchpad.net/bugs/1668238, online documentation needs to add more clarity about what it means for a unit to be a leader, for how long the leader is elected as well as what Juju guarantees as far as leadership is concerned.

**Comment by matthewhelmke** [comment]
This seems pretty clear in [Leadership for the charm author](https://jujucharms.com/docs/stable/developer-leadership). Is there something specific missing from that page? The salient bits of the LP bug above all seem to be in there, right at the top.

**Comment by matthewhelmke** [comment]
I'm going to close this as invalid. Please reopen if something specific is discovered missing. We will be happy to enhance the page in that case.
