### ISSUE TITLE
GUI Example appears to be out of date

### ISSUE THREAD

**Issue by chris-sanders** [juju/docs#1710]
Running through the documentation for 2.1 stable, I've just performed the install for Django as described https://jujucharms.com/docs/stable/tut-google#use-juju's-gui.

While it did deploy trying to see what deployed I only ever get an Internal Server Error from gunincorn. Returning to the charm to see what was expected it states "Note that this bundle will just deploy a rough equivalent of a Django Creating a Project.." which provides a dead link (404). I've stopped troubleshooting at this point and moved on. The point was to see the GUI but an example which is up to date and working out of the box like the Mediawiki example would be significantly better.

**Comment by degville** [comment]
Thanks for letting us know. We'll update this as soon as we can.
