### ISSUE TITLE
juju list-plans requires a charm parameter

### ISSUE THREAD

**Issue by vds** [juju/docs#1712]
The usage string is:
Usage: juju plans [options]

While in the help it says:
Examples:
    juju plans cs:webapp

In fact:
$ juju list-plans 
error: missing arguments

**Comment by matthewhelmke** [comment]
In our [commands reference page](https://jujucharms.com/docs/stable/commands) both `juju plans` and its alias `juju list-plans` appear. In both instances the documentation includes the charm parameter.

I'm closing as invalid. Please reopen if I have misunderstood the issue.
