### ISSUE TITLE
Add example of using variables in bundle

### ISSUE THREAD

**Issue by frankban** [juju/docs#1715]
Moved from https://github.com/CanonicalLtd/jujucharms.com/issues/433

It would be nice if there was an example of using variables in a bundle file. See for example: https://launchpadlibrarian.net/298175262/bundle.yaml

**Comment by frankban** [comment]
Note that native bundles don't support variables.

**Comment by evilnick** [comment]
There doesn't seem to much point in documenting variables in a bundle if Juju cannot use them? Or am I missing something?

**Comment by pmatulis** [comment]
@evilnick @frankban Does this issue apply to both 1.25 and 2.x? Shall we just provide a link to the example bundle file? If not, can we close this?

**Comment by evilnick** [comment]
@pmatulis There really isn't any point asking me - I know as much as you do :)

**Comment by anastasiamac** [comment]
I do not believe that variables as used in juju-deployer are currently supported natively in Juju.
I have opened https://bugs.launchpad.net/juju/+bug/1731387.
Until the functionality provided, I am not sure how you could document an example usage :D

**Comment by howbazaar** [comment]
Hey peeps,

Yes native bundles do support variables, and yes we should come up wwith a good example.

**Comment by anastasiamac** [comment]
This PR adds support for Juju 2.3 going forward - https://github.com/juju/juju/pull/8050....
The example that we are using in this code can be found at https://github.com/juju/juju/pull/8050/files#diff-6b0599fde45dfeaf14e4cb306fc9112dR1924
Feel free to define a different example for online documentation.

**Comment by howbazaar** [comment]
Well, it adds support for using the YAML anchors in the bundle-config files, which it didn't support prior.

The CPE and STS teams have been using YAML anchors for their bundles for quite a while.

**Comment by pmatulis** [comment]
@anastasiamac IIUC, variables have been possible for a long time in bundle definition files via YAML anchors but your cited PR now allows the same in the newer bundle config files. I will need an example of each that I can put into the documentation. FWIW, I do not know what a YAML anchor is. Also, your link to the Juju codebase does not help me.

**Comment by pmatulis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add example of using variables in bundle](https://trello.com/c/sdxW0y4P/3-add-example-of-using-variables-in-bundle)

**Comment by pmatulis** [comment]
This has been fixed on the [Charm bundles page](https://docs.jujucharms.com/charm-bundles#heading--using-YAML-anchors-and-aliases) and on the [Bundle reference page](https://docs.jujucharms.com/bundle-reference).
