### ISSUE TITLE
Add information on attach-storage and detach-storage

### ISSUE THREAD

**Issue by matthewhelmke** [juju/docs#1716]
This is related to #1687 as a continuation of the persistent storage story.

As of today, the `detach-storage` and `attach-storage` commands have landed, but the backends do not yet operate as documented in the spec. The `attach-storage` command will just fail with "not implemented", and `detach-storage` will detach but also destroy.

**Comment by evilnick** [comment]
I find the command names confusing - 

Attach and detach are fine, but remove storage is ambiguous (i.e. does it delete the storage or just detach it)

**Comment by matthewhelmke** [comment]
Yes, this will require some explanation in the documentation.  The spec seems reasonably clear, but there may be questions as the commands are finalized and we can start writing.

**Comment by matthewhelmke** [comment]
Waiting for the commands to be implemented.

**Comment by axw** [comment]
> I find the command names confusing -
>
> Attach and detach are fine, but remove storage is ambiguous (i.e. does it delete the storage or just detach it)

FYI, remove-storage has had couple of changes which I think should help:

 - remove-storage will fail if the storage isn't already detached. You can pass --force to cause remove-storage to detach the storage first, and then remove it from the model. The idea behind this is to protect users from accidentally removing storage when they really just wanted to detach it.
 - remove-storage now has a --no-destroy flag. When you use the remove-storage command, it will remove the storage from the model; by default it will also destroy the corresponding cloud storage. If you pass the --no-destroy flag, then the cloud storage will be disassociated from the model/controller, and not destroyed.
