### ISSUE TITLE
Clarify how to start Juju with desired mongo profile

### ISSUE THREAD

**Issue by anastasiamac** [juju/docs#1722]
As per https://bugs.launchpad.net/juju/+bug/1673314, users can choose what memory profile bootstrapped mongo will use.

**Comment by evilnick** [comment]
do we have any idea which version of Juju introduced this?

**Comment by anastasiamac** [comment]
It is a new config available in 2.2 :D

**Comment by matthewhelmke** [comment]
Removing the 2.1 label as this was added in 2.2.
