### ISSUE TITLE
Transfer juju doc to doc.ubuntu.com github repository

### ISSUE THREAD

**Issue by ArKam** [juju/docs#1731]
Hi guys,

Wouldn't be nice for juju to be part of the docs.ubuntu.com new docs portal?
I mean, as a user or potential developer/contributo, I'm looking for a central and unified documentation.

Juju docs format is already using the md file format and the visual guidelines, could you get in touch with webteam.at.canonical.com and so make them add Juju to the already existing list?

**Comment by evilnick** [comment]
Hi @ArKam !

Thanks for your interest in the Juju docs. In fact, all the docs built at docs.ubuntu.com, and the tools used to build them are based on the work we did here in the Juju docs first. Along the way we made some changes (improvements I hope) to make delivering documentation more efficient and easier for contributors, reviewers and the site maintainers.
At the moment, that means these docs are built with what you could imagine as being the alpha version of those processes. We do intend to migrate these docs to the new tooling in the near future, but it is a big job - the Juju docs are bigger than all the projects on docs.ubuntu.com combined!
I hope you will find that as a contributor though, there is not too much difference to working on Juju docs compared to MAAS, snappy, etc.

**Comment by ArKam** [comment]
Hi @evilnick Oh, I'm really glad to see that! Yes I saw that Juju docs where on the same shape as the other docs and I really thank you for this answer.
On a side note, would it be ok to contact webteam to at least ask them to add a link to the Juju doc as they made it with snapcraft?
It would be easier to me to point to that documentation during my demos session at work.

**Comment by anthonydillon** [comment]
@pmatulis yea sure. The template is here: https://github.com/canonical-websites/docs.ubuntu.com/blob/master/templates/index.html. feel free to create a PR or file a issue and we'll get on it.

**Comment by pmatulis** [comment]
@anthonydillon Ok, here you go: https://github.com/canonical-websites/docs.ubuntu.com/pull/135

**Comment by pmatulis** [comment]
This is now closed due to the above PR.
