### ISSUE TITLE
juju layer-vanilla repository is missing or the doc is incorrect.

### ISSUE THREAD

**Issue by ArKam** [juju/docs#1738]
Hi guys, digging on the juju doc and how to write a charm, I found out that this part of the documentation is not correct:

https://jujucharms.com/docs/stable/developer-getting-started#writing-your-charm

It state that we need to clone the following repository on github but this one is no longer available.
[layer-vanilla.git](git clone http://github.com/juju-solutions/layer-vanilla.git)

I tried to find it on this juju repository but can't find anything related except an empty repository.
Do I missed something?
Could you provide me the correct URL?

I could do the documentation fix if you provide me the correct informations by the way.

**Comment by tvansteenburgh** [comment]
That is the correct repo - link works for me.

**Comment by ArKam** [comment]
Yep, indeed!
Nevermind, that is an issue with my ISP using bad proxy caching methods...
