### ISSUE TITLE
Missing information on how to provide vpc-id value for aws models

### ISSUE THREAD

**Issue by hatched** [juju/docs#1745]
When creating a new model on JAAS you may want to to provide a `vpc-id` via the CLI if you want it to be on a specific VPC. This is done with `juju add-model --config vpc-id=<id>` but this doesn't config option appear to be documented anywhere, in the docs, nor in the CLI help output.

**Comment by matthewhelmke** [comment]
While considering how/where/if to put this in the documentation, I definitely think as a first step this is a config option that belongs in the help for add-model.

**Comment by matthewhelmke** [comment]
Probably useful in here: https://jujucharms.com/docs/stable/help-aws

**Comment by evilnick** [comment]
It probably deserves mentioning on the AWS page, but it belongs on the model config table.

I wonder how out of date the table is?

**Comment by matthewhelmke** [comment]
@evilnick I agree with the wonder about the model config table. I'm going to create a new issue for it that parallels #1783, which documents the same update and filling-in-gap needs for controllers.
