### ISSUE TITLE
Detail the recommendation/promulgation process

### ISSUE THREAD

**Issue by arosales** [juju/docs#1746]
With the new charm push model we need to do a better job of describing how to get a charm into a recommended name-space

Suggest to link or follow-on at:
https://jujucharms.com/docs/stable/authors-charm-store

-thanks,
Antonio

**Comment by pmatulis** [comment]
The specific issue of how to promulgate a charm is being handled via #2145 (developer-getting-started.md edited). There is also a long term issue (#2160) to merge the authors-* and developer-* docs that were imported into the repository prematurely. Closing.
