### ISSUE TITLE
Deadlinks

### ISSUE THREAD

**Issue by wallyworld** [juju/docs#1752]
As reported in https://github.com/juju/juju/issues/7154

The first link in the readme is a deadlink. ( http://jujucharms.com/charms )

Also "How it works" ( https://jujucharms.com/how-it-works ) -> "Learn more about writing charms ›" deadlinks.

**Comment by matthewhelmke** [comment]
Thanks. The original issue reported was not with our [readme.md](https://github.com/juju/docs/blob/master/README.md) but with the one in [juju/juju](https://github.com/juju/juju/blob/staging/README.md).

Closing this and commenting on juju/juju#7154.
