### ISSUE TITLE
juju scp still references -e and enivornment

### ISSUE THREAD

**Issue by mitechie** [juju/docs#1754]
juju scp -e testing foo.txt apache2/1:

In a grep through the docs it looks like there's also one for charm tools

    grep "\-e " src/en/**/*
    src/en/tools-charm-tools.md:                       [-p PRESERVE_ENVIRONMENT_VARIABLES] [-e JUJU_ENV]

That I'm not sure about. The rest of the references seems to be on the juju1 release notes page and using -e for shell scripting which are ok.

**Comment by evilnick** [comment]
Thanks for spotting that, will fix.

I think charm tools itself is out of date rather than the docs - currently this option is still listed (maybe backwards compatibility?)
