### ISSUE TITLE
https://jujucharms.com/docs/1.25/wip-users suggests using a command that doesn't exist

### ISSUE THREAD

**Issue by frankban** [juju/docs#1774]
Moved from https://github.com/CanonicalLtd/jujucharms.com/issues/432

Juju 1.25.6, attempting to run password changes, the instructions state to use "juju system" but this returns with "ERROR unrecognized command: juju system".

The same page also doesn't specify what should 'bob' should do with the .server file when it's been sent after creating the new user.

**Comment by matthewhelmke** [comment]
The page referenced was a work in progress leading up to the 2.0 release. As far as we know, none of its content applies to 1.25 and it is not linked to from anywhere within the 1.5 documentation. I am removing the page so that it does not appear in search results.

**Comment by matthewhelmke** [comment]
Closed in #1791
