### ISSUE TITLE
feedback on jaas getting-started page

### ISSUE THREAD

**Issue by mitechie** [juju/docs#1777]
- [ ] Running openstack in azure isn't all that useful. Can we find a second example that's more common real use case? 

- [x] The images for create a model are above the heading and the caption then replicates the first line of the section under create a model. The screenshots don't seem to be tied with the section and then it's confusing with the two sentences of almost the same content so close. 
![green button](https://cloud.githubusercontent.com/assets/75915/24519191/628bf5e4-1552-11e7-8654-581124985f63.jpg)

- [ ] Wording suggestion
    You will be shown a list of available charms and bundles with a description of each. Select a charm or bundle to learn more about it.

    "Build your model by selecting software from the Charm Store. View the details about any Charm or Bundle to learn more about it. Add it to your current model by pressing the "Add to model" button."

- [ ]  wording suggestion

    you will see where to enter your cloud credentials.

    you'll be guided through adding your cloud credentials.

My general feedback is that telling me what I see what to do seems like something that might be an interesting principle to follow. I'd much rather read what stuff is and more action orientated than telling me what I see. I guess I feel there's a bit of "don't read the slides" as I go through this. 

- [x] The two tables of picking a cloud is too close together and makes things busy. Either rely on the screenshot to demonstrate the clouds or rely on the text in the body, but both is too much. Maybe instead of the visual buttons we just put the links at the end of the sentence. 

![pick-clouds-dupe](https://cloud.githubusercontent.com/assets/75915/24519413/0eb63492-1553-11e7-8c05-3a190f1bc38b.jpg)

- [x] We briefly cover retrieving and entering your GCE credentials below.

I strongly feel like we shouldn't walk through this again here. It only applies to one set of users, it's covered elsewhere and needs to be kept in sync, and the webui is going to guide them through the bits they need. We've told them they'd need their cloud credentials.

- [ ] Back in JAAS, enter a name for this new project, we'd recommend using the same name as the project in GCE,

There's no such thing as a 'project' in jaas. This needs to be "model" and I'd not conflate the model in JAAS with a project because they are not 1-1. 

- [x] I don't think we need the collaborate here on this page. This is meant to be short/slim and we've pushed the CLI work off and this is not worth the real estate at the moment. This should just be under the sharing models in the general juju docs as the GUI does the same thing. The one difference is how you reference a user name. 

- [x] Destroy a model I don't think needs to be here at the moment. We have docs for this and the double screenshots for this is a chunk of space that's not JAAS specific. 

- [x] My biggest issue is that we don't have the CLI bit on here. I see the CLI next page and it's lovely but has a lot of added fluff that repeats how to do things the same way you do with Juju. We need that register line in here so that users can access their JAAS models from the CLI when they end this "getting started". They're not started w/o the CLI.

**Comment by evilnick** [comment]
I think we have covered most of this in various ways (take a look!). The exception is item 1, the example. If you have a better example we'd be happy to add it.

**Comment by mitechie** [comment]
For 1:

     You can deploy Kubernetes to GCE in 10 minutes or setup Hadoop with Spark to AWS with two clicks, all from your web browser.

Basically I think the hadoop with spark bundle is a better one to go off of, but I'm nervous that because it's all Java it'll not have an impressive deploy time.

**Comment by evilnick** [comment]
I think we're going to count this as done for now :)
