### ISSUE TITLE
'debug-hooks' supports both hooks and actions

### ISSUE THREAD

**Issue by anastasiamac** [juju/docs#1788]
According to https://bugs.launchpad.net/juju/+bug/1676399, 'debug-hook' command supports both hooks and actions but it is not obvious to the end-user.

Whilst we need to make it clearer on juju side, please clarify on your end as well \o/

**Comment by evilnick** [comment]
Thanks. It wasn't obvious to us either. Debug-hooks has been around since the dawn of juju go as have the docs for it, so I guess it was added at or after 'actions' were added to Juju.
