### ISSUE TITLE
Do not include browser chrome with images

### ISSUE THREAD

**Issue by hatched** [juju/docs#1803]
It would be nice if there was a convention to not include the browser chrome with the images of the GUI (https://jujucharms.com/docs/devel/getting-started-jaas). It doesn't add anything to the information available to the user and isn't very attractive.

**Comment by evilnick** [comment]
Hi, thanks for reporting this.

There is a style for this type of image which does include the browser for various reasons. One of which is that the GUI images alone are rather confusing without a context and don't work well with the styles for documentation. But we will take another when we next review the docs styles

![image](https://cloud.githubusercontent.com/assets/115290/25179350/6df125f8-2501-11e7-808d-4fc7acdd5940.png)
