### ISSUE TITLE
About Juju image 'about-charms' is not consistent with new GUI 

### ISSUE THREAD

**Issue by hatched** [juju/docs#1811]
About 1/2 way down this page: https://jujucharms.com/docs/stable/about-juju

**Comment by evilnick** [comment]
would you care to be more specific?

**Comment by hatched** [comment]
This image: https://jujucharms.com/static/img/jujudocs/about-charms.png

**Comment by evilnick** [comment]
Ah, okay, cool. You do know that is just a diagram and not necessarily supposed to represent the gui?
I will see when we can get some design time to redraw it
