### ISSUE TITLE
Do getting-started instructions need "apt update"?

### ISSUE THREAD

**Issue by nottrobin** [juju/docs#1812]
[The getting started page](https://jujucharms.com/docs/stable/getting-started) says:

> Begin by installing the required software:
>
> ``` bash
> sudo add-apt-repository -u ppa:juju/stable
> sudo apt install juju lxd zfsutils-linux
> ```

I wouldn't expect this to work without running `sudo apt update` in between.

**Comment by degville** [comment]
Thanks Robin. It's easy to miss, but that's what the `-u` is for.

**Comment by nottrobin** [comment]
@degville do you think we could use the expanded `--update` to make this clearer? I always go for expanded options in documentation.

**Comment by degville** [comment]
@nottrobin Yes. I think you're right - I'll change it. Thanks!
