### ISSUE TITLE
charm snap needs classic confinement

### ISSUE THREAD

**Issue by nottrobin** [juju/docs#1813]
[The charm tools documentation](https://jujucharms.com/docs/stable/tools-charm-tools) suggests you install it with `sudo snap install charm`, but when I run it I get:

``` bash
$ sudo snap install charm
error: snap "charm" requires classic or confinement override
```

I assume it should be `sudo snap install --classic charm`.

**Comment by evilnick** [comment]
Sorry. This was fixed in master a while back, but wasn't backported for some reason
