### ISSUE TITLE
"Your first charm" and "charm tools" docs don't match

### ISSUE THREAD

**Issue by nottrobin** [juju/docs#1814]
I first installed `juju` from the PPA as per the [getting started page](https://jujucharms.com/docs/stable/getting-started).

Then ["Your first charm starts here" page](https://jujucharms.com/docs/stable/authors-charm-writing) says:

> Although it is possible to create a charm without using anything other than a text editor, we are also going to make use of the very excellent time saving plugin for Juju, Charm Tools. [Find out how to get and install charm tools here](https://jujucharms.com/docs/stable/authors-charm-writing). Then hurry back.

Then:

> Using the charm tools plugin, we can create the directory structure we need for our charm quickly and easily:
> ``` bash
> juju charm create vanilla
> ```

(I had a side issue that I didn't notice the instruction to install charm tools initially, expecting `juju charm create vanilla` to just work, as I had `juju`. I do think this is a problem. Many people will jump right to the first command they see.)

But the [charm-tools documentation](https://jujucharms.com/docs/stable/tools-charm-tools) says:

> Install the charm snap:
> 
> ``` bash
> sudo snap install charm
> ```

When I install the charm snap, I get a `charm` command (which is [also broken](https://github.com/juju/charm-tools/issues/319)), but (of course) the snap has not influenced the installed `juju` command, so `juju charm create` still doesn't exist.

I assume I should instead be installing `charm-tools` with `apt`, similar to how I installed `juju` itself?

**Comment by nottrobin** [comment]
So I have now installed `charm-tools` from the `juju/stable` PPA:

``` bash
$ sudo apt policy charm-tools
charm-tools:
  Installed: 2.2.0-0ubuntu1~ubuntu16.10.1~ppa2
  Candidate: 2.2.0-0ubuntu1~ubuntu16.10.1~ppa2
  Version table:
 *** 2.2.0-0ubuntu1~ubuntu16.10.1~ppa2 500
        500 http://ppa.launchpad.net/juju/stable/ubuntu yakkety/main amd64 Packages
...
$ sudo apt install charm-tools 
Reading package lists... Done
...
Setting up charm-tools (2.2.0-0ubuntu1~ubuntu16.10.1~ppa2) ...
```

Now `charm create {name}` works fine, but I still don't have `juju charm create`, as the documentation suggests I should:

``` bash
$ juju charm create vanilla
error: unrecognized command: charm create
```

**Comment by evilnick** [comment]
The charm-tool install story is a bit of a mess. AIUI, only the snap is now supported, but there are issues there with installing plugins.

see also #1256 #1649  & https://github.com/juju/charm-tools/issues/303
