### ISSUE TITLE
Replace ppa install instructions with snap

### ISSUE THREAD

**Issue by evandandrea** [juju/docs#1833]
https://jujucharms.com/docs/stable/getting-started suggests installing juju via a PPA. Can we replace that (and the LXD initialisation) with the juju and lxd snaps?

**Comment by mitechie** [comment]
This is in progress in #1826

**Comment by nskaggs** [comment]
Don't forget https://jujucharms.com/docs/stable/getting-started-general and https://jujucharms.com/docs/stable/reference-releases which is somewhat updated, but not completely.

**Comment by evilnick** [comment]
fixed, by various recent PRs
