### ISSUE TITLE
subordinate charm units can be removed using remove-relation

### ISSUE THREAD

**Issue by javacruft** [juju/docs#1856]
The docs for subordinate charms contain a caveat:

> Caveats
>
> The current model of subordinates doesn't include support for removing subordinate units from their > principal service apart from removing the principal service itself. This limitation stems from the current policy around service shutdown and the invocation of stop hooks.

which is not applicable - I tested on a 2.1.x install and was able to remove subordinate units from the principle service by removing the relation between them.

**Comment by evilnick** [comment]
Cool. Thanks for the update, we will get this removed

**Comment by evilnick** [comment]
fixed by #1857
