### ISSUE TITLE
Bundle docs missing `description` key in bundle.yaml

### ISSUE THREAD

**Issue by hatched** [juju/docs#1863]
https://jujucharms.com/docs/2.1/charms-bundles

**Comment by degville** [comment]
Thanks for filing this. Could you add or link further detail on the missing key? I can't find an example of where `description` is used within a bundle, unless I've misunderstood the issue. Thanks.

**Comment by hatched** [comment]
@mitechie are you able to find some information on this?

**Comment by mitechie** [comment]
The idea is that users can add an additional field of information in their bundles called description. Users haven't been doing it so far but we want to suggest and push folks towards it. 

https://github.com/juju/charm/blob/v5/bundledata.go#L50

There's a corresponding bug in the GUI that it's not showing the data as well:

https://github.com/juju/juju-gui/issues/2931

**Comment by degville** [comment]
Perfect, thanks. I'll add the info.
