### ISSUE TITLE
subordinate remove-relation needs a caveat

### ISSUE THREAD

**Issue by kwmonroe** [juju/docs#1865]
In #1856, @javacruft noted that subs can be removed with `remove-relation`.  There seems to be a corner case where this is not true.  If a subordinate is related to 2 or more different applications, removing a principal-sub relation does not remove the sub:

https://bugs.launchpad.net/juju/+bug/1692675

I think the caveat removed in #1857 should come back, perhaps re-worded like this:

> Caveats
>
> When a subordinate is related to a single principal application, the subordinate may be removed by removing the principal-subordinate relation.  When related to multiple principal applications, the subordinate may only be removed by removing the principal unit.

**Comment by evilnick** [comment]
\o/

**Comment by howbazaar** [comment]
Actually, this has been fixed in 2.2 by Christian.

**Comment by evilnick** [comment]
😿

**Comment by kwmonroe** [comment]
Lol, sorry about that @evilnick.  It wasn't fixed in 2.2-beta4, i promise!  Perhaps:

> Caveat
>
> Damned if you do, damned if you don't.
