### ISSUE TITLE
run-action can now run on multiple units

### ISSUE THREAD

**Issue by evilnick** [juju/docs#1866]
https://jujucharms.com/docs/2.1/actions should be updated to reflect the changes as detailed 
here https://github.com/juju/juju/pull/7244

**Comment by evilnick** [comment]
This doesn't seem to be implemented in 2.2rc1, or at least, not as described in the PR 
@stub42 ?

**Comment by stub42** [comment]
https://github.com/juju/juju/pull/7244 has not landed. You probably meant https://github.com/juju/juju/pull/7060 , which did land and added the --wait option.

**Comment by evilnick** [comment]
ok, thanks for the info. I will punt this to 2.3 then
