### ISSUE TITLE
Add openSUSE information

### ISSUE THREAD

**Issue by evilnick** [juju/docs#1886]
Juju now has limited support for openSUSE, as per https://github.com/juju/juju/pull/7257

As there are now special cases around CentOS, Windows and openSUSE charms, it would probably work best if these were rolled into a single page in the charms section.

See also #1854

**Comment by evilnick** [comment]
@marcmolla - any notes you have on openSUSE would be useful! :smile:

**Comment by marcmolla** [comment]
@evilnick I am on it, but I need some time :)

my plan is to send two PR to the docs: one for manual provisioning and another one for containers/general. 

I have my original notes here:
https://github.com/marcmolla/juju-OpenSUSE/blob/master/test-compiled-Juju.md
https://github.com/marcmolla/juju-OpenSUSE/blob/master/lxd-opensuse-42.2-image.md

but they should be updated (now jujud supports OpenSUSE but agent is not generated for it...)

**Comment by pmatulis** [comment]
@marcmolla Are you still working on this?

**Comment by marcmolla** [comment]
@pmatulis not all the time that it requires... I wrote the doc related to manual provisioning but it still pending to document the image requirements and how to use it with containers. No so much work but I am not focused on this now. 

I will try to send a PR with my current work asap and my plans are to return to Juju with new reqs, but are a little bit delayed.

**Comment by pmatulis** [comment]
@marcmolla Thanks for the update! :racehorse:

**Comment by pmatulis** [comment]
@marcmolla Hi, any news?
