### ISSUE TITLE
Need Windows & CentOS troubleshooting

### ISSUE THREAD

**Issue by evilnick** [juju/docs#189]
There has been a request for more information regarding Windows/Centos deployments. Specifically one issue raised was about driver failures during deploy. We should try and capture these problems and store solutions in the troubleshooting section.

**Comment by evilnick** [comment]
@marcmolla - any notes you have on openSUSE would be useful! :smile:

**Comment by AdamIsrael** [comment]
I think the title of this issue should be updated to include Centos.

**Comment by evilnick** [comment]
The best place for this would be on or linked from this page I think
https://jujucharms.com/docs/stable/troubleshooting

**Comment by AdamIsrael** [comment]
For Centos, this page needs review by someone familiar with using Juju and Centos: https://jujucharms.com/docs/stable/juju-centos

**Comment by pmatulis** [comment]
@evilnick Unless there is any contributed information ('driver failures during deploy'?) that we can document I propose we close this issue.

**Comment by evilnick** [comment]
ok, we can re-open when we have some contributed info
