### ISSUE TITLE
Add new commands to debug/troubleshooting docs

### ISSUE THREAD

**Issue by evilnick** [juju/docs#1893]
As per https://github.com/juju/juju/pull/7465

**Comment by pmatulis** [comment]
@evilnick I'm not sure how to use this information.

```
$ juju-cpu-profile 5
Sampling CPU for 5 seconds.
Querying @jujud-machine-0 introspection socket: /debug/pprof/profile?debug=1&seconds=5
"[xe/¥{V¿|>ølE¶§;?ý½gµYYd[yJ|1ø¿ø݇Wª]xº,²<¥ÿV³eeyZa;=«/җ?~y¸X^yZ,ÿùûQ¿ÿ·ewþû¨ÿu鍯nýõh3»£>|p[ɃM|
¸)ZH¤±¡Wh'¦C/¥¾:4O8lv¶÷S¬$!
"7IN0AiUXYm'@Gi=g½4J¨Á² ¤_©û럼´9Rz¥¤´cF@¢\Fg        ¾V¯nzxdfgY°Gϔ"F¤VS×YwV³*bG©ARh¸
                                                                                                      c6¨÷¯֫jՁϤs"舌n  /Á2M$J
U½*x4{÷f0þl¤
             D@¢*rʬe$0M=|©~r{ir¢"­gF<r#ld¸}w8ºvܽ§3GM
                                                  7w[»ভ
                                                       ÿÿ"K     
```

The above command was mentioned as the more important ones. Still, some of the other commands do show legible output but it's still not clear how this is supposed to help the user.

**Comment by pmatulis** [comment]
@axw Can you be more explicit of how https://github.com/juju/juju/pull/7465 is supposed to help our users?

**Comment by pmatulis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add new commands to debug/troubleshooting docs](https://trello.com/c/a7EkUm4k/5-add-new-commands-to-debug-troubleshooting-docs)
