### ISSUE TITLE
Update Juju/Centos instructions for using LXD

### ISSUE THREAD

**Issue by AdamIsrael** [juju/docs#1935]
It's possible to use LXD on Centos, with Juju, but we currently show that as unsupported. We should document that process and add it to the juju-centos page.

I have the instructions to do this and will submit a pull request next week.

**Comment by AdamIsrael** [comment]
This is in reference to #189 

I have a [gist](https://gist.github.com/AdamIsrael/e6b4a540233a7be6d28decd917b60c3d) which documents the process for getting lxd working on Centos with Juju. It'll need to be updated to pull the latest stable version of Juju. I'll work on reformatting this for the docs.

**Comment by pmatulis** [comment]
@AdamIsrael 
Hi, are you still working on this?

**Comment by pmatulis** [comment]
The instructions don't seem to work for people (as per gist comment of 6 days ago). I'm marking this as 'blocked'.

**Comment by pmatulis** [comment]
Unfortunately, working at the source code level does not belong in the official Juju docs. It's just too hard to maintain and be responsible for. I feel a blog is more appropriate. Closing this.
