### ISSUE TITLE
Search may change the juju version unexpectedly

### ISSUE THREAD

**Issue by AdamIsrael** [juju/docs#1936]
If I do a search for "policy" from the Getting started page of the stable juju release (https://jujucharms.com/docs/stable/getting-started), it takes me to the results for Juju 2.2 (https://jujucharms.com/docs/search/?text=policy&version=2.2).

This isn't wrong in that 2.2 is the stable release, but I think it may be confusing to the user. I would expect this to take me to the results for "stable", regardless of what the exact version number is, i.e., https://jujucharms.com/docs/search/?text=policy&version=stable, if that were a working link.

**Comment by evilnick** [comment]
Search is not implemented in the docs repo, it is part of the site functionality, so I am moving this issue here: https://github.com/CanonicalLtd/jujucharms.com/issues/467
