### ISSUE TITLE
Documentation for 2.2 describes a --networks option that doesn't exist

### ISSUE THREAD

**Issue by dave-lawson** [juju/docs#1937]
The documentation here:
https://jujucharms.com/docs/2.2/charms-deploying
Near the bottom of the page makes mention of a --networks option that can be used to bind to spaces.  That option to deploy doesn't appear to exist:

$ juju --version
2.2.0-xenial-amd64
$ juju deploy ./neutron-gateway --to lxd:1 --bind "management data=openstack" --networks management,openstack
ERROR flag provided but not defined: --networks

**Comment by jameinel** [comment]
I believe networks was a 1.X flag. It should be
--constraints "spaces=X,Y,Z"

John
=:->

**Comment by degville** [comment]
Thanks for letting us know. Spaces are covered earlier in the same document, so we'll remove the reference to the networks option.
