### ISSUE TITLE
Unable to find metadata.yaml documentation

### ISSUE THREAD

**Issue by stub42** [juju/docs#1950]
metadata.yaml is the core configuration file for a charm, which is why I'm surprised I can find no documentation for it in the reference section or the getting started section.

**Comment by pmatulis** [comment]
@stub42 What about [authors-charm-metadata](https://jujucharms.com/docs/devel/authors-charm-metadata)? Maybe it just requires adding to the navigation (menu)?

**Comment by stub42** [comment]
That looks about right, and I still can't find it linked from the navigation menu.

I also see some of that document duplicated elsewhere, such as https://jujucharms.com/docs/devel/developer-storage#adding-storage. Its odd having separate 'authors' and 'developer' sections, since from my POV they are the same role, but ironing out that kink is a larger issue.

**Comment by pmatulis** [comment]
Yes, the navigation needs to be adjusted. And, yes, a unholy merge of two distinct sets of dev pages occurred (not by the Docs team by the way).

I will close this issue once the navigation has been modified. Issue #2160 is tracking the much larger aspect of merging all dev pages.
