### ISSUE TITLE
Wrong link to godoc for logging-config on models-config

### ISSUE THREAD

**Issue by jaycee** [juju/docs#1951]
From @sparkiegeek, reporting on https://github.com/CanonicalLtd/jujucharms.com/issues/468:

> On [models-config page for 2.2](https://jujucharms.com/docs/2.2/models-config) for the `logging-config` row, the docs point to https://godoc.org/github.com/juju/loggo#ParseConfigurationString but the documentation is actually at https://godoc.org/github.com/juju/loggo#ParseConfigString

**Comment by degville** [comment]
Thanks for letting us know.
