### ISSUE TITLE
Docs don't list all possible action status codes

### ISSUE THREAD

**Issue by AdamIsrael** [juju/docs#1962]
I haven't found anywhere in the docs that list the various `action` statuses the user may want to watch for. According to [the code](https://github.com/juju/juju/blob/4982b4b9a825aa33c584aba740baae67a4a324aa/state/action.go#L33), they are:
- failed
- completed
- cancelled
- pending
- running

**Comment by degville** [comment]
Thanks for the info (and the link!) - we'll add these details to the actions document.
