### ISSUE TITLE
no note on how to enable a feature flag

### ISSUE THREAD

**Issue by mitechie** [juju/docs#1968]
per https://askubuntu.com/questions/766851/how-do-i-use-a-feature-flag

We should list this in the documentation and probably a list of currently running feature flags available for testing/use.

**Comment by pmatulis** [comment]
Where can I find the current list of feature flags?

**Comment by pmatulis** [comment]
As agreed internally, the Docs will not point to the experimental flags. Thus effectively invalidating this issue. Closing.

**Comment by pmatulis** [comment]
Note that JUJU_DEV_FEATURE_FLAGS is mentioned [here](https://jujucharms.com/docs/stable/reference-environment-variables).
