### ISSUE TITLE
/troubleshooting-tools page not found

### ISSUE THREAD

**Issue by arosales** [juju/docs#1969]
On the bottom of:
https://jujucharms.com/docs/stable/troubleshooting

there is a nice section for additional troubleshooting topics. One of those is a "Troubleshooting tools" link which goes to https://jujucharms.com/docs/stable/troubleshooting-tools/ however that page is not found.

**Comment by degville** [comment]
Thanks for letting us know. This page was actually fixed and updated in master but not backported to 2.2. We'll merge those changes back.

**Comment by degville** [comment]
fixed with #1970
