### ISSUE TITLE
Juju Doc Should Include a MAAS Compatibility Matrix

### ISSUE THREAD

**Issue by dsjpoulain** [juju/docs#1981]
The Juju 1.x doc should make it clear that Juju 1.x only works with MAAS 1.x, whereas the Juju 2 doc should state that Juju 2 can work with MAAS versions 1 and 2.

**Comment by evilnick** [comment]
It doesn't really need a matrix as such, just a note on the 1.25 docs that it doesn't work with MAAS 2.0

**Comment by dsjpoulain** [comment]
Thanks Nick. I'd still strongly recommend adding an explicit mention in the 2.x docs that Juju 2.x works with both versions of MAAS, as this would avoid any potential confusion from users, esp. those coming from Juju 1.25 - we've seen such confusion in the field on a number of occasions.

**Comment by evilnick** [comment]
OK, cool. Will add to both then !
