### ISSUE TITLE
error bootstraping local environment with juju-quickstart

### ISSUE THREAD

**Issue by thism55** [juju/docs#1982]
Hi all,

while trying to initiate the juju-quickstart, i get the following error,

_### juju-quickstart
usage: juju-quickstart [-h] [-e ENV_NAME] [-n BUNDLE_NAME] [-i] [-u]
                       [--gui-charm-url CHARM_URL] [--gui-port PORT]
                       [--no-browser] [--environments-file ENV_FILE]
                       [--distro-only] [--ppa] [--version] [--debug]
                       [--description] [--upload-tools]
                       [--upload-series UPLOAD_SERIES]
                       [--constraints CONSTRAINTS]
                       [BUNDLE]
juju-quickstart: error: environment lxd-test:admin/default not found_

and by specifying the name of the environment I get this unexpected printout:

_juju-quickstart -e local
juju quickstart v2.2.4
ssh-agent has been started.
To interact with Juju or quickstart again after quickstart finishes, please run the following in a terminal to start ssh-agent:
  eval `ssh-agent`

bootstrapping the local environment
sudo privileges will be required to bootstrap the environment
juju-quickstart: error: ERROR flag provided but not defined: -e

Any suggestions please?

Regards

**Comment by mitechie** [comment]
juju-quickstart is deprecated and only functions with Juju 1.25. I believe that you're hitting this issue. What led you to leverage juju-quickstart and maybe the getting-started docs can be of assistance. 

https://jujucharms.com/docs/stable/tut-lxd
