### ISSUE TITLE
Erroneous Link to MAAS's Documentation on Zones

### ISSUE THREAD

**Issue by dsjpoulain** [juju/docs#1983]
At <https://jujucharms.com/docs/2.2/charms-ha#availability-zones> the doc refers the reader to <http://maas.io/docs/installconfig-zones> for doc on MAAS zones, but that URL eventually leads to a 404:

```
curl -IL http://maas.io/docs/installconfig-zones
HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: https://maas.io/docs/installconfig-zones
Connection: close

HTTP/1.1 302 Found
Server: gunicorn/17.5
Date: Thu, 20 Jul 2017 09:00:36 GMT
Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8
Location: http://docs.ubuntu.com/maas/2.2/installconfig-zones
X-Robots-Tag: all

HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: https://docs.ubuntu.com/maas/2.2/installconfig-zones
Connection: close

HTTP/1.1 404 Not Found
Server: gunicorn/17.5
Date: Thu, 20 Jul 2017 09:00:37 GMT
Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8
X-Robots-Tag: all

```

Instead you can use e.g. <https://docs.ubuntu.com/maas/2.2/en/manage-zones> for MAAS 2.2 and <https://docs.ubuntu.com/maas/1.9/en/physical-zones> for 1.9 (there doesn't appear to be a version-agnostic landing page you could use instead to further dispatch the reader to 1.9 or 2.2 depending on their interests).

**Comment by degville** [comment]
Thanks for flagging this, we'll update the docs.
