### ISSUE TITLE
Charm Tools Windows installer is outdated

### ISSUE THREAD

**Issue by stub42** [juju/docs#1984]
https://jujucharms.com/docs/stable/tools-charm-tools points Windows users to a 1.2 release from 2014

**Comment by evilnick** [comment]
yes, this is problematic - there is no recent build for Windows on Launchpad as the project is now on github. There appears to be no Windows build there either and the information on the repository is also out of date.

**Comment by pmatulis** [comment]
A more general issue (involving macos too) was raised recently and is being tracked. I'm closing this one in favour of it. See #2103.
