### ISSUE TITLE
Azure help is outdated

### ISSUE THREAD

**Issue by nskaggs** [juju/docs#2000]
I went through setting up azure on juju yesterday, including having to manually add credentials for ci usage. The current directions reference to install an edge snap, which results in an out of date version of azure cli tools being installed. The instructions still seem to work for the intents of getting your information to feed into juju via autoload credentials (though az login seems broken), however the manual setup is incorrect. Due to the use of the older cli, it fails in non-intuitive ways, and juju and azure won't work well.

Let's update this page to reflect an updated and working method. I referenced the following upstream information to get things to work. https://docs.microsoft.com/en-us/azure/xplat-cli-connect and https://docs.microsoft.com/en-us/azure/cli-install-nodejs for information on obtaining the newer cli.

**Comment by nskaggs** [comment]
The following is the minified steps I took to get things working via the cli. After this, autoload credentials just worked for bootstrap by me or via automated testing in a new environment.

```
sudo npm install -g azure-cli
$ azure login
info:    Executing command login
/info:    To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code XXXXXXXX to authenticate.
\info:    Added subscription XXXXXXXXX
+
info:    login command OK
$ azure account show
info:    Executing command account show
data:    Name                        : XXXXXXXXX
data:    ID                          : xxxxxxxxxxxxxxxxxxxxxxxxxxxx
data:    State                       : Enabled
data:    Tenant ID                   : xxxxxxxxxxxxxxxxxxxxxxxxxx
data:    Is Default                  : true
data:    Environment                 : AzureCloud
data:    Has Certificate             : No
data:    Has Access Token            : Yes
data:    User name                   : xxxxxxxxxxxxxxxxxxx
data:    
info:    account show command OK
$ azure ad sp create -n juju -p xxxxxxxxxxx
info:    Executing command ad sp create
+ Creating application qatesting                                               
+ Creating service principal for application xxxxxxxxxxxxxxxxxxxxxxxx
data:    Object Id:               aaaaaaaaaaaaaaaaaaaaa
data:    Display Name:            juju
data:    Service Principal Names:
data:                             xxxxxxxxxxxxxxxxxxxxx
data:                             http://juju
info:    ad sp create command OK
$ azure role assignment create --objectId aaaaaaaaaaaaaaaaaaaaa -o Owner
info:    Executing command role assignment create
+ Finding role with specified name                                             
\data:    RoleAssignmentId     : /subscriptions/xxxxxxxxxxxx/providers/Microsoft.Authorization/roleAssignments/xxxxxxxxxxxxxxxxxxxx
data:    RoleDefinitionName   : Owner
data:    RoleDefinitionId     : xxxxxxxxxxxxxxx
data:    Scope                : /subscriptions/xxxxxxxxxxxxxxxxxx
data:    Display Name         : juju
data:    SignInName           : undefined
data:    ObjectId             : xxxxxxxxxxxxxxxx
data:    ObjectType           : ServicePrincipal
data:    
+
info:    role assignment create command OK

```

**Comment by evilnick** [comment]
Thanks for the report - keeping the Azure/Oracle/Google pages up to date is important, its just a shame they keep changing them all the time. This is really useful info though, will work it into docs ASAP
