### ISSUE TITLE
Publish/Mirror Juju API docs at jujucharms.com

### ISSUE THREAD

**Issue by dustinkirkland** [juju/docs#201]
A customer asked recently for a link to the Juju API documentation.  I searched Google for "juju api" and got no relevant hits on the first 2 pages.  When I asked in #juju, I did get an answer:

http://godoc.org/github.com/juju/juju/api

So that's autogenerated documentation, which is more or less what we were looking for, but quite hard to find.

This bug is requesting that we host/mirror that documentation on one of the official Juju sites (juju.ubuntu.com or jujucharms.com), wherever is more appropriate, and setup appropriate Google indexing of such documentation.

**Comment by evilnick** [comment]
Just circling back to this, a while ago I added a link from the docs https://jujucharms.com/docs/stable/commands (in the reference section). 
I know that's not the complete answer @dustinkirkland , but hopefully they are at least slightly easier to find!

@mitechie I'm not sure that anyone has actually done any work on this for jujucharms? Perhaps this should be a sprint topic

**Comment by dustinkirkland** [comment]
Nice.


:-Dustin

**Comment by mitechie** [comment]
Oops, Dustin's reply reminded me that I had not replied. There is a sprint
session scheduled to work with the core team,  documentation team, and our
team to get good readable API documentation up on the website.

Rick

**Comment by AdamIsrael** [comment]
The jujucharms label doesn't apply here.

This is more of a backend issue that needs to be solved, possibly in the build engine of the docs.

**Comment by pmatulis** [comment]
@mitechie What did you come up with? :sob:

**Comment by pmatulis** [comment]
We've gone over this recently and it remains an esthetics issue. It's a nice-to-have but unfortunately it's quite low on our list of priorities.
