### ISSUE TITLE
Local firewall rule needed for lxd juju controller

### ISSUE THREAD

**Issue by xavpaice** [juju/docs#2011]
In https://jujucharms.com/docs/stable/tut-lxd we have excellent instructions for setting up a local controller via lxd - in order to make this work when we have a firewall enabled (e.g. ufw) we need to add an inbound allow rule for tcp/8443 from the lxd network.  This page could do with a note to that effect so that we don't trip over it.

**Comment by pmatulis** [comment]
Thanks. We'll look into it.

**Comment by pmatulis** [comment]
This is done. Closing.
