### ISSUE TITLE
application-version-set isn't documented in the juju docs 

### ISSUE THREAD

**Issue by mitechie** [juju/docs#2057]
https://github.com/juju/juju/blob/01b24551ecdf20921cf620b844ef6c2948fcc9f8/worker/uniter/runner/jujuc/application-version-set_test.go#L61

In checking out bug https://github.com/juju/charmstore/issues/774 it seems this might be useful for their purposes but there's no docs available for it currently.

**Comment by evilnick** [comment]
Well, it *is* in the docs:
https://jujucharms.com/docs/2.2/reference-hook-tools#application-version-set

But I don't know if this brief description would be adequate for their usage

**Comment by mitechie** [comment]
Sorry, my search-fu failed me after I found it in the code. 

https://jujucharms.com/docs/search/?text=application-version-set&version=2.2

Thanks for pointing it out to me.  /me goes to file bug on jujucharms.com search.

**Comment by evilnick** [comment]
Ok! open a new issue if there is something which should be added to that.
