### ISSUE TITLE
Install commands should reference signed windows exe

### ISSUE THREAD

**Issue by nskaggs** [juju/docs#2121]
We make a signed windows installer that we should probably point people to instead of the unsigned exe on

https://jujucharms.com/docs/stable/reference-install

The url difference is small, https://launchpad.net/juju/2.2/2.2.4/+download/juju-setup-2.2.4-signed.exe instead of https://launchpad.net/juju/2.2/2.2.4/+download/juju-setup-2.2.4.exe.

Actually curious if there is a reason to have an unsigned exe published on the milestone, or why we differentiate. We could drop the unsigned exe and push the signed one to https://launchpad.net/juju/2.2/2.2.4/+download/juju-setup-2.2.4.exe instead. That would mean the docs wouldn't have to change.

**Comment by evilnick** [comment]
AFAIK, historically this was because it takes time to get the .exe file signed, so the signed version wasn't available. IMHO I think it is probably better to wait until we have all the bits for a release before we announce it on lists, it saves disappointment and issues like this (however, i will update the link)

**Comment by pmatulis** [comment]
@nskaggs Can your team endeavour to have the signed 2.3 exe ready for release time?

**Comment by nskaggs** [comment]
If we simply only published the signed exe, nothing would have to change except the release process for juju. I'm not sure if there is a reason to have an unsigned exe, which I suppose is my only remaining question. We may be able to change things for 2.3-beta1 if we can came to a conclusion, but maybe not.

**Comment by pmatulis** [comment]
I don't see a need for an unsigned exe. Let's go signed-only. We just need to have the signed one ready for each Juju release. I'm probably missing something.
