### ISSUE TITLE
juju logging needs its own topic page

### ISSUE THREAD

**Issue by chuckbutler** [juju/docs#217]
We have a ton of logging information under troubleshooting. While that's great - logging is a topic all unto itself and should reside on its own topic page in the user docs with proper topic headings.

The developer logging can be summed up by explaining the different logging levels and `juju log`, which I believe is already in the author docs.

**Comment by petermatulis** [comment]
I'm intending on creating a new page (under Troubleshooting in TOC):

troubleshooting-debug-log.md

And transferring stuff from:

* [troubleshooting-debug-log.md](https://jujucharms.com/docs/stable/troubleshooting.html) (include link to new page)
* [authors-hook-debug.md](https://jujucharms.com/docs/stable/authors-hook-debug.html) (include link to new page)

In the sense of 'juju-log' being "developer logging" I don't find much info available, certainly no logging levels:

* [authors-charm-writing.md](https://jujucharms.com/docs/stable/authors-charm-writing.html)
* [authors-hook-environment.md](https://jujucharms.com/docs/stable/authors-hook-environment.html)

Do you mean logging levels for debug-log given on [commands.md](https://jujucharms.com/docs/stable/commands.html)?

**Comment by petermatulis** [comment]
@evilnick
Comments?

**Comment by evilnick** [comment]
wrt the logging levels, I believe chuck is saying we should have some charm author docs on writing the logs and using appropriate levels (?). This uses the juju-log hook tool (https://jujucharms.com/docs/stable/authors-hook-environment#hook-tools)
I'm not sure if the current usage info set there is complete (it only mentions two levels) because of course, if it changed nobody bothered to tell me about it.

**Comment by petermatulis** [comment]
I've consolidated the debug-log stuff. As for juju-log, I'm not sure what else can be done. A charm can send a message to the log (default level: INFO) but can set it as level: DEBUG using --debug.

**Comment by howbazaar** [comment]
On 24/07/15 08:23, Peter Matulis wrote:
> I've consolidated the debug-log stuff. As for juju-log, I'm not sure
> what else can be done. A charm can send a message to the log (default
> level: INFO) but can set it as level: DEBUG using --debug.

the charm log command can specify the log level explicitly using

 -l or --log-level

These values are case insensitive and are: trace, debug, info, warning,
error.

Also look at 'juju help logging'

Tim

**Comment by petermatulis** [comment]
'juju help logging' mentions a CRITICAL level as well which is not available to 'juju debug-log', which is strange.

Where can I get more information on 'juju-log'? We'll probably need a separate page for it. I can only find an old version on [manpages.ubuntu.com](http://manpages.ubuntu.com/manpages/quantal/man1/juju-log.1.html).

**Comment by petermatulis** [comment]
PR #570 covers most of this. I created issue #573 for juju-log specifically. Closing.
