### ISSUE TITLE
juju run documentation has no mention of different user in different contexts

### ISSUE THREAD

**Issue by chuckbutler** [juju/docs#219]
`juju run` executes as different users in different contexts.
You can validate this assertion by running `whoami` in the context.

- --service
- --unit
- --all
- --machine

**Comment by marcoceppi** [comment]
Just for documentation sake

`--service` and `--unit` run as root and in a hook context
`--machine` runs as ubuntu user with passwordless sudo acccess

**Comment by pmatulis** [comment]
Closed due to #1113
