### ISSUE TITLE
cinder storage provider now has a "volume-type" config attribute

### ISSUE THREAD

**Issue by axw** [juju/docs#2249]
The cinder storage provider docs [0] need a small update. The docs currently state, "The Cinder provider does not currently have any specific configuration options."  This will no longer be true in Juju 2.3; the provider now supports a single config attribute, "volume-type". The value can be the name of any of the volume types registered with Cinder.

[0] https://jujucharms.com/docs/devel/charms-storage#openstack/cinder-(cinder)

**Comment by evilnick** [comment]
Thanks for the heads up!
