### ISSUE TITLE
Docs Needed: MAAS Storage Example

### ISSUE THREAD

**Issue by jamesbeedy** [juju/docs#2251]
[this](https://jujucharms.com/docs/devel/charms-storage#maas-(maas)) is a bit sparse, and I can't quite see how I would use juju storage with the MAAS provider from the docs. Can we get an example here please? thx

**Comment by pmatulis** [comment]
Thanks for the suggestion! :+1:

**Comment by pmatulis** [comment]
I need information from the Juju team on tagging disks.
