### ISSUE TITLE
Integer relation ids instead of relname:42 format

### ISSUE THREAD

**Issue by stub42** [juju/docs#2283]
Per https://bugs.launchpad.net/juju/+bug/1728553

https://github.com/juju/docs/blob/e9446845ded4e97d0bfc9b521d4c8ccd07c5143a/src/en/developer-network-primitives.md has 'juju offers' reporting integer relation ids. The remaining examples also deal with relation '2' rather than with relation 'db:2' in numerous relation-get examples, and relation '0' instead of... something:0

**Comment by pmatulis** [comment]
Fixed via #2282
