### ISSUE TITLE
How to address duplication between charms.reactive and Juju docs

### ISSUE THREAD

**Issue by galgalesh** [juju/docs#2301]
There is a bunch of duplication between the Juju and the `charms.reactive` docs. Now that `charms.reactive` is the recommended way to build charms, we need to address this issue.

The first thing we need to do is define what kind of docs should go where. Our inclination would be for the the reactive docs to be the (auto-generated) API docs plus some narrative docs that dive into specific advanced features and the inner workings of `charms.reactive`. Do you agree with this? If so, I'll create a PR to remove the duplicated content.

*PS: A big part of the `charms.reactive` docs are automatically generated from the module's source code and `charms.reactive` is versioned separately from Juju core. Merging all `charms.reactive` docs into Juju docs is thus not recommended.*

**Comment by evilnick** [comment]
Yes, this seems reasonable. So API docs and some reasonable detail/examples live in the reactive docs, whilst structured text for actually building charms using the framework are in the main docs.

At some point we will likely split the charm writing docs from the Juju user docs, but I don't think this will have an impact.

**Comment by galgalesh** [comment]
Great, thanks!
