### ISSUE TITLE
how to wipe / reinstall juju once everything goes south

### ISSUE THREAD

**Issue by john-cplanenetworks** [juju/docs#2328]
Q:  is there anyway to completly wipe a juju controller/env?   I made the mistake of trying to upgrade juju version - which corrupted the env.   while trying to recover/remove/clean I just released the bootstrap node and uninstalled juju apt-get remove juju.    then tried to start from scratch - install juju,etc.   the problem is there are still remnants of the old system.   I just want to wipe and start from scratch.   juju kill-controller, destroy-controller all fail.

Docs found this on the web also doe not work  "sudo apt-get purge --auto-remove juju"

what I found that works is to:

juju unregister <controller-name>
juju add-cloud  .... maas, etc using the same name as unregister. this will overwrite the prev conf
juju bootstrap <controller-name>  works

**Comment by pmatulis** [comment]
@john-cplanenetworks Are you saying the Juju client upgrade went bad or the Juju agents upgrade?

**Comment by john-cplanenetworks** [comment]
On the juju deployment server – we did an update/upgrade on the os, including juju pkgs.     Juju commands (status, destroy model, add-model) no longer worked.

John Casey
CPlane Networks
Direct: 415-215-0854
