### ISSUE TITLE
documentation on getstarted.md for GUI missing

### ISSUE THREAD

**Issue by hatched** [juju/docs#2356]
Would be great to get some information on the getstarted.md file in the charm author docs.

https://blog.jujugui.org/2017/10/30/juju-gui-get-your-users-started-with-getstarted-md/

**Comment by pmatulis** [comment]
@hatched I'm guessing that this is new in 2.3?

**Comment by hatched** [comment]
So that is to say it's available in JAAS and in any GUI newer than 2.10.0 regardless of which Juju version.
