### ISSUE TITLE
Juju command reference docs missing anchors

### ISSUE THREAD

**Issue by szeestraten-ntnu** [juju/docs#2365]
The juju command reference [docs](https://jujucharms.com/docs/stable/commands) could really use some anchors so people can link specific commands.

**Comment by pmatulis** [comment]
I agree. Unfortunately, this is a design flaw and is outside the scope of the documentation team.

**Comment by szeestraten-ntnu** [comment]
I see. Where can I file an issue for the web team?


On Jan 19, 2018 17:34, Peter Matulis <notifications@github.com> wrote:

I agree. Unfortunately, this is a design flaw and is outside the scope of the documentation team.

**Comment by pmatulis** [comment]
[Here](https://github.com/CanonicalLtd/jujucharms.com/issues/new).

**Comment by szeestraten-ntnu** [comment]
Thanks @pmatulis.

**Comment by evilnick** [comment]
@szeestraten-ntnu Note that you **can** use the implicit anchors provided by the id ( e.g. https://jujucharms.com/docs/stable/commands#list-machines will go to that part of the text. There just isn't an easy link to copy the anchor (and it would be better if that section of the docs opened automatically)

**Comment by pmatulis** [comment]
Because the issue has been created [here](https://github.com/CanonicalLtd/jujucharms.com/issues/516) I will close this one. Cheers.
