### ISSUE TITLE
charm command install instructions missing on getting started

### ISSUE THREAD

**Issue by hatched** [juju/docs#2366]
https://jujucharms.com/docs/stable/developer-getting-started says to run `charm build` but gives no information on where that command came from or how to get it.

**Comment by hatched** [comment]
As it turns out there are links at the top of the page, but the styling doesn't indicate that they are links.

**Comment by pmatulis** [comment]
Thanks. The bold text will be removed.

**Comment by pmatulis** [comment]
Actually, this is another design fail. It appears that any link that resides within an HTML list will appear like this.

**Comment by pmatulis** [comment]
I reported this issue [here](https://github.com/CanonicalLtd/jujucharms.com/issues/514).

**Comment by pmatulis** [comment]
The other issue has been acknowledged. Closing this.
