### ISSUE TITLE
Juju store urls aren't very well documented in our docs

### ISSUE THREAD

**Issue by chuckbutler** [juju/docs#237]
When attempting to deploy directly from the store, the url breakdowns can be a bit obtuse for new users to grokk.

We should have a clear cut definition of how this is implemented in the docs so I can point new users to a single source of truth for how this works with:

juju deploy
juju quickstart
juju deployer

As its mostly ubiquitous - but all of these tools are in use, and warrant being documented.

**Comment by evilnick** [comment]
i believe this is now redundant as everything has changed.

**Comment by chuckbutler** [comment]
i agree :cake:
