### ISSUE TITLE
charm tool usage links do not appear clickable

### ISSUE THREAD

**Issue by hatched** [juju/docs#2372]
https://jujucharms.com/docs/stable/tools-charm-tools At the bottom of the page the links to expand do not turn the cursor to a pointer, or look like they can be interacted with.

**Comment by evilnick** [comment]
You mean they don't look like they work, or they don't actually work?

**Comment by hatched** [comment]
They don't look like links and because the users pointer doesn't change to the link pointer when hovered they don't appear to be interactable

**Comment by evilnick** [comment]
okay, so it's a design issue. thanks

**Comment by pmatulis** [comment]
I reported this issue [here](https://github.com/CanonicalLtd/jujucharms.com/issues/515).

**Comment by pmatulis** [comment]
The above issue has been acknowledged. Closing this.
