### ISSUE TITLE
update register jaas in docs

### ISSUE THREAD

**Issue by chrisheckler** [juju/docs#2405]
docs still show legacy jaas registration command https://jujucharms.com/docs/stable/getting-started#register-or-login-to-jaas

**Comment by pmatulis** [comment]
@mitechie Please advise. Also, which versions of Juju should have their instructions updated (we are currently tracking 2.0, 2.2, and 2.3).

**Comment by evilnick** [comment]
This looks like the updated command was reverted in error  at some point.

@pmatulis it is 2.2 and 2.3 which will need updating

**Comment by pmatulis** [comment]
Just let me know what the change should be and I'll get on it.

**Comment by mitechie** [comment]
Correct, the command is just juju login jaas. I'm pretty sure that has been since 2.1, but I could be mistaken.
