### ISSUE TITLE
Documentation how to configure SSO on controller is missing

### ISSUE THREAD

**Issue by nbyl** [juju/docs#2429]
The documentation mentions the concept of an identity manager when configuring the juju controller. The only part that mentions this is at https://jujucharms.com/docs/stable/controllers-config

The parameter is explained as 

> Sets the URL of the identity manager

Maybe, there should be a link where potential users can find more information on this or how to setup such an identity manager.

I'd be willing to help on this, but currently don't have a clue what this manager is.

**Comment by mitechie** [comment]
Hi @nbyl, this is something that'll be coming across the next cycle. In the JAAS use case where the Juju user system is backed by Ubuntu SSO there's a chunk of code called the identity manager that's being worked out and will be more open for use in the future. It's not there yet as JAAS is in beta and there's some work going into improving it.

So on this one...hold tight. More news in the next cycle.

**Comment by pmatulis** [comment]
I'll update the table on that page mentioning that this key is not yet for user consumption.
