### ISSUE TITLE
OS update/upgrade options need docs

### ISSUE THREAD

**Issue by evilnick** [juju/docs#243]
possibly also linked to #207

**Comment by petermatulis** [comment]
Please elaborate on this issue. We need to document how to update/upgrade the OS (Ubuntu)?

**Comment by petermatulis** [comment]
@evilnick 
Fished this [1] out of the 1.21.1 section of reference-release-notes.md. Is this what you're after?

[1]
=============
  ### Configuring OS update and upgrade for faster provisioning

  When Juju provisions a machine, its default behaviour is to update the
  list of available packages and upgrade the existing packages to the
  latest version. If your OS images are fresh or the services you deploy
  do not require updated packages, you can disable updates and upgrades to
  provision the machine faster.

  Two configuration options are available to disable apt updates and
  upgrades. When your OS images are fresh, you can set both
  ```enable-os-refresh-update```, and ```enable-os-upgrade``` to false. When you
  know that some charms want the latest packages to set up services,
  you will want to keep ```enable-os-refresh-update``` set to "true".

  You can configure the options in environments.yaml for fast provisioning
  like so:

  ```yaml
  enable-os-upgrade: false
  enable-os-refresh-update: false
  ```
  The local provider skips apt upgrades by default for faster
  provisioning. If you wish to enable upgrades in your local
  development, set ```enable-os-upgrade``` to
  "true" in your environments.yaml:

  ```yaml
  enable-os-upgrade: true
  ```

  If you are using the local-provider to develop charms or test, you
  will want to regularly purge the Juju template and LXC caches to
  be certain you are using fresh images. For example, before you start
  testing a new trusty charm, you can remove the template and cloud
  image like this:

  ```bash
  sudo lxc-destroy -n juju-trusty-lxc-template
  sudo rm -r /var/cache/lxc/cloud-trusty
  ```
=============

**Comment by evilnick** [comment]
It looks like it belongs as a section on that general config page, but you may want to reference it from elsewhere - e.g. local-provider 


that config page is sorely in need of a table of contents
