### ISSUE TITLE
Down machine replacement docs for a MAAS cloud

### ISSUE THREAD

**Issue by hyperbolic2346** [juju/docs#2436]
It would be nice if there were documentation about how to properly handle a down machine in juju in the troubleshooting or howto section of the docs. I'm looking for something like what you do in the case of hardware failure like a hard drive or even a full machine replacement. I apologize if I just overlooked it somehow, but even that might be useful information.

**Comment by pmatulis** [comment]
@hyperbolic2346 Are you talking about using Juju with a MAAS backing cloud? Otherwise, the Juju machine will be virtual.

**Comment by hyperbolic2346** [comment]
@pmatulis Yes, this is a MaaS deployment. I had a machine's hard drive die and I'm looking for the proper method of fixing it. It is possible the best option is to add a new machine and delete the old. I was just looking for a faq or best practices.

**Comment by pmatulis** [comment]
Thanks for the confirmation. We may be adding a few MAAS-specific pages in the coming weeks so I will try to squeeze this aspect in.
