### ISSUE TITLE
'agent-stream' and 'image-stream' options need explaining

### ISSUE THREAD

**Issue by evilnick** [juju/docs#244]
possibly also linked to #207

**Comment by petermatulis** [comment]
Closed #481 ; imported relevant commentary here.

====

The image metadata section [1] of the private cloud how-to should probably mention the "image-stream" option. This environments.yaml option isn't very well explained [2], but relevant to the discussion of image metadata in the private cloud how-to.

[1] https://jujucharms.com/docs/stable/howto-privatecloud#image-metadata
[2] The only good info I found was in the "Using daily image streams for faster provisioning" section of the 1.21.1 release notes.

==

It is included specifically in https://jujucharms.com/docs/devel/config-general, but yes, it needs more explanation there and elsewhere

====
