### ISSUE TITLE
update-credential documentation is unclear

### ISSUE THREAD

**Issue by anastasiamac** [juju/docs#2441]
As was seen by the experience in https://bugs.launchpad.net/bugs/1735402, we need to make sure that our online documentation provide clear guidance as to what needs to happen when cloud credentials expire, say  on a long living controller.

Clarity around update-credential and its limitations is a start...

**Comment by pmatulis** [comment]
TL;DR

This issue affects the Azure provider only. 

Juju team has a general re-work of credentials UX on their radar.

Current doc "fix" for Azure ([help-azure.md](https://github.com/juju/docs/blob/master/src/en/help-azure.md)):

 1. ```juju add-credential azure```
 1. ```juju credentials azure --format yaml --show-secrets```
 1. Take the above output, paste it into azure-creds.yaml (now containing both the new and the old sets of credentials), and copy the values of ```application-id``` and ```application-password``` from the new set to the old set.
 1. ```juju add-credential azure -f azure-creds.yaml --replace```
 1. ```juju update-credential azure <name of your old creds>```
