### ISSUE TITLE
manual add-cloud documentation is incorrect

### ISSUE THREAD

**Issue by hatched** [juju/docs#2445]
Original: https://github.com/CanonicalLtd/jujucharms.com/issues/519

The fold-out for "Manual" clouds is a duplicate of "MAAS":

https://jujucharms.com/docs/stable/clouds#specifying-additional-clouds

For juju-2.3.2 at least, the exchange should look like this:

$ juju version
2.3.2-highsierra-amd64

$ juju add-cloud
Cloud Types
  maas
  manual
  openstack
  oracle
  vsphere

Select cloud type: manual

Enter a name for your manual cloud: mycloud

Enter the controller's hostname or IP address: <sudo_user>@<ip>

Cloud "mycloud" successfully added
You may bootstrap with 'juju bootstrap mycloud'
You'll notice I put in <sudo_user>@<ip> for the hostname. It is important that the user know that Juju needs to be able to ssh over to the machine with an account that has sudo privileges. I'm not sure the best way to present this requirement in this doc; feel free to change <sudo_user>@<ip> in whatever way makes this more clear.

**Comment by kwmonroe** [comment]
FYI, this juju bug to make add-model more descriptive is somewhat related:

https://bugs.launchpad.net/juju/+bug/1749302
