### ISSUE TITLE
new api-info command

### ISSUE THREAD

**Issue by evilnick** [juju/docs#249]

**Comment by petermatulis** [comment]
@evilnick 
Fished this [1] out of the 1.21.1 section of reference-release-notes.md. Is this what you're after?

[1]
=============
  ### Inspecting the API connection settings

  The ```juju api-info``` command shows the settings used to connect to the
  Juju state-server's API. You can see the settings for all the fields
  (except for password) like so:

  ```bash
  juju api-info
  ```

  If you want to see the password being used, you need to either use the
  "--password" option:

  ```bash
  juju api-info --password
  ```

  or specify the password field as the only field to show:

  ```bash
  juju api-info password
  ```

  You can learn the value of any field by including it in the command
  line. For example, to learn the name of user created during bootstrap,
  type:

  ```bash
  juju api-info user
  ```
=============

**Comment by petermatulis** [comment]
I'm not sure where this should go.
