### ISSUE TITLE
Show how to set a model configuration key value to null

### ISSUE THREAD

**Issue by pmatulis** [juju/docs#2541]
A model configuration key can be set to a null value. The current docs do not mention using null values  but it is worth doing so. Previously, this was required:

`juju model-config blah=\"\"`

Now, this is possible:

`juju model-config blah=""`
`juju model-config blah=`

As per https://github.com/juju/juju/pull/7615

**Comment by evilnick** [comment]
probably best to pick one. i don't really see the point of having both
