### ISSUE TITLE
Clarify that a relation ID can be used with `remove-relation`

### ISSUE THREAD

**Issue by pmatulis** [juju/docs#2547]
Clarify that a relation ID can also be used when removing a relation. 

Affects charms-destroy.md and models-cmr.md. Review the best way for these pages to be less redundant. 

As per https://github.com/juju/juju/pull/7744

**Comment by pmatulis** [comment]
The CMR documentation already shows that `remove-relation` works with relation IDs. Apparently this works with non-CMR setups except that there does not seem to be a way to discover the ID in that context. For CMR, it is exposed via `juju show-offers`. @wallyworld ?

**Comment by wallyworld** [comment]
It's a bit messy. Charms are able to discover and use the relation ids using the relation-ids hook command. But you are right in that juju status doesn't show them. So the only place in Juju that currently exposes the relation id is CMR. I think we should add the relation id to status (at the least in yaml/json) output.

**Comment by pmatulis** [comment]
I opened [LP 1776665](https://bugs.launchpad.net/juju/+bug/1776665).

Closing this.
