### ISSUE TITLE
Add JUJU_VERSION variable to hook environment

### ISSUE THREAD

**Issue by pmatulis** [juju/docs#2550]
As per https://github.com/juju/juju/pull/7898

Affected file: authors-hook-environment.md

Add an entry under:

`The following variables are always available.`

**Comment by evilnick** [comment]
This actually needs to go here https://jujucharms.com/docs/stable/reference-environment-variables

**Comment by pmatulis** [comment]
I thought that page was for shell environment variables. Isn't JUJU_VERSION a hook environment variable? I'm probably wrong but I did consider the other page.

**Comment by evilnick** [comment]
We should have them all in the same place, at least for reference. The reference page is probably best for this, though it could do with more explanation too. there is also a difference between things available on the Unit and on the unit when running within a hook context

This doesn't mean these things shouldn't be discussed elsewhere, but all those author-* pages are going to die, so it seems pointlessto change them

https://jujucharms.com/docs/stable/reference-environment-variables#unit
