### ISSUE TITLE
Add ICMP rule support to hook tools

### ISSUE THREAD

**Issue by pmatulis** [juju/docs#2552]
Affects reference-hook-tools.md

There is a lot of redundancy with authors-hook-environment.md. I'm not sure what to do about that. @evilnick ?

As per https://github.com/juju/juju/pull/7969

**Comment by evilnick** [comment]
forget about it, all these pages are going

**Comment by pmatulis** [comment]
Do you mean I should forget about this entire issue or just omit updating authors-hook-environment.md?

**Comment by evilnick** [comment]
don't bother with hook-environment.md, but I guess, do add it to the reference page
