### ISSUE TITLE
duplicate tags created in markdown>html generation

### ISSUE THREAD

**Issue by evilnick** [juju/docs#259]
Just spotted this today, e.g. from the azure config page:

```
<a href="https://manage.windowsazure.com"><a href="https://manage.windowsazure.com">https://manage.windowsazure.com</a></a>
```

**Comment by evilnick** [comment]
I really can't figure this out - the standalone markdown_py seems to process this fine. Any ideas @marcoceppi ?
It isn't a major problem, just generates unpleasant HTML which I guess could go wonky depending on the browser.

**Comment by chuckbutler** [comment]
I'm not 100% certain on this nick but if you change the description from the full link it didn't render the extra artifact. I'll take a closer look at this later if someone else doesn't get to it before me.

**Comment by petermatulis** [comment]
@chuckbutler 
Did you find anything?

**Comment by chuckbutler** [comment]
@petermatulis aside from changing it from a full-formed link to omitting the http://, i have not looked at this in any detail since I posted above.
