### ISSUE TITLE
JUJU_AVAILABILITY_ZONE variable is not just for developers

### ISSUE THREAD

**Issue by anastasiamac** [juju/docs#2595]
As per https://bugs.launchpad.net/juju/+bug/1759737, JUJU_AVAILABILITY_ZONE is a valid environment variable and is not limited to development use only.

Please update https://jujucharms.com/docs/stable/reference-environment-variables.
At the very list, it should not be in the list at the bottom of the page.

**Comment by evilnick** [comment]
It was in that section because that's where we were told to put it:
https://github.com/juju/docs/issues/742#issuecomment-158108250

I'm fine with including it in the main part of that page

**Comment by pmatulis** [comment]
@evilnick There are three other sections to that page: 'Juju client', 'Building', and 'Unit'. To which one do you want this variable moved to?
