### ISSUE TITLE
Using Juju link points to a topic page of "introducing charms"

### ISSUE THREAD

**Issue by chuckbutler** [juju/docs#260]
This is misleading, the topic page gives an overview of charms - not so much on "using juju" - which to me would be more of an overview on how to interface with juju, a brief introduction to charms, and links to sub-topic pages with a brief overview of the page contents/intent.

**Comment by petermatulis** [comment]
I guess some stuff needs to be added *before* the "Introducing Charms" header. I agree that the page is jarring as is.

**Comment by petermatulis** [comment]
@evilnick 
What do you think about renaming the page 'Juju Charms' and be done with it? The underlying file is already just called 'charms'.

**Comment by petermatulis** [comment]
Confirmed today that the above will be done. Stand by.

**Comment by petermatulis** [comment]
See PR #592
