### ISSUE TITLE
Clarify for 2.3 that a controller will continue to get deployed on Xenial

### ISSUE THREAD

**Issue by pmatulis** [juju/docs#2609]
As per https://bugs.launchpad.net/juju/+bug/1762741

In terms of the default release, for now we will hardcode "Xenial" for the 2.3 version of the Juju docs. The 2.2 version will continue to say "latest LTS". Bionic is being deferred until 18.04.1 as unforeseen Juju breakages have cropped up.

**Comment by anastasiamac** [comment]
@pmatulis,
Just to clarify -  Juju controllers will be able to bootstrap on 'bionic' if the users will choose to do so. However, 'bionic' will not be picked as a default LTS by Juju immediately upon 'bionic' release.

**Comment by pmatulis** [comment]
Yes, the default.
