### ISSUE TITLE
Stop hook documentation is unclear

### ISSUE THREAD

**Issue by galgalesh** [juju/docs#264]
The [stop hook documentation](https://juju.ubuntu.com/docs/authors-charm-hooks.html#stop) is a bit unclear. It currently reads "Stop [...] should be used to ensure that the charm's software is not running, and will not start again on reboot." While actually it should do a bit more:

>The stop hook is typically responsible for a few concerns.
>
>Stopping the service
>removing any responsible application files/configuration that were populated during the service lifecycle.
>Preparing any backup(s) of the service that are required to restore (in a well formed charm)
>

So stop should actually do a stop + save + uninstall

[source](http://askubuntu.com/questions/584716/what-does-juju-destroy-service-do-exactly/584746)

**Comment by evilnick** [comment]
yes, I was also confused by this - "stop" is slightly ambiguous in this context. I will add more material to make it clearer

**Comment by petermatulis** [comment]
This is fixed in the devel version. Closing.
