### ISSUE TITLE
"Removal with Juju" documentation needs more detailed explanation

### ISSUE THREAD

**Issue by galgalesh** [juju/docs#265]
The [removal with Juju documentation](https://juju.ubuntu.com/docs/charms-destroy.html#removing-services) talks about the commands like `juju remove-service <service-name>` without actually explaining what the commands do. For example, it doesn't say that the `juju remove-service` calls the stop hook.

I have asked an askubuntu question about this and received an [excellent answer](http://askubuntu.com/a/584746/172367). I think this information should be included in the documentation about each command.

**Comment by galgalesh** [comment]
Thanks for fixing this

**Comment by evilnick** [comment]
np, thanks for filing the issue - sorry it took so long!
