### ISSUE TITLE
authors-charm-building page is outdated, links to 404

### ISSUE THREAD

**Issue by jamesbeedy** [juju/docs#2659]
![screen shot 2018-04-24 at 8 19 29 am](https://user-images.githubusercontent.com/5590546/39197100-8c9344e0-4798-11e8-8d02-ad80752ebbfa.png)

Link to stable docs is broken, need working link.

**Comment by pmatulis** [comment]
That page doesn't exist anymore. Please use the menu. [This page]( https://jujucharms.com/docs/stable/developer-getting-started) is a decent beginning. A lot of the charm developer documentation needs to be redone.

**Comment by pmatulis** [comment]
That page doesn't exist anymore. Please use the menu. [This page](https://jujucharms.com/docs/stable/developer-getting-started) is a decent candidate. The entire section of the charm developer pages needs to be redone.

**Comment by erik78se** [comment]
Its kind of disencouraging when the documentation isn't working for newcomers. Especially the "getting started" endpoints.

**Comment by jamesbeedy** [comment]
@erik78se I think what he is saying is that the getting started stuff is in order, but for some reason the stale docs come up on google search instead of the current/working docs. 

@pmatulis is this a fair assessment?

**Comment by pmatulis** [comment]
@jamesbeedy Yes, correct.

**Comment by erik78se** [comment]
Right, ok.

**Comment by evilnick** [comment]
the erroneous search links should be fixed in the medium term.
See also - https://github.com/canonical-webteam/documentation-builder/issues/96

Also, the out-of-date message on all archive docs will be changing soon - https://github.com/juju/docs/pull/2636

**Comment by pmatulis** [comment]
The two issues cited by @evilnick have been dealt with by the webteam. In accordance with the same rationale provided [in this closed docs issue](https://github.com/juju/docs/issues/2835#issuecomment-454169026) I will be closing this issue. This is not a docs issue but a webteam issue.
