### ISSUE TITLE
make broken (or just a bit outdated?)

### ISSUE THREAD

**Issue by erik78se** [juju/docs#2681]
I'm trying to "make" the documentation (on xenial).

I wish to contribute to the documentation, but its now working out easily.

This is my workflow:

```
git clone ...
python3 -m venv myvenv
source myvenv/bin/activate
pip install --upgrade pip
pip install -r requirements.py
make
```
Breaks....

Traceback (most recent call last):
  File "/home/erik/github/erik78se/docs/venv/lib/python3.5/site-packages/markdown/__init__.py", line 246, in build_extension
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'markdown.extensions.callouts'
...

`pip install markdown
`
Requirement already satisfied: markdown in ./venv/lib/python3.5/site-packages (2.6.6)
ubuntudesign-documentation-builder 1.5.1 has requirement Jinja2==2.8, but you'll have jinja2 2.10 which is incompatible.

`pip install callouts
`
Collecting callouts
  Could not find a version that satisfies the requirement callouts (from versions: )
No matching distribution found for callouts

[update]
Oh, after installing the "make sysdep" it works, however, it requires me to be "root"/"sudo" which isn't really so good.

Would it be possible to make the "sysdep" part only dependent on the "requirement.txt" installation dependencies so that you dont have to be administrator on a node to "make" the documentations?

**Comment by erik78se** [comment]
Oh, after installing the "make sysdep" it works, however, it requires me to be "root"/"sudo" which isn't really so good.

Would it be possible to make the "sysdep" part only dependent on the "requirement.txt" installation dependencies so that you dont have to be administrator on a node to "make" the documentations?

**Comment by pmatulis** [comment]
@erik78se Hi, thanks for your interest in Juju documentation. We'll take a look at your suggestion. I should also mention that the documentation will soon be moving over to a new build system.

**Comment by evilnick** [comment]
The docs are now built in situ with the web server also configured and run from the repository (with the run command) 
However, this is not the best way for contributors to interact with the docs. I will look at updating the makefile to better support local development/checking
