### ISSUE TITLE
howto-privatecloud gives the impression that swift and simplestreams are required

### ISSUE THREAD

**Issue by jhobbs** [juju/docs#2686]
At some point, juju's cli changed to use --metadata-source for local metadata, rather than metadata hosted in swift. The current howto doesn't talk about this, and it gives the impression that swift is the only way to accomplish bootstrapping against juju.

That's unfortunate because there are many more steps involved in getting it working in swift, and not all openstacks have swift available.

**Comment by evilnick** [comment]
@hmlanigan ?

**Comment by jhobbs** [comment]
@hmlanigan I don't know - that's a broken link. If the link works and talks about how to use '--metadata-source', then yes.

**Comment by hmlanigan** [comment]
@jhobbs , hmm... now i only see it in the devel version of the docs.  this is weird.  does this link work: https://docs.jujucharms.com/devel/en/howto-privatecloud?  there should be a section like below:

Use of a local directory for image metadata
Stop here and return to the bootstrap instructions.

"bootstrap instructions" is a link to: https://docs.jujucharms.com/devel/en/help-openstack#bootstrap-with-juju

**Comment by pmatulis** [comment]
@hmlanigan So you want those two lines in 2.3 then?

**Comment by hmlanigan** [comment]
They are applicable to all 2.x versions, please add to 2.2, 2.3, 2.4 and
devel docs.

**Comment by pmatulis** [comment]
2.4 isn't out yet, and the lines *are* in devel. Backporting to 2.2 is often problematic but I'll take a look (also, 2.2 will soon be removed from the docs site). So 2.3 is the main target here.

**Comment by pmatulis** [comment]
This correction was made to 2.2 and 2.3 via #2782 and #2783 and will be reflected on the site at the next build time. Closing.
