### ISSUE TITLE
Note syntax broken in 1.25 docs

### ISSUE THREAD

**Issue by charlesdunbar** [juju/docs#2695]
Looking at some docs in 1.25 - every note special markdown is blank.  Switching the docs to a 2.x version of the docs fixes it however.

Some examples:

https://docs.jujucharms.com/1.25/en/charms-destroy
https://docs.jujucharms.com/1.25/en/reference-hook-tools

**Comment by evilnick** [comment]
Thanks for the heads up. We changed the way docs are generated recently, and we did have 1.25 working but there must have been a regression somewhere.

**Comment by evilnick** [comment]
it seems this was a change in the default style template which may have caused this, so not actually an issue with these docs, but with all docs. A fix is being worked on

**Comment by pmatulis** [comment]
This looks to be [fixed](https://docs.jujucharms.com/1.25/en/config-maas). Please re-open if the issue reoccurs. :walking_man:
