### ISSUE TITLE
default redirects aren't working

### ISSUE THREAD

**Issue by evilnick** [juju/docs#2724]
https://docs.jujucharms.com/devel/ currently redirects to https://docs.jujucharms.com/devel/en/ and then gives a 500

**What should happen?**
https://docs.jujucharms.com/devel/en/ should redirect to https://docs.jujucharms.com/devel/en/getting-started

**ALSO:** 
https://docs.jujucharms.com/stable/ redirects to https://docs.jujucharms.com/2.3/en/ and then gives a 500

**What should happen**

anything like `https://docs.jujucharms.com/<version>/en/` should point to `.../<version>/en/getting-started`

**Comment by evilnick** [comment]
@pmatulis @anthonydillon @WillMoggridge

**Comment by anthonydillon** [comment]
@evilnick Redirects added here: https://github.com/juju/docs/pull/2727
