### ISSUE TITLE
Broken links from juju cli --help to online docs

### ISSUE THREAD

**Issue by AdamIsrael** [juju/docs#2729]
Hi all,

I suspect this is a larger issue to be addressed, but while checking `juju bootstrap --help` I tried to follow two links in particular that lead me to a 404:

```
Available keys for use with --config can be found here:
    https://jujucharms.com/docs/stable/controllers-config
    https://jujucharms.com/docs/stable/models-config
```
The content is available at https://docs.jujucharms.com/stable/en/controllers-config. It looks like we've been transitioned to localized content (yay!) but in doing so have broken some (or many) links between the cli command docs and the online docs.

Perhaps something can be added at these pages that would auto-detect the browsers language setting and redirect to the correct locale?

**Comment by evilnick** [comment]
Hi,
Yes, this is a known if somewhat annoying issue. The site was switched but jujucharms.com doesn't have the correct redirects in place. The fix is pending a release it seems

https://github.com/CanonicalLtd/jujucharms.com/issues/527

**Comment by evilnick** [comment]
I'm going to mark this as closed, as I think a release may be imminent and the corresponding issue has been closed.
