### ISSUE TITLE
metadata reference scrambled

### ISSUE THREAD

**Issue by stub42** [juju/docs#2736]
On https://docs.jujucharms.com/2.3/en/authors-charm-metadata

"A metadata file defines the charm's relations, and whether it's designed for deployment as a subordinate service." is out of place. It is talking about relations, but is under storage. This might just be a missing header, since there is no actual relation section.

~~"Endpoint names are strings and must not match existing relation names from the Provides, Requires, or Peers metadata sections. The values beside each endpoint name must be left out (i.e. "foo": <anything> is invalid)." would also belong under the missing relation section, but is found under Extra bindings. Looks like someone started an update with the newer Endpoint terminology, or a mismerge.~~ (use of endpoint confused me, as it is a term we are now using for relations and normally had just used 'binds' instead of 'bind endpoints')

"Other available fields are:" doesn't belong under the Extra Bindings section, but instead an other/misc/stuff-that-doesn't-fit-elsewhere section.

**Comment by pmatulis** [comment]
I looked at the history of this file and this confusion has been present for a long long while. Thanks for bringing this to light.

**Comment by pmatulis** [comment]
I think I'll place the first batch of text ("A metadata file defines..." plus the three bullet points) at the top of the page (after the existing text). And then followed by the second batch of text ("Other available fields...").

**Comment by pmatulis** [comment]
@stub42 I ended up doing a complete review of this page.
