### ISSUE TITLE
Need more info to bootstrap a private OpenStack cloud 

### ISSUE THREAD

**Issue by chanjarster** [juju/docs#2746]
Hi, I'm trying to bootstrap a private OpenStack cloud following this [guide][1] and this [guide][2]. But I get stuck by the floating ip. After some googling I found there is a config key `use-floating-ip=true` which is not mentioned in the doc. But after adding this config another problem raised. So I guess may be there are some other config keys not mentioned in the doc.

PS. Actually the `network` and `use-floating-ip` are not mentioned in [controllers config][3]

[1]: https://docs.jujucharms.com/2.3/en/help-openstack
[2]: https://docs.jujucharms.com/2.3/en/howto-privatecloud
[3]: https://docs.jujucharms.com/2.3/en/controllers-config

**Comment by pmatulis** [comment]
Thanks for surfacing this omission. We'll dig into it.
