### ISSUE TITLE
document config-changed behavior during hook execution and retries

### ISSUE THREAD

**Issue by dshcherb** [juju/docs#2775]
It is currently not apparent how config-get works across executions and those sections do not mention anything at all:

https://docs.jujucharms.com/2.3/en/reference-hook-tools#config-get
https://docs.jujucharms.com/2.3/en/charms-config

Currently, each **hook execution** or **hook retry** will get a new copy of a config:

```
landscape-server/2*           error     idle   7/lxd/4  10.232.6.15                         hook failed: "db-relation-changed"

juju resolved landscape-server/2

root@juju-149147-7-lxd-4:/var/lib/juju/agents/unit-landscape-server-2/charm# config-get
key: 4652B4E6
root-url: ""
smtp-relay-host: ""
source: ppa:landscape/17.03
ssl-cert: ""
ssl-key: ""
worker-counts: 2

juju config landscape-server key='10'

root@juju-149147-7-lxd-4:/var/lib/juju/agents/unit-landscape-server-2/charm#  exit 1

juju resolved landscape-server/2`

root@juju-149147-7-lxd-4:/var/lib/juju/agents/unit-landscape-server-2/charm#  config-get
key: "10"
root-url: ""
smtp-relay-host: ""
source: ppa:landscape/17.03
ssl-cert: ""
ssl-key: ""
worker-counts: 2
```

Hook queuing might give a charm developer a false impression that a config-get will return a different result only after **config-changed** is run. As seen above, this is not the case and config-get fetches the latest config from the controller (apiserver) at the time when hook execution context is generated in a unit agent.

This can result in race conditions in the code that assumes the opposite.

**Comment by pmatulis** [comment]
Thanks for bringing this up.
