### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by galgalesh** [juju/docs#286]
https://jujucharms.com/docs/authors-interfaces

At the bottom of this page, there is a broken link (mysql)

**Comment by evilnick** [comment]
thanks for the report. The source for this exists (https://github.com/juju/docs/blob/master/src/en/interface-mysql.md) so it seems like a generation issue. I will investigate

**Comment by evilnick** [comment]
The page is being generated okay, so it most likely is a problem with the jujucharms website. I created an issue for it. Thanks for the report

**Comment by evilnick** [comment]
fix should be live  next time there is an update
