### ISSUE TITLE
Clarity around openstack keystone v2 vs v3 configuration

### ISSUE THREAD

**Issue by anastasiamac** [juju/docs#2868]
As per https://bugs.launchpad.net/juju/+bug/1770835 (see comment 2 especially), there could be some confusion around what values need to be specified for keystone v2 vs v3.

I am not too sure what we can do about Openstack's documentation though :)

**Comment by pmatulis** [comment]
This is solid. An update will appear today. Thanks.

**Comment by pmatulis** [comment]
@anastasiamac I have serious doubts now. Please see the LP bug.

**Comment by pmatulis** [comment]
@anastasiamac I'm going to close this bug in a few days unless I can get some reliable information.

**Comment by pmatulis** [comment]
This bug is now expired.
