### ISSUE TITLE
[2.5] Document `export-bundle` command

### ISSUE THREAD

**Issue by pmatulis** [juju/docs#2886]
The CLI is growing the ability to save a bundle. Previously the web UI was the only way.

As per:

 - https://github.com/juju/juju/pull/8912
 - https://github.com/juju/juju/pull/8962

**Comment by pmatulis** [comment]
:warning: This is hidden behind a flag for 2.4.

See https://github.com/juju/juju/pull/9076

**Comment by hatched** [comment]
There will be a slight difference in functionality between a bundle export in the GUI and the CLI. The GUI supports exporting a bundle without actually deploying a model whereas the CLI doesn't have that 'uncommitted' functionality.

**Comment by pmatulis** [comment]
@hatched Do you mean that `export-bundle` requires an existing deployment whereas the GUI does not?

**Comment by howbazaar** [comment]
@hatched this is getting juju to export the current model as a bundle, not the deploy phase.

**Comment by hatched** [comment]
@pmatulis correct.

However exporting an existing model will likely contain more information and be a more reliable export. The GUI will generate a bundle yaml from all the information it has at any time, deployed or not.

**Comment by hatched** [comment]
@howbazaar When the GUI generates a bundle it could have some deployed and some 'uncommitted' changes and still generate an all encompassing bundle. It does this by generating the bundle yaml from what it has in it's internal database of the model.

**Comment by pmatulis** [comment]
Closed via #3083

**Comment by pmatulis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [export-bundle](https://trello.com/c/VRXr3KAZ/618-export-bundle)
