### ISSUE TITLE
Page missing from navigation 

### ISSUE THREAD

**Issue by mitechie** [juju/docs#289]
Copied over from: https://github.com/CanonicalLtd/jujucharms.com/issues/57

Afaict https://jujucharms.com/docs/authors-interfaces is not linked from anywhere in nav or related pages. Content of this doc is significantly more detailed for writing interfaces than https://jujucharms.com/docs/authors-charm-interfaces however.

**Comment by evilnick** [comment]
ok thanks, this looks like a page which got mixed up when we switched to markdown last year
