### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by paulgear** [juju/docs#2891]
https://docs.jujucharms.com/2.4/en/getting-started contains the following broken links in the navigation:

"Report a docs issue": https://docs.jujucharms.com/github.com/juju/docs/issues/new
"Layers and charms.reactive": https://docs.jujucharms.com/charmsreactive.readthedocs.io

There are probably several more similar problems - I didn't check all the navigation.

**Comment by evilnick** [comment]
Thanks for spotting this. It seems to be a bug in documentation-builder, as the links are correct in the source. Possibly something has gone awry with the url-rewriting rules
