### ISSUE TITLE
Tech preview - windows workloads

### ISSUE THREAD

**Issue by evilnick** [juju/docs#290]
Summary:
- Windows workloads are now possible as a preview

Description:
## Windows workloads are now possible as a preview

Starting with 1.21 there is initial windows workload support in juju.
This is BETA at the moment, and will be improved in the following releases.

A juju charm boilerplate has been created and is available here:
https://github.com/cloudbase/windows-charms-boilerplate

We encourage you to use powershell as the language of choice when
writing juju charms for windows, as it is tightly coupled to Windows
automation, but feel free to use any language you see fit.

We tried to keep juju charms on Windows as close to their counterparts
on Ubuntu as much as possible, but there are a few notable differences
between charms running on Ubuntu and charms running on Windows:
- All charm hooks must have one of the following extensions: .ps1, .cmd,
  .bat, .exe. The extensions will be searched in order, with powershell
  being default.
- All juju files/charms are located in: C:\juju . The folder structure
  should be the same as on ubuntu, with C:\juju as the root.
- Cloudbase-init installs a local copy of python 2.7 (soon to switch to
  3.X). If you wish, you can write python code to deploy your
  applications, but keep in mind you would have to wrap the execution of
  your script in one of the filetypes above (.ps1, .cmd, .bat, .exe).
- If the machine reboots for whatever reason, juju machine agents and
  unit agents will have a delayed start. This means that juju services
  will start 2 minutes after the last windows service is started. So if
  the juju services are listed as "Stopped" immediately after reboot,
  don't panic.
- all juju services (and therefor charms) will run under an
  administrator account called: jujud. This will allow charms to use
  installers that require a real user, and not just the "system" user.

You can deploy windows workloads on any of the available providers
(except manual and local) that offer Windows images, bundled with
Cloudbase-init.

Current limitations:
- Windows cannot be used as a bootstrap machine. Only machine agents are
  supported.
- juju ssh currently does not work with windows. That implementation is
  tightly coupled with *nix systems, and having OpenSSH deployed on
  windows machines might later become a security risk due to the fact that
  it is not part of normal windows update systems. Work is being done to
  integrate WinRM support into juju. This will allow us to offer the same
  level of integration using powershell remoting
  (http://msdn.microsoft.com/en-us/library/dd357801.aspx)
- manual provider is not supported. Manual provider requires SSH to
  deploy. See above mention.
- local provider is not supported. At the moment, local provider relies
  on LXC to work. also, it will deploy a bootstrap machine locally, which
  is currently not supported on windows.
- debug hooks are not yet supported. The current implementation requires
  SSH and tmux to work, which is very platform specific. This is high
  priority and we will try to get this implemented for windows as well, as
  soon as possible.

**Comment by chuckbutler** [comment]
@evilnick I was going to start injecting some of the docs we put together for the OCP demo in a working PR against this - and hand off to the CloudBase team to fill in any gaps that they could. Is this something you're interested in or do you already have WIP against this item?

**Comment by chuckbutler** [comment]
actually, let me ammend that statement - A good majority of the document focuses on the MAAS setup side, which doesn't necessarily need to live in the Juju documents. The outline you have above - has far more information regarding Juju and windows than the setup doc does.. because Juju on windows for the most part, just worked as it was supposed to. (barring the known things that don't work)

**Comment by evilnick** [comment]
I haven't done any work on this yet. I *think*, from the information I have so far, we should probably create a new " tech preview" page, where we can outline the information above for the time being, and add notes etc to the main pages where relevant. This could include notes on the MAAS setup too (as I don't know where else we would put those).

**Comment by chuckbutler** [comment]
@evilnick i've just thrown together the sketch notes in a howto page lastnight - got that committed up and pushed here so we can collab on the effort. I'll loop in @gabriel-samfira and Alessandro where applicable.  If this needs to be chopped apart, or conglomerated in a different page - feel free to review as such.

Thanks and :cheers:

**Comment by evilnick** [comment]
Are we any closer to having this done?

**Comment by chuckbutler** [comment]
I haven't received any word back from the cloudbase team, I'll mail @gabriel-samfira and point him at this issue and see where they stand.

Thanks for circling back @evilnick

**Comment by gabriel-samfira** [comment]
Sorry for not replying sooner. We are still traveling, and will be in the
US until the 30th.

Charles, can you link me to the document you mentioned so I can have a
look? I should be able to review it tonight.

Cheers
Gabriel

**Comment by chuckbutler** [comment]
@gabriel-samfira No problem, I linked you to the document. It was the OCP Demo prep notes, which may or may not be depreciated now as I know some additional work has been done to rev/refine that process a bit.
