### ISSUE TITLE
Docs needed: definitive list of bundle properties and format

### ISSUE THREAD

**Issue by evilnick** [juju/docs#294]

**Comment by mitechie** [comment]
We've got plans to do this as part of some ongoing work. The current document is in a google doc and @makyo is going to be working on updating those docs here in the coming week.

**Comment by AdamIsrael** [comment]
The bundle file has been documented fairly well here: https://jujucharms.com/docs/2.2/charms-bundles

I think what it's still lacking is a complete example of a bundle file showing every available option.

**Comment by pmatulis** [comment]
@mitechie @AdamIsrael 
Has there been any progress here?

**Comment by mitechie** [comment]
No, unfortunately there's not been.

**Comment by pmatulis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bundle file format lacks explanation](https://trello.com/c/M32jNvKE/1-bundle-file-format-lacks-explanation)

**Comment by pmatulis** [comment]
affects #1689 (storage)
affects #1836 (subordinates)

**Comment by pmatulis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bundle properties and format](https://trello.com/c/JnhhW59V/1057-bundle-properties-and-format)
