### ISSUE TITLE
404 doc pages raise internal server errors

### ISSUE THREAD

**Issue by jcsackett** [juju/docs#2947]
Per @frankban, reporting on https://github.com/CanonicalLtd/jujucharms.com/issues/535:

> For instance:
> https://docs.jujucharms.com/2.4/en/no-such
> https://docs.jujucharms.com/2.4/en/

Not sure if this is triggering redirection issues or it's something else. Other obviously not existing urls also trigger server error rather than 404, e.g. https://docs.jujucharms.com/this-does-not-exist.

**Comment by pmatulis** [comment]
The lack of a 404 page is being tracked here:

https://github.com/canonical-webteam/generator-canonical-webteam/issues/72

Although I agree that a non-page (https://docs.jujucharms.com/2.4/en/) request should be redirected at the Juju docs repository level.
