### ISSUE TITLE
GCE credential instructions are out of date and misses some things

### ISSUE THREAD

**Issue by evilnick** [juju/docs#2968]
The page at https://docs.jujucharms.com/2.4/en/help-google is now slightly out of date with the website. 

It also now needs to advise enabling the IAM API, which is required for some charms to work properly.

Rather than just regenerate all the steps for the latest iteration of the website, I suggest it might be better/easier/more durable to recommend using the  [cloud sdk](https://cloud.google.com/sdk/) tools from google to do this. I suspect there will be more longevity in the command-line tools than the website design, and it would be easier to test if it required updating.

**Comment by evilnick** [comment]
I believe the relevant command for creating credentials is `gcloud iam service-accounts keys create`
Anyhow, the documentation on auth is here https://cloud.google.com/sdk/docs/authorizing

**Comment by pmatulis** [comment]
I've made some progress on this. It should be feasible to provide instructions for the CLI method.
