### ISSUE TITLE
Broken link in Google search results

### ISSUE THREAD

**Issue by AdamIsrael** [juju/docs#2970]
I googled for "juju actions" and both their highlighted result and the top result lead to a 404:

https://docs.jujucharms.com/master/authors-charm-actions
https://docs.jujucharms.com/2.0/en/actions

**Comment by mitechie** [comment]
I'm finding that even searching the docs at all I get links to 2.0 but that
fails and I have to manually change to 2.4 to get it to load

**Comment by huwshimi** [comment]
This also affects links coming from the main jujucharms.com site such as the docs link in the header.
