### ISSUE TITLE
[devel] Home page redirect loop

### ISSUE THREAD

**Issue by pmatulis** [juju/docs#3037]
@WillMoggridge 

The home page for the devel version does not work.

https://docs.jujucharms.com/devel/en/index

ends up here:

https://docs.jujucharms.com/devel/en/

Chrome says:

This page isn’t working
docs.jujucharms.com redirected you too many times.

**Comment by WillMoggridge** [comment]
That looks like a good change, I agree with it

**Comment by pmatulis** [comment]
Alrighty then. I'll shut this issue down.
