### ISSUE TITLE
Make it clear that users should back up all or part of their .juju directory.

### ISSUE THREAD

**Issue by ericsnowcurrently** [juju/docs#313]
(see https://bugs.launchpad.net/juju-core/+bug/1427257)

It sounds like it isn't clear to users that the .juju directory (or at least the environments.yaml file) is a single point of failure that they should be backing up.  Nor what the consequences of losing the directory (or that file) are.  In the case of the above-cited bug report, the user was under the impression that a juju backup archive (from `juju backup` or `juju backups create`) had them covered.  That is a clear example to me of what we can improve in the docs.

So I think the docs need two things.  First, a brief high-visibility note in the backup/restore docs indicating that it involves only server-side juju state (and not client-side or charms).  Second a clear note somewhere around the point that new users are instructed to use `juju init` telling them that the contents of .juju (or just .juju/environments.yaml) are essential to interacting with juju and they should keep it backed up.  A similar note could probably go in a few other related places too (e.g. the init doc).

**Comment by evilnick** [comment]
I take the point that we should encourage users to back up .juju as well. 
Currently though, the backup docs do quite clearly reference only the state server and make no mention of backing up anything other than that, so I don't believe it is misleading in that way.

I propose a solution to this is to add some text to the same document about backing up the client environment (as far as that can feasibly be done). The page itself should probably be moved to the "using juju" section now it doesn't rely on a plugin

**Comment by ericsnowcurrently** [comment]
Sounds good.  Thanks!

**Comment by gemagomez** [comment]
Please, emphasize that if they lose the client machine they will lose all ability to log into their environment and use it. So it effectively leaves them without deployment. It is like losing the keys to your car and nobody being able to let you in. I think this needs to be put in a very visible place.
