### ISSUE TITLE
Charm writing needs new examples

### ISSUE THREAD

**Issue by evilnick** [juju/docs#315]
specifically:
- [ ] simple python charm
- [ ] advanced python charm using helpers (possibly OpenStack?)
- [ ] a.n. other language (Ruby? )

**Comment by AdamIsrael** [comment]
We're deliberately only showing an example of writing layered charms with Python 3, as a best practice. We might want to clarify that it's possible to write charms in other languages, or without the layered framework, but that's best demonstrated elsewhere (in people's blog post, if they're passionate about alternative ways of writing charms).

I recommend we close this issue, and someone can open a new one if they'd like better docs for the current example.
