### ISSUE TITLE
Using Juju locally (lxd): instructions in guide are broken

### ISSUE THREAD

**Issue by bryden** [juju/docs#3158]
The step-by-step instructions in the documentation for _Using Juju locally (lxd)_ are broken.
https://docs.jujucharms.com/2.4/en/tut-lxd

Specifically, after running `juju bootstrap localhost lxd-test` we are presented with an error that is difficult to troubleshoot:

> juju bootstrap localhost lxd-test
> ERROR Get https://10.66.59.1:8443/1.0: Unable to connect to: 10.66.59.1:8443

I've tested this on two machines, both are Ubuntu 18.04 (Bionic).

**Comment by mitechie** [comment]
What's the 130 on the end of the command for? 

This looks like you might have had the lxd deb installed but moved to the snap. Can you make sure that you've apt purge lxd lxd-client ?

**Comment by bryden** [comment]
Sorry about the 130 that's just display from a zsh plugin it's not input.

I only used snap for juju as per the documentation. I ran `sudo apt install lxd zfsutils-linux` as per the docs as well.

I've tried running `sudo apt remove lxd zfsutils-linux --purge` previously and attempting to run through the documentation again with no luck.

**Comment by mitechie** [comment]
Ok, can you please file a bug on bugs.launchpad.net/juju with details of what version of Ubuntu you're on and the steps you ran through? It appears that your lxd isn't running but if you followed the tutorial it should be ok so we'll have to see what's not right there. 

I'd be curious if a:
lxd activateifneeded --debug has anything helpful in the output as well to note why it might not be running.

**Comment by bryden** [comment]
Your intuition about moving to the snap was right. This time I not only ran `sudo apt remove lxd zfsutils-linux --purge` but also `sudo snap remove lxd` for. After running both of those, and `sudo snap remove juju`, I was able to get this to work following the instructions.

I had docker installed already, I'm not sure if that relies on lxd or not, but I do believe I must have installed _something_ that included installing an lxd snap since I never ran that command myself. I'll try a fresh 18.04 install in a VM and run through the documentation one more time. If that fails, I'll open a new ticket and reference this one.

**Comment by pmatulis** [comment]
This page should probably be updated to have LXD installed by snap.
