### ISSUE TITLE
All docs pages should have metadata titles

### ISSUE THREAD

**Issue by evilnick** [juju/docs#317]
as part of #81 

- [ ]  about-juju.md
- [ ]  actions.md
- [ ]  authors-charm-actions.md
- [ ]  authors-charm-best-practice.md
- [ ]  authors-charm-components.md
- [ ]  authors-charm-config.md
- [ ]  authors-charm-hooks.md
- [ ]  authors-charm-icon.md
- [ ]  authors-charm-interfaces.md
- [ ]  authors-charm-metadata.md
- [ ]  authors-charm-policy.md
- [ ]  authors-charm-store.md
- [ ]  authors-charm-upgrades.md
- [ ]  authors-charm-writing.md
- [ ]  authors-hook-debug-dhx.md
- [ ]  authors-hook-debug.md
- [ ]  authors-hook-environment.md
- [ ]  authors-hook-errors.md
- [ ]  authors-implicit-relations.md
- [ ]  authors-interfaces.md
- [x]  authors-intro.md
- [ ]  authors-relations-in-depth.md
- [ ]  authors-service-config.md
- [ ]  authors-subordinate-services.md
- [ ]  authors-testing.md
- [ ]  charm-review-process.md
- [ ]  charms-bundles.md
- [ ]  charms-config.md
- [ ]  charms-constraints.md
- [ ]  charms-deploying.md
- [ ]  charms-destroy.md
- [ ]  charms-environments.md
- [ ]  charms-exposing.md
- [ ]  charms-ha.md
- [ ]  charms.md
- [ ]  charms-relationships.md
- [ ]  charms-relations.md
- [ ]  charms-scaling.md
- [ ]  charms-service-groups.md
- [ ]  charms-upgrading.md
- [ ]  charms-working-with-units.md
- [ ]  charm-unmaintained-process.md
- [ ]  commands.md
- [ ]  config-aws.md
- [ ]  config-azure.md
- [ ]  config-digitalocean.md
- [ ]  config-general.md
- [ ]  config-hpcloud.md
- [ ]  config-joyent.md
- [ ]  config-local.md
- [ ]  config-LXC.md
- [ ]  config-maas.md
- [ ]  config-manual.md
- [ ]  config-onlinelabs.md
- [ ] config-openstack.md
- [ ] config-vagrant.md
- [ ] contributing.md
- [ ] getting-started-keygen-win.md
- [x]  getting-started.md
- [ ] glossary.md
- [ ]  howto-authorised-keys.md
- [ ]  howto-backup-restore.md
- [ ]  howto-gui-management.md
- [ ]  howto-harvesting.md
- [ ] howto-highavailability.md
- [ ]  howto.md
- [ ] howto-node.md
- [ ] howto-offline-charms.md
- [ ] howto-privatecloud.md
- [ ]  howto-proxies.md
- [ ] howto-rails.md
- [ ]  howto-vagrant-workflow.md
- [ ] interface-mysql.md
- [ ]  juju-ha.md
- [ ]  reference-constraints.md
- [ ] reference-environment-variables.md
- [ ]  reference-release-notes.md
- [ ]  reference-releases.md
- [ ] reference-reviewers.md
- [ ]  tools-amulet.md
- [ ] tools-charm-helpers.md
- [ ] tools-charm-tools.md
- [ ]  troubleshooting.md
- [ ] write-charms.md

**Comment by evilnick** [comment]
- [ ]  about-juju.md
- [ ]  actions.md
- [ ]  authors-charm-actions.md
- [ ]  authors-charm-best-practice.md
- [ ]  authors-charm-components.md
- [ ]  authors-charm-config.md
- [ ]  authors-charm-hooks.md
- [ ]  authors-charm-icon.md
- [ ]  authors-charm-interfaces.md
- [ ]  authors-charm-metadata.md
- [ ]  authors-charm-policy.md
- [ ]  authors-charm-store.md
- [ ]  authors-charm-upgrades.md
- [ ]  authors-charm-writing.md
- [ ]  authors-hook-debug-dhx.md
- [ ]  authors-hook-debug.md
- [ ]  authors-hook-environment.md
- [ ]  authors-hook-errors.md
- [ ]  authors-implicit-relations.md
- [ ]  authors-interfaces.md
- [ ]  authors-intro.md
- [ ]  authors-relations-in-depth.md
- [ ]  authors-service-config.md
- [ ]  authors-subordinate-services.md
- [ ]  authors-testing.md
- [ ]  charm-review-process.md
- [ ]  charms-bundles.md
- [ ]  charms-config.md
- [ ]  charms-constraints.md
- [ ]  charms-deploying.md
- [ ]  charms-destroy.md
- [ ]  charms-environments.md
- [ ]  charms-exposing.md
- [ ]  charms-ha.md
- [ ]  charms.md
- [ ]  charms-relationships.md
- [ ]  charms-relations.md
- [ ]  charms-scaling.md
- [ ]  charms-service-groups.md
- [ ]  charms-upgrading.md
- [ ]  charms-working-with-units.md
- [ ]  charm-unmaintained-process.md
- [ ]  commands.md
- [ ]  config-aws.md
- [ ]  config-azure.md
- [ ]  config-digitalocean.md
- [ ]  config-general.md
- [ ]  config-hpcloud.md
- [ ]  config-joyent.md
- [ ]  config-local.md
- [ ]  config-LXC.md
- [ ]  config-maas.md
- [ ]  config-manual.md
- [ ]  config-onlinelabs.md
- [ ] config-openstack.md
- [ ] config-vagrant.md
- [ ] contributing.md
- [ ] getting-started-keygen-win.md
- [ ]  getting-started.md
- [ ] glossary.md
- [ ]  howto-authorised-keys.md
- [ ]  howto-backup-restore.md
- [ ]  howto-gui-management.md
- [ ]  howto-harvesting.md
- [ ] howto-highavailability.md
- [ ]  howto.md
- [ ] howto-node.md
- [ ] howto-offline-charms.md
- [ ] howto-privatecloud.md
- [ ]  howto-proxies.md
- [ ] howto-rails.md
- [ ]  howto-vagrant-workflow.md
- [ ] interface-mysql.md
- [ ]  juju-ha.md
- [ ]  reference-constraints.md
- [ ] reference-environment-variables.md
- [ ]  reference-release-notes.md
- [ ]  reference-releases.md
- [ ] reference-reviewers.md
- [ ]  tools-amulet.md
- [ ] tools-charm-helpers.md
- [ ] tools-charm-tools.md
- [ ]  troubleshooting.md
- [ ] write-charms.md

**Comment by ns950** [comment]
Submitted a pull request with my stab at this.
