### ISSUE TITLE
Example does not work: debug-log -n +1

### ISSUE THREAD

**Issue by bac** [juju/docs#318]
The example given on https://jujucharms.com/docs/1.21/authors-hook-debug for starting debug-log from the first line does not work on 1.21 or 1.22:

$ juju --version
1.21.1-trusty-amd64
$ juju debug-log -n +1
error: invalid value "+1" for flag -n: strconv.ParseUint: parsing "+1": invalid syntax

**Comment by evilnick** [comment]
cool, I didn't see any changes to that in the release notes - any idea how to get the desired behaviour now?

**Comment by evilnick** [comment]
Cool, well, I have discovered the issue - the parameters passed to tail have been subtly changed sometime during 1.20.
