### ISSUE TITLE
missing hooks on "Charm hooks" page

### ISSUE THREAD

**Issue by ericsnowcurrently** [juju/docs#319]
(https://jujucharms.com/docs/1.20/authors-charm-hooks)

The "/hooks" doc needs newer hooks added.  Actions is missing.  I don't know if there are others.

**Comment by evilnick** [comment]
I think this is already addressed by another bug, but I will leave this here until i confirm.

N.B., actions weren't in 1.20, which is the version of docs currently being shown as default
