### ISSUE TITLE
juju trace logging example typo

### ISSUE THREAD

**Issue by gmeszaros** [juju/docs#3193]
https://docs.jujucharms.com/2.4/en/troubleshooting-logs#agent-logging-override
In the example the line:
  LOGGING_OVERRIDE=juju=trace
should be
  LOGGING_OVERRIDE: juju=trace

Otherwise the agent fails upon restart.

**Comment by mitechie** [comment]
Thanks for the correction. I've updated it.

**Comment by pmatulis** [comment]
I've backported this to devel, 2.4, and 2.3.
