### ISSUE TITLE
Docs needed: Authenticating external users

### ISSUE THREAD

**Issue by jamesbeedy** [juju/docs#3203]
We have a discourse post on this [0] and an issue on juju-gui here [1].

@mitechie's post on his blog (god bless his soul) referenced in the discourse issue is all we have documenting 
 the use of some of these options. We need formal docs on the process for the production controller scenarios bad, including identity/candid example config (frequent questions around this).

[0] https://discourse.jujucharms.com/t/options-for-production-controllers/187
[1] https://github.com/juju/juju-gui/issues/3887

**Comment by pmatulis** [comment]
I'm going to actually remove what coverage we do have in this regard as it is entirely insufficient.
