### ISSUE TITLE
charm snap install missing --classic

### ISSUE THREAD

**Issue by hatched** [juju/docs#3226]
https://docs.jujucharms.com/2.4/en/tools-charm-tools

![screen shot 2018-12-07 at 9 48 54 am](https://user-images.githubusercontent.com/532033/49657453-543f1180-fa05-11e8-92f5-ccc5fbde4525.png)
![screen shot 2018-12-07 at 9 49 19 am](https://user-images.githubusercontent.com/532033/49657475-6325c400-fa05-11e8-8bdf-a5e94a3faa41.png)

**Comment by hatched** [comment]
https://github.com/juju/charm-tools/issues/415

**Comment by pmatulis** [comment]
Yeah, I noticed this myself just yesterday. I'll fix it up now.

**Comment by pmatulis** [comment]
Closed via #3227.
