### ISSUE TITLE
Add two more "txn" controller configuration options

### ISSUE THREAD

**Issue by pmatulis** [juju/docs#3255]
As per https://github.com/juju/juju/pull/9594, keys `prune-txn-sleep-time` and `prune-txn-query-count` are being added.

**Comment by pmatulis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add two more txn options](https://trello.com/c/F05BX0Zq/930-add-two-more-txn-options)

**Comment by jameinel** [comment]
Both parameters are used to tune how aggressive our automatic transaction pruning is done.
You can see comments in the code about what the parameters do:
https://github.com/juju/juju/pull/9594/files#diff-330f8f50a671c5dde044bd4bcbc45c6dR140
https://github.com/juju/juju/pull/9594/files#diff-330f8f50a671c5dde044bd4bcbc45c6dR204

prune-txn-sleep-time tells the worker thread to do nothing for X time in between batches. It supports syntax such as "100ms" as the duration.
prune-txn-query-count changes how many transactions we will evaluate at a time (defaulting to 1000). 

Changing these parameters is considered advanced usage, so probably should not be done arbitrarily.


Also, we should note that if we have existing documents about max-prune-txn-batch-size, and max-prune-txn-passes those parameters are now deprecated.
https://github.com/juju/juju/pull/9594/files#diff-330f8f50a671c5dde044bd4bcbc45c6dR129
https://github.com/juju/juju/pull/9594/files#diff-330f8f50a671c5dde044bd4bcbc45c6dR134
