### ISSUE TITLE
Interface Layers missing referenced Communication Scopes

### ISSUE THREAD

**Issue by AdamIsrael** [juju/docs#3274]
The [Interface Layers](https://docs.jujucharms.com/2.4/en/developer-layers-interfaces) documentation has a navigation hyperlink for [Communication Scopes](https://docs.jujucharms.com/2.4/en/developer-layers-interfaces#communication-scopes), but no such target exists on the page. In fact, there's no mention of scope anywhere on the page aside from the navigation.

**Comment by pmatulis** [comment]
Is this issue about the broken links (I found a second one just under) or about the lack of content? Probably both?

I'm not an expert on this but what is meant by "scope"? This [page](https://docs.jujucharms.com/2.4/en/authors-relations-in-depth) mentions the term.
