### ISSUE TITLE
Mismatch in documentation commands and VagrantFile location for genghisapp charm.

### ISSUE THREAD

**Issue by zetas** [juju/docs#333]
Following the documentation here: https://jujucharms.com/docs/1.20/config-vagrant it instructs you to create the VagrantFile in ~/vagrant however in these docs https://jujucharms.com/docs/1.20/howto-vagrant-workflow it tells you to put it in ~/vagrant/charms instead. This mismatch leads to confusion when trying to deploy the genghisapp charm. The command the second set of docs tells you to use is: juju deploy --repository=/vagrant local:trusty/genghisapp yet that won't work, it says: no such charm. Instead you need to provide the proper path like so: juju deploy **--repository=/vagrant/charms** local:trusty/genghisapp

**Comment by evilnick** [comment]
thanks, i will check into this!
