### ISSUE TITLE
[2.4] ERROR unrecognized command: juju set-series Edit

### ISSUE THREAD

**Issue by mitechie** [juju/docs#3349]
migrated from https://bugs.launchpad.net/juju/+bug/1814578

[Impact]

While following the documentation on "Update the series of a controller or machine" (https://docs.jujucharms.com/2.4/en/howto-updateseries ) says that "juju set-series" should be used change the default series for an application, while the command available is "juju update-series"

[Test Case]

$ juju --version
2.4.7-cosmic-amd64
$ juju bootstrap snowspeeder
Creating Juju controller "snowspeeder-snowspeeder" on snowspeeder/snowspeeder
Looking for packaged Juju agent version 2.4.7 for amd64
To configure your system to better support LXD containers, please see: https://github.com/lxc/lxd/blob/master/doc/production-setup.md
Launching controller instance(s) on snowspeeder/snowspeeder...
 - juju-e37f8f-0 (arch=amd64)
Installing Juju agent on bootstrap instance
Fetching Juju GUI 2.14.0
Waiting for address
Attempting to connect to 192.168.10.11:22
Connected to 192.168.10.11
Running machine configuration script...
Bootstrap agent now started
Contacting Juju controller at 192.168.10.11 to verify accessibility...
Bootstrap complete, "snowspeeder-snowspeeder" controller now available
Controller machines are in the "controller" model
Initial model "default" added
$ juju deploy --series xenial cs:ubuntu
Located charm "cs:ubuntu-12".
Deploying charm "cs:ubuntu-12".
 ~ $ juju status
Model Controller Cloud/Region Version SLA Timestamp
default snowspeeder-snowspeeder snowspeeder/snowspeeder 2.4.7 unsupported 15:33:05-03:00

App Version Status Scale Charm Store Rev OS Notes
ubuntu 16.04 active 1 ubuntu jujucharms 12 ubuntu

Unit Workload Agent Machine Public address Ports Message
ubuntu/0* active idle 0 192.168.10.10 ready

Machine State DNS Inst id Series AZ Message
0 started 192.168.10.10 juju-5ec3d8-0 xenial Running

$ juju set-series ubuntu bionic
ERROR unrecognized command: juju set-series
$ juju set-series --help
ERROR unrecognized command: juju set-series
$ juju help commands | grep series
update-series Update an application or machine's series.
$ juju update-series ubuntu bionic
$ echo $?
0

**Comment by pmatulis** [comment]
Closed via #3359
