### ISSUE TITLE
Document the meaning and difference between remove-, destroy-, and kill- prefixes

### ISSUE THREAD

**Issue by johnsca** [juju/docs#3353]
These three prefixes have very precise and useful meanings in Juju, but the distinction is not immediately obvious from an outside perspective.   They should be called out explicitly on the Concepts and Terms page.

We might also want to call out list- vs show- and the fact that there are common aliases for the list- commands.

**Comment by pmatulis** [comment]
Thanks. I will probably include this into an upcoming "Basic client usage" tutorial.

**Comment by johnsca** [comment]
@pmatulis Please take a look at the PR linked above.  Feedback on that would be appreciated.
