### ISSUE TITLE
Doc Example for cloudinit-userdata.

### ISSUE THREAD

**Issue by manadart** [juju/docs#3354]
As mentioned in [this](https://discourse.jujucharms.com/t/using-model-config-key-cloudinit-userdata/512) thread, docs lack an explicit example of setting `cloudinit-userdata`. Though that post will eventually become documentation...

**Comment by afreiberger** [comment]
The cloudinit-userdata.yaml template in the example provided is missing a | after "cloudinit-userdata:" to denote the following yaml is actually a multi-line string.  The example output is correct with the |- trailing the key to denote the multi-line value.
