### ISSUE TITLE
"Getting Started" JUJU_REPOSITORY clarification 

### ISSUE THREAD

**Issue by sabaini** [juju/docs#3366]
https://docs.jujucharms.com/2.4/en/developer-getting-started advises setting up the JUJU_REPOSITORY env var, but there's no context around that. 

Instead the reference at https://docs.jujucharms.com/2.4/en/reference-environment-variables says it's deprecated and/or dysfunctional in current Jujus

**Comment by pmatulis** [comment]
It looks to me like the instructions merely use JUJU_REPOSITORY as a benign helper variable to set up a directory structure. @sabaini is that your conclusion as well?

**Comment by sabaini** [comment]
@pmatulis I /think/ so? -- just found it confusing that elsewhere that env var was being documented as deprecated. I'd suggest to rename that helper variable maybe

**Comment by pmatulis** [comment]
Done in https://discourse.jujucharms.com/t/getting-started-with-charm-development/1118
