### ISSUE TITLE
status of legacy proxy settings is unclear

### ISSUE THREAD

**Issue by dannf** [juju/docs#3406]
In the "List of model keys" section, the (what I now know to be) legacy and non-legacy (juju-*) proxy settings have descriptions that appear to be mutually exclusive. In my reading, the legacy options are for configuring proxies for new instances (presumably via /etc/environment or similar), while the juju- ones are used by charms. But, if I try to use both together, I get the error:

"ERROR cannot specify both legacy proxy values and juju proxy values"

This is the first I've heard that the {ftp,http,https,no}-proxy options are legacy options, and it isn't clear in what circumstances I should use the legacy vs. the juju-* style.

I delved into the git history, and found this commit which clarifies things in the comments:
1147bafd67 Handle both legacy proxy and new juju proxy values in model config. Environment set correctly for units.

After reading through that I now believe I understand that the legacy options were implemented using a sledge hammer, and are maintained for backwards compatibility. But the new style provides the proxy info to the charm and relies on the charm to have the knowledge to DTRT. Could we make that info available in the docs?

**Comment by pmatulis** [comment]
@dannf Hi, thanks for this feedback. In the left menu, the proxy stuff is explained under 'Networking' > 'Working offline'. Specifically:

https://docs.jujucharms.com/2.5/en/charms-offline-strategies

Let me know if that is insufficient. If it is, please provide me with what you would like added (or removed). Perhaps insert a link from the table page to the above page.

**Comment by dannf** [comment]
@pmatulis Thanks for the quick reply. I hadn't read that section before, but it does seem to clarify things. However, I didn't think to look under "offline" content for proxy information, because I don't consider going through a proxy to be an "offline" use case, just a modified online one. Would it be possible to link to the proxy info in the "offline" section from the "model keys" section?

**Comment by pmatulis** [comment]
@dannf Yes, there isn't much room to work with in that table (and I would need to add a link for each key) but I think that's the best way forward. Thanks again for your feedback.

**Comment by pmatulis** [comment]
Done in https://discourse.jujucharms.com/t/offline-mode-strategies/1071
