### ISSUE TITLE
404 to tutorial about hooks

### ISSUE THREAD

**Issue by erik78se** [juju/docs#3413]
In  https://github.com/juju/docs/blob/2.5/src/en/authors-charm-hooks.md

There is a reference to a tutorial on hooks. A basic concept in juju charming.

Its really nasty that this is a 404. It should lead to a tutorial that is for hooks to help beginners learn juju.

**Comment by pmatulis** [comment]
@erik78se Hi, so links on those GitHub source pages will always be broken. The file is below. I'm not sure how up to date it is however.

https://docs.jujucharms.com/2.5/en/authors-charm-writing

**Comment by erik78se** [comment]
Weird, it was broken when I tried it even on the https://docs.jujucharms.com/2.5/en/authors-charm-writing

But its working now?! I just looked it up for the purpose of the issue...

It can be closed since it seems to work now.

**Comment by pmatulis** [comment]
Yes, it sounds odd! I will close.
