### ISSUE TITLE
"Removing things" page should include bundles

### ISSUE THREAD

**Issue by mlda065** [juju/docs#3460]
I deployed a bundle with

```
juju deploy file.yaml --debug
```

Now I want to uninstall/remove/destroy/whatever that bundle, to free up those resources.

The [Removing things](https://docs.jujucharms.com/2.5/en/charms-destroy) page  lists how to remove:

* controllers
*  models
*  storage
*  applications
* machines
* relations
* storage
* units
* users

But it doesn't say how to remove a bundle.

Similarly, the [Bundle page](https://docs.jujucharms.com/2.5/en/charms-bundles) doesn't say how to remove a bundle.

I assume it must be possible to remove a bundle. (Otherwise there's no point in bundles existing as a concept.) But I cannot find it in the docs, or `juju --help`.

**Comment by mitechie** [comment]
Thanks for the report. Unfortunately bundles are not model entities. You deploy a bundle and it's unpacked into the model. Models evolve over time and as soon as you change a config value, add-unit, relate something the question arises as to "what is the bundle" any more. 

We encourage folks to use models to group related work and so it might be that you'd just destroy the model and create a new one if you're done testing something specific to a bundle. In this way you get a clean canvas for your next run and there's no assuming of what the user is wanting for us to process. 

Let me know if you have any questions/concerns around this and if using multiple models doesn't assist you in what you're looking to do.

**Comment by pmatulis** [comment]
@mlda065 FYI, I updated the documentation [here](https://discourse.jujucharms.com/t/removing-things/1063#heading--removing-bundles).
