### ISSUE TITLE
GUI docs should state how to install GUI

### ISSUE THREAD

**Issue by mdavis-xyz** [juju/docs#3461]
I was looking at [this page](https://docs.jujucharms.com/2.5/en/controllers-gui).

> To view the URL and login credentials for the GUI, use the following command:
>
>     juju gui

But when I try to run that I see

```
$ juju gui
ERROR Juju GUI is not available: Juju GUI not found
```

The docs should say how to install the GUI. (Also the error message should say that too.)

The docs say:

> The GUI comes with every controller providing the controller was not created with the `--no-gui` option

I don't think that's true. It obviously didn't come with my controller, and I didn't use `--no-gui`.

**Comment by mitechie** [comment]
What version of Juju are you using? It wasn't baked into 1.25 but from 2.0 onward it's build in and downloaded as part of boostrap.

**Comment by hatched** [comment]
@mitechie is correct, however it's possible that there was an issue downloading the GUI on bootstrap and the error messaging around that might have been lacking.

If you'd like to get a GUI going on that controller you can try the following:
- Download the latest release https://github.com/juju/juju-gui/releases/download/2.14.1/jujugui-2.14.1.tar.bz2
- `juju upgrade-gui path/to/jujugui-2.14.1.tar.bz2`
- Wait a few moments after the upload completes for it to uncompress and start serving.
- `juju gui`

**Comment by mlda065** [comment]
I'm using version 2.5.2

**Comment by mlda065** [comment]
The bootstrap claimed to finish successfully. I saw no errors.

That said, I am unable to deploy anything successfully.

**Comment by hatched** [comment]
Were you able to add a GUI using the above mentioned steps?

**Comment by mlda065** [comment]
Yes. That worked. Now I'm writing a pull request to add those steps to the docs.

**Comment by hatched** [comment]
Glad to hear it.

It sounds like there was an issue downloading the GUI during bootstrap, we'll have to make that more resilient to failure and to output some messaging if it fails.

**Comment by mlda065** [comment]
Maybe I can try it again and paste the logs here?

How do I unbootstrap?

**Comment by hatched** [comment]
https://docs.jujucharms.com/2.5/en/charms-destroy#destroying-controllers
