### ISSUE TITLE
Redirect loop in docs

### ISSUE THREAD

**Issue by mhilton** [juju/docs#3487]
At least http://docs.jujucharms.com/charm-writing is currently inaccessible due to a redirect loop. The pages are constantly redirecting between http://docs.jujucharms.com/charm-writing and http://docs.jujucharms.com/charm-writing-guide/1260.

**Comment by pmatulis** [comment]
@mhilton Hi, yes, the problem is known and web team is working on it.

**Comment by pmatulis** [comment]
@mhilton Looks good here. Can you confirm on your end?

**Comment by nottrobin** [comment]
Thanks for reporting this. This is now fixed in https://github.com/canonical-web-and-design/docs.jujucharms.com/commit/6e6f95aa899eebec55701f465bb4a90762e93a8a
