### ISSUE TITLE
Cross model relations scenario 2 is out of date

### ISSUE THREAD

**Issue by jamonation** [juju/docs#3491]
The example in https://docs.jujucharms.com/cmr-scenario-2 does not work. When deploying MySQL, the charm defaults to zesty. Specifically this line is the issue:

`juju deploy mysql`

Using that with no arguments results in a juju status like this:

```
Unit     Workload  Agent       Machine  Public address  Ports  Message
mysql/0  waiting   allocating  0                               waiting for machine

Machine  State  DNS  Inst id  Series  AZ  Message
0        down        pending  zesty       no matching agent binaries available
```

The document should be updated with either a different charm/example, or with a flag to force the series, e.g.:

`juju deploy mysql --series boinic --force`

**Comment by pmatulis** [comment]
@jamonation Thank you for this. The document will be reviewed.
