### ISSUE TITLE
No way to jump between doc versions

### ISSUE THREAD

**Issue by relaxdiego** [juju/docs#3493]
Currently, https://docs.jujucharms.com refers to documentation for 2.6.x...probably. It's hard to tell since it doesn't say on the left hand side for which version these docs are for.

On the other hand, to get to older documentation, one has to jump to https://old-docs.jujucharms.com but when you're there, there's no obvious way to get to the more recent version.

Apart from that, the old docs do not have a warning at the top indicating that the reader is viewing old documentation.

Compare that to kubernetes documentation for 1.12 which shows in clear bold text that the reader is viewing an old doc that is no longer maintained: https://v1-12.docs.kubernetes.io/docs/home/?path=users&persona=app-developer&level=foundational

And when you happen to be viewing the latest doc version, it's very easy to switch to the old version via the drop-down menu on the top-right corner of the page: https://kubernetes.io/docs/home/

**Comment by howbazaar** [comment]
Hi @relaxdiego, thanks for the feedback.

This is a consious design choice at this stage. The docs at  https://docs.jujucharms.com do in fact refer to the current version. We are trying to make the docs more relevant across versions. We are tagging newer features or aspects with "Introduced in 2.6.0" or similar.

The intent is to have the docs split over major version numbers. When Juju 3.0 comes along, there will be options to jump between 2.x and 3.x docs.

**Comment by relaxdiego** [comment]
Thanks @howbazaar.

> This is a conscious design choice at this stage.

Just so I understand this part correctly: are you saying it was a conscious decision to not have an explicit way to jump between old and current document versions? (i.e. 2.4 <--> 2.5 <--> 2.6 <--> dev)

**Comment by mitechie** [comment]
Yes, this is the decision. We're working to simplify and if something is version specific call it out in the document as required.

**Comment by relaxdiego** [comment]
Thanks for clarifying, @mitechie. I don't agree with it but I will respect your team's decision. :-)
