### ISSUE TITLE
Juju docs missing heading anchors 

### ISSUE THREAD

**Issue by szeestraten-ntnu** [juju/docs#3494]
There are no heading anchors so one can link to specific parts of the documentation.

See for example: https://docs.jujucharms.com/charm-bundles

**Comment by pmatulis** [comment]
@szeestraten This should work:

https://docs.jujucharms.com/charm-bundles#heading--using-YAML-anchors-and-aliases

Do you mean there is no obvious way to obtain the above? If so, then what you filed [here]( https://github.com/CanonicalLtd/jujucharms.com/issues/516) is what we should be looking at. I will try to get some traction on this as I realise the usability impact is not insignificant.

**Comment by szeestraten** [comment]
Hi @pmatulis, yes, clicking the header as usual would be a step up.

If the other issue can cover all the docs pages and not just the command reference, then feel free to close this one.

Apologies for the double up. I forgot the other issue still was open.

**Comment by pmatulis** [comment]
I'm pushing to get this looked at (the general case; not just the command page) and I received a promising acknowledgement. I'll close this one. Thanks for bringing this up again.
