### ISSUE TITLE
Broken link to commands reference

### ISSUE THREAD

**Issue by IwanVosloo** [juju/docs#3501]
Hi there. On the Juju.is website, there's a broken link.

On https://juju.is/docs, the link on the left menu under Reference >> For Juju administrators >> Commands links to https://juju.is/docs/commands which does not exist.

**Comment by timClicks** [comment]
Thanks for notifying us of this Iwan.

**Comment by timClicks** [comment]
Hi again @IwanVosloo. https://juju.is/docs/commands should now be live for you.

I'll close this issue now. Feel free to comment if it should be re-opened.
