### ISSUE TITLE
Broken links in "working offline" section in JUJU docs on both jaas.ai and juju.is sites.

### ISSUE THREAD

**Issue by alexdodson** [juju/docs#3512]
Hello,

I am going through the documentation trying to find network requirements outbound for juju charm upgrades etc. I went to the working offline section and I hit the following links that are broken. Both jaas.ai and juju.is link to the same pages.

https://juju.is/t/offline-mode-strategies/1071
https://juju.is/t/configuring-juju-for-offline-usage/1068
https://juju.is/t/deploying-charms-offline/1069
https://juju.is/t/installing-snaps-offline/1179
https://juju.is/t/using-the-localhost-cloud-offline/1070

**Comment by jkfran** [comment]
All these broken links shouldn't be present anymore after https://github.com/canonical-web-and-design/juju.is/pull/174
