### ISSUE TITLE
using-lxd-clustering-with-juju: dead link

### ISSUE THREAD

**Issue by toby63** [juju/docs#3514]
Related to: https://discourse.charmhub.io/t/using-lxd-clustering-with-juju/1091

In the section `Forming a LXD cluster`, you use a dead link:

> The documentation provided by the LXD project explains the process of forming a LXD cluster 20(https://lxd.readthedocs.io/en/latest/clustering/).

The documentation is now here:
https://linuxcontainers.org/lxd/docs/master/clustering

**Comment by juanmanuel-tirado** [comment]
Fixed.
