### ISSUE TITLE
Images on the juju.is docs website fail to open upon click

### ISSUE THREAD

**Issue by izmalk** [juju/docs#3518]
Images should open a full-size version when clicked on.
Some images on the docs website fail to open.

![Screenshot from 2024-07-03 19-34-25](https://github.com/juju/docs/assets/48120135/2e4fd723-399e-4ae7-bd7e-b7c72411f3ec)

There are many affected images, for example:

-  the first image on the page [charm-lifecycle](https://juju.is/docs/sdk/charm-lifecycle)

- the first image on the [first page](https://juju.is/docs/juju )

- all images on the [tutorial](https://juju.is/docs/juju/tutorial) pages

The same images can be seen in full size if clicked in Discourse.

**Comment by tmihoc** [comment]
I've run into this issue as well. It's about the URL. The web team is aware of this (though not sure to what extent they're prioritizing this). FWIW if you click on ignore that will show you the diagrams.

**Comment by tmihoc** [comment]
I believe this has now been fixed.
