### ISSUE TITLE
Documentation: Set up your development environment

### ISSUE THREAD

**Issue by mathmarchand** [juju/docs#3524]
Docs page: https://juju.is/docs/sdk/dev-setup

Docs source: https://discourse.charmhub.io/t/set-up-your-development-environment/4450

Issue: The current mount command will prevent creating virtual environment from the VM into the mounted path. If you try to use the tox command, it will fails.  If mounted while using type=native, it will work correctly:
```
mulitpass stop charm-dev-vm
multipass mount --type native ~/my-charm charm-dev-vm:~/my-charm
multipass start charm-dev-vm
```
Ref: https://github.com/canonical/multipass/issues/3620 
Note: I only tested from Ubuntu Desktop 24.04.1 using multipass version 1.14.0

**Comment by tmihoc** [comment]
Thanks for catching this, and for also suggesting a fix. I've updated the doc according to your suggestion. Do you by any chance have a Discourse handle? If you're okay with it, I'd like to add you to the list of contributors on the bottom of the doc.

**Comment by mathmarchand** [comment]
Yes, I do, it's @mathmarchand. 

Regards,

**Comment by tmihoc** [comment]
Added your handle. But the Charmhub Discourse doesn't recognize it, so it doesn't link to anything: https://discourse.charmhub.io/t/set-up-your-development-environment/4450 (scroll down to the bottom of the doc, the contributors section).
