### ISSUE TITLE
Documentation: How to manage charm resources

### ISSUE THREAD

**Issue by gfouillet** [juju/docs#3534]
Docs page: https://juju.is/docs/sdk/resources

Docs source: https://discourse.charmhub.io/t/how-to-manage-charm-resources/4468

Issue:

There is a typo in the sentence:

> The [fetch()](https://ops.readthedocs.io/en/latest/#ops.Resources.fetch) method will raise a [ModelError](https://ops.readthedocs.io/en/latest/#ops.ModelError) if the resource does not exist, and returns a Python [Path](https://docs.python.org/3/library/pathlib.html#pathlib.Path) object to the resource if it does.

Which should be:

> The [fetch()](https://ops.readthedocs.io/en/latest/#ops.Resources.fetch) method will raise a [NameError](https://docs.python.org/3/library/exceptions.html#NameError) if the resource does not exist, and returns a Python [Path](https://docs.python.org/3/library/pathlib.html#pathlib.Path) object to the resource if it does.

(if we trust both the snippet just above the sentence and the documentation of the [fetch()](https://ops.readthedocs.io/en/latest/#ops.Resources.fetch) method)

**Comment by tmihoc** [comment]
Fixed (and added you to the contributors). Thanks!
