### ISSUE TITLE
Docs should contain reference/guidance for multiplatform charms

### ISSUE THREAD

**Issue by evilnick** [juju/docs#362]
E.g, presumably we want a world with charms which can deploy on any supported platform, rather than different charms for each platform.

we should provide a reference implementation of this in documentation

**Comment by evilnick** [comment]
what I am thinking of here is that we should provide some sort of best practice template for determining which OS the charm is being installed on and act accordingly. I don't know exactly what the best method is? checking /etc/lsb-release perhaps? I am not sure if this is just of relevance to the install hooks, or if it may be useful elsewhere.

**Comment by AdamIsrael** [comment]
I think this is a good issue that needs discussion, but is blocked on first-class support for multi-platform charms in the reactive framework.
