### ISSUE TITLE
Need an example of what an optional relation looks like

### ISSUE THREAD

**Issue by cmars** [juju/docs#371]
Needed to mark relations as optional in the metadata.yaml for a charm I'm writing, didn't see an example of where to declare it optional in the docs.

**Comment by evilnick** [comment]
Like i say, I'm not disputing that this exists, but I don't think it has ever been used for anything, and therefore doesn't need docs. In essence, all relations are optional.
But please get back to me if there is some evidence of a compelling use!

**Comment by marcoceppi** [comment]
All relations are implicitly optional, there is no such thing as a required relation.
