### ISSUE TITLE
top search result page for "upgrade" is just headers.

### ISSUE THREAD

**Issue by jrwren** [juju/docs#379]
https://jujucharms.com/docs/1.21/charms-upgrading is linked as a search result but the page is nonsense, or just headers.

**Comment by evilnick** [comment]
Yup, something has gone wrong with that - it looks like all the content has disappeared, I will check into it

**Comment by petermatulis** [comment]
The charm upgrade stuff is at [authors-charm-upgrades](https://jujucharms.com/docs/stable/authors-charm-upgrades.html). Unless someone object, I'm going to remove [charms-upgrading.md](https://jujucharms.com/docs/stable/charms-upgrading.html).

While I'm at it I'm going to also remove:

- [write-charms.md](https://jujucharms.com/docs/stable/write-charms.html) - correct file: [authors-charm-writing.md](https://jujucharms.com/docs/stable/authors-charm-writing.html)
- [juju-topics.md](https://jujucharms.com/docs/stable/juju-topics.html) - never used

**Comment by evilnick** [comment]
@petermatulis shouldn't this be closed now?

**Comment by petermatulis** [comment]
@evilnick 
I didn't get any feedback and forgot about this one. FWICS, the bottom 2 files are still up.

**Comment by evilnick** [comment]
this was done, at some point
