### ISSUE TITLE
juju retry-provisioning needs docs

### ISSUE THREAD

**Issue by evilnick** [juju/docs#39]
Juju retry-provisioning

You can use the retry-provisioning command in cases where deploying
services, adding units, or adding machines fails. The command allows you
to specify machines which should be retried to resolve errors reported
in status.

For example, after you deployed 100 units and machines, status reports
that machines 3, 27 and 57 could not be provisioned because of a rate
limit exceeded error. You can ask juju to retry:

    juju retry-provisioning 3 27 5

**Comment by petermatulis** [comment]
Ok to put text here?:

charms-deploying.md

**Comment by evilnick** [comment]
yup.
