### ISSUE TITLE
Scaleway doesn't work

### ISSUE THREAD

**Issue by zorrobyte** [juju/docs#390]
How about removing the Scaleway Readme as it's broken?

pip install -U juju-scaleway results in compile errors across 14.04 and 15.04.

**Comment by marcoceppi** [comment]
I don't think just removing them is the right course of action. Fixing it sounds much more appealing :) I attempted an install and it appears juju-scaleway plugin now requires `libffi-dev` `libssl-dev` package.

on Ubuntu `sudo apt-get install libffi-dev libssl-dev`

What platform are you using? What are the error messages you're getting? I'll have the docs updated to reflect this new dependency.

**Comment by zorrobyte** [comment]
Good point!

I was using 14.04 and 14.10, both have the dependency issue.

It would be nice to get https://www.vultr.com/ in there somewhere.

**Comment by marcoceppi** [comment]
Someone would need to create a provider for it. The Scaleway engineers were
nice enough to contribute this plugin provider for Juju. Either yourself or
anyone else who has time to work on something similar for vultr would be
great!

**Comment by zorrobyte** [comment]
I’ll be sure to put in a request with their support, I wish I could be more help writing this.

**Comment by moul** [comment]
cc @edouardb
