### ISSUE TITLE
Add "1.23" docs and update "devel" to 1.24.

### ISSUE THREAD

**Issue by ericsnowcurrently** [juju/docs#405]
It looks like a 1.23 branch was not created when juju 1.23 was released.  The "devel" branch also still refers to 1.23 (e.g. in the release notes).

**Comment by evilnick** [comment]
No, it wasn't, because there was no difference doc-wise, none of the 1.23 features have been fully documented.
The long answer to this is that we (and by that I don't mean me) are just not co-ordinated enough about releases! I will spin off 1.23 when we have at least some of the content ready
