### ISSUE TITLE
Cannot link to release notes or commands

### ISSUE THREAD

**Issue by hatched** [juju/docs#408]
You're unable to link to a specific release note: https://jujucharms.com/docs/stable/reference-release-notes

You're unable to link to a specific command: https://jujucharms.com/docs/stable/commands

**Comment by evilnick** [comment]
yes, this relates to differences in the way we render stuff; I will have to update the markdown plugin to make this work

**Comment by evilnick** [comment]
To clarify, you *can* link to a specific release note or command, there just isn't a little icon to make it easy to copy the link.
