### ISSUE TITLE
Missing bundle deploy methods in GUI

### ISSUE THREAD

**Issue by hatched** [juju/docs#428]
https://jujucharms.com/docs/stable/charms-bundles#deploying-a-bundle-from-the-charm-store-with-the-gui

There are actually four ways to deploy a bundle:
Charmstore: drag token to the canvas, or click the deploy button.
Drag a bundle yaml file to the canvas.
Click the import button in the deployer bar.

**Comment by evilnick** [comment]
is  this a new behaviour - it certainly didn't used to do that?

**Comment by hatched** [comment]
Over a year now :)

**Comment by evilnick** [comment]
Cool, well, thanks for letting us know :)

**Comment by evilnick** [comment]
@degville did we cover all these?

**Comment by degville** [comment]
@evilnick Yes, they're all in the 2.0 doc although I don't think dragging from the Charm Store works any more (and the store covers the canvas almost completely now).

**Comment by evilnick** [comment]
ok, cool
