### ISSUE TITLE
User sections should include screenshots of the GUI for feature equivalents

### ISSUE THREAD

**Issue by marcoceppi** [juju/docs#432]
Trying to explain how to expose a service in the GUI is different than on the CLI. Including screenshots of each of the specific features between CLI and GUI (or explaining them) will go a long way to cut down on repeating instructions

**Comment by hatched** [comment]
I agree this would be nice but as we make continuous UI updates every release we would have to make sure we also updated the various screenshots.

**Comment by evilnick** [comment]
Indeed. I think when we have the time to also write documentation for the GUI, whilst it would be nice to have screenshots in the general Juju docs, how to do things will have to go on a separate page in order to keep it maintainable
