### ISSUE TITLE
maintainer page should give an example of the maintainer field.

### ISSUE THREAD

**Issue by mbruzek** [juju/docs#436]
I ran into a charm review where the author simply listed the email address for the maintainer.  I searched the docs and we don't have an example of what a maintainer field should look like on the page:

https://jujucharms.com/docs/devel/authors-charm-metadata

We should include an example so authors know what to put in this field.

"Charm Author Name &lt;author@email.com&gt;"

**Comment by evilnick** [comment]
Cool. I suppose I shall fix that, as I can spell "maintainer"
:laughing:
