### ISSUE TITLE
Documentation on peers variable

### ISSUE THREAD

**Issue by cholcombe973** [juju/docs#442]
As a new user to juju I'm doing my best to follow the docs.  There seems to be almost no information on what the peers variable does. After some digging I think it relates to cluster units but I'm not sure.  Some more information around this would be very helpful.

**Comment by evilnick** [comment]
Hi, sorry you find it less than helpful - I am a bit confused by what you mean when you say 'peers variable'
If you mean a peer relation, there is some documentation for charm authors here: https://jujucharms.com/docs/devel/authors-relations#peers
Peer relations are made, if specified in the charm's metadata, when there is more than one unit of the charm, which is, as you say, useful for clustering.

**Comment by cholcombe973** [comment]
Oh I must've missed that section of the docs.  Thanks!

**Comment by evilnick** [comment]
No problem - I just recently updated that page to clarify a few things, so for the time being, the best version is in the developer docs until I backport it. Thanks for the feedback anyhow :)
