### ISSUE TITLE
Bundle documentation uses old bundle format

### ISSUE THREAD

**Issue by hatched** [juju/docs#477]
https://jujucharms.com/docs/stable/charms-bundles

**Comment by evilnick** [comment]
cool, I was aware we were working on a new bundle format, but as usual, had no idea it was finalised. If this is the case, are there any pointers to any existing information about it or any examples of its use? All the bundles in the store seem to use the format as described here

**Comment by mitechie** [comment]
This isn't quite bundles 2.0 as we've been talking/planning a lot lately. This is more of a 1.5 revision that was done with the new charmstore. The docs around this we started and were looking for feedback on in the charmstore:

https://github.com/juju/charmstore/blob/v4/docs/bundles.md

These docs are not currently in the Juju docs as they're tied to the version that the charmstore supports.

**Comment by evilnick** [comment]
Ah, okay, thanks for the link @mitechie

**Comment by makyo** [comment]
This is fixed in devel, needs to be ported to stable.

**Comment by evilnick** [comment]
thx, I need to remind @petermatulis to mark stuff for backports!
