### ISSUE TITLE
Mention "image-stream" in howto-privatecloud.

### ISSUE THREAD

**Issue by ericsnowcurrently** [juju/docs#481]
The image metadata section [1] of the private cloud how-to should probably mention the "image-stream" option.  This environments.yaml option isn't very well explained [2], but relevant to the discussion of image metadata in the private cloud how-to.

[1] https://jujucharms.com/docs/stable/howto-privatecloud#image-metadata
[2] The only good info I found was in the "Using daily image streams for faster provisioning" section of the 1.21.1 release notes.

**Comment by evilnick** [comment]
this should be covered by #244 
It is included specifically in https://jujucharms.com/docs/devel/config-general, but yes, it needs more explanation there and elsewhere

**Comment by ericsnowcurrently** [comment]
Sounds good.  I thought it might also be helpful to have a brief mention of it in the image metadata section of private cloud how-to.

**Comment by evilnick** [comment]
I agree :smile:

**Comment by petermatulis** [comment]
Closing this and staying with #244 . Brought over some of the above commentary.
