### ISSUE TITLE
Need to have a 1.24 release of the docs

### ISSUE THREAD

**Issue by marcoceppi** [juju/docs#494]
1.24 is released and there are special things in said release. To avoid bleeding between new devel and 1.24 a release of the docs should be cut and "stable" should point to 1.24 release

**Comment by marcoceppi** [comment]
Closed with no comment or resolution? Still no 1.24 branch?

**Comment by evilnick** [comment]
oh, apologies, I didn't know you meant me to take this seriously. I got a bit confused by the way you triaged it yourself and then assigned people to it. It is also a bit obvious and something that is already, obviously, being worked on

**Comment by marcoceppi** [comment]
It's really not obvious at all and its causing a lot of confusion with users

**Comment by petermatulis** [comment]
This is done. Closing.
