### ISSUE TITLE
Docs needed: troubleshooting juju service

### ISSUE THREAD

**Issue by dhammo** [juju/docs#510]
In juju documentation troubleshooting section there is no mentioning of how to troubleshoot juju it-self. The troubleshooting section only lists what to do if a charm/service/unit has an issue. It is missing guidelines on how to troubleshoot and check if juju is [not] working. For example, what to do if "juju status" cmd hangs and return no results. How to check if juju it-self is healthy and juju service is running or what logs to check.

**Comment by evilnick** [comment]
Yes, this page could do with a lot of extra information, including troubleshooting for different platforms. thanks for reporting it

**Comment by petermatulis** [comment]
Ongoing. PR #588 heading in the right direction.

**Comment by AdamIsrael** [comment]
Some specific things I think we need to cover:

- What are the components of the juju service (mongod and jujud?)
- How do I restart the juju service?
- How do I debug why the juju agent doesn't start on boot of a unit?

**Comment by pmatulis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Troubleshooting juju service](https://trello.com/c/C0VHo5JH/14-troubleshooting-juju-service)
