### ISSUE TITLE
add 1.23 upgrade issue to docs

### ISSUE THREAD

**Issue by evilnick** [juju/docs#539]
Due to a new worker that was added in 1.23, it is likely that the state server agents will be unable to restart when an upgrade of a 1.23 environment is requested.

Manual intervention will be required to unstick the upgrade. On each state server host do the following:
Find the tools directory. 
For the local provider this will be something like ~/.juju/local/tools
For other providers this will be /var/lib/juju/tools
You should see both the old and the new tools listed with a symlink for the machine agent pointing to the old version. For example: 
drwxr-xr-x 2 root root 4096 May 27 21:18 1.23.3.1-trusty-amd64
drwxr-xr-x 2 root root 4096 Jun 16 11:35 1.24.0-trusty-amd64
lrwxrwxrwx 1 root root 21 May 27 21:18 machine-0 ->
1.23.3.1-trusty-amd64

Remove the old symlink, e.g.: sudo rm machine-0
Add one that points to the new tools, e.g.: sudo ln -s 1.24.0-trusty-amd64 machine-0
Kill the machine agent so that it restarts into the new version: sudo pkill jujud

The upgrade will then proceed as normal.

It's regrettable that this is required. Unfortunately but because upgrades themselves get blocked we can't easily offer an upgrade that fixes the problem. 

The root cause was fixed in 1.24.0 so upgrading directly to 1.24.0 or later (skipping 1.23) will avoid the issue.

**Comment by petermatulis** [comment]
What do we want to do here? People don't read documentation before they upgrade, and probably not after encountering such a problem as well.

**Comment by evilnick** [comment]
agreed. it is mentioned in the release notes. as 1.23 is not a supported version, there are probably more urgent things to look at

**Comment by petermatulis** [comment]
I still don't see what there is to do here. It's a software bug.

**Comment by petermatulis** [comment]
Closing this.
