### ISSUE TITLE
Dev vs. stable juju release distinction in commands.md

### ISSUE THREAD

**Issue by sabaini** [juju/docs#556]
commands.md states in the section about upgrade-juju:  "A development version is defined to be any version with an odd minor version or a nonzero build component..."

Is this still true? Rumour from IRC has it that the mapping between even/odd ~= dev/stable is deprecated. If so, that'd be quite unfortunate, as the above docs would lead people (eg., me) to outdated juju versions.

**Comment by evilnick** [comment]
Yes, odd/even numbering no longer has a particular meaning.

however, the commands section of the docs is generated directly from Juju's help text, so the error should be fixed there.

I have filed https://bugs.launchpad.net/juju-core/+bug/1474411

**Comment by evilnick** [comment]
fixed in core
