### ISSUE TITLE
More info required on juju-log

### ISSUE THREAD

**Issue by pmatulis** [juju/docs#573]
Pursuant to #217

**Comment by petermatulis** [comment]
http://manpages.ubuntu.com/manpages/quantal/man1/juju-log.1.html

**Comment by evilnick** [comment]
wow, that is a seriously out of date man page

**Comment by petermatulis** [comment]
I'm not good enough at reading code as I would like to be but is there any other alternative?

**Comment by evilnick** [comment]
@petermatulis alternative to what?

If you need more detail on logging, I would try and schedule some time with @howbazaar as I think he was the last one to meddle with it.

**Comment by petermatulis** [comment]
I've lowered priority on this. I can't find any reliable information on the current implementation of juju-log other than the use of the '-l' switch for specifying log level. I would like us to start adopting a more definitive documentation style and not a common usage "tutorial-style".

**Comment by evilnick** [comment]
The issue is that it *WAS* definitive. The usage of the command changed without sufficient documentation in the release notes, so now there are extra things that weren't explained in the original article.

**Comment by petermatulis** [comment]
Filed [LP #1496127](https://bugs.launchpad.net/juju-core/+bug/1496127)

**Comment by evilnick** [comment]
@pmatulis I guess your current work will resolve this? (And #1002)

**Comment by pmatulis** [comment]
@evilnick No. This is the juju-log command used by charms. By now, I expect this to be in the charm writer's guide.

**Comment by evilnick** [comment]
Hahah. Okay
