### ISSUE TITLE
No documentation for status-set or status-get

### ISSUE THREAD

**Issue by AdamIsrael** [juju/docs#590]
I just noticed that, while we have documentation of the various [status values], we don't have documentation about how to use the commands to set/get them.

[status values]: https://jujucharms.com/docs/1.24/reference-status

**Comment by evilnick** [comment]
Hi,

the docs for [status-set](https://jujucharms.com/docs/stable/authors-hook-environment#status-set) and [status-get](https://jujucharms.com/docs/stable/authors-hook-environment#status-get) are included with all the other hook tools, as well as being included in the [charm walkthrough](https://jujucharms.com/docs/stable/authors-charm-writing#writing-hooks)

I'm not sure where else you were expecting to find them?

**Comment by evilnick** [comment]
Hi @AdamIsrael, can you let me know if that covers your concerns so we can close this or do something else?
