### ISSUE TITLE
Expand on upgrade-charm docs

### ISSUE THREAD

**Issue by hatched** [juju/docs#598]
It would be great if the upgrade charm docs outline in details what Juju does to the existing charm when performing the upgrade. The docs https://jujucharms.com/docs/1.24/authors-charm-upgrades don't really tell you in any detail what happens. One can infer that it extracts the new charm into the charm path overwriting all files which match but it's not very clear. It's also missing that it then runs either the install or charm-upgrade hook afterwards.

**Comment by petermatulis** [comment]
Agreed.
