### ISSUE TITLE
charm tools docs do not link to the source

### ISSUE THREAD

**Issue by mitechie** [juju/docs#630]
https://jujucharms.com/docs/stable/tools-charm-tools

I cannot find the code link in the doc. Is this on LP, GH, etc?

**Comment by tvansteenburgh** [comment]
https://launchpad.net/charm-tools

**Comment by mitechie** [comment]
Can this be removed then? I just got through emailing folks concerned this hadn't been updated since January but I noticed debs from June:

https://github.com/juju/charm-tools/commits/master

**Comment by evilnick** [comment]
in the meantime, I'll add a link to the source on the page
