### ISSUE TITLE
Typo's on Private Cloud docs

### ISSUE THREAD

**Issue by chrisjohnston** [juju/docs#642]
https://jujucharms.com/docs/stable/howto-privatecloud

I believe the following are both typo's:

the <path_url> value as described above in Tools Metadata Contents

the <path_url> value as described above in Image Metadata Contents

(copy and paste failed, currently on the docs website they show up as LT and GT instead of < and >)

**Comment by chrisjohnston** [comment]
Could this be pushed to the stable docs as well please:

https://jujucharms.com/docs/stable/howto-privatecloud

**Comment by petermatulis** [comment]
Done :sleeping: . Please confirm.

**Comment by chrisjohnston** [comment]
Looks good. Thanks
