### ISSUE TITLE
%APPDATA% on getting-started is formatted poorly

### ISSUE THREAD

**Issue by chrisjohnston** [juju/docs#645]
https://jujucharms.com/docs/stable/getting-started

Under the Windows section there is a line:
%APPDATA%\Juju\environments.yaml
which has special formatting. It is immediately followed by the line:
%APPDATA% typically == C:\Users\\AppData\Roaming
which has no special formatting and seems out of place using '=='

**Comment by petermatulis** [comment]
You want to replace '==' with 'is defined as' you mean?

**Comment by chrisjohnston** [comment]
That sounds better than how it is now.

**Comment by petermatulis** [comment]
Ok, it has been changed and should be live in around 15 minutes.

**Comment by petermatulis** [comment]
There was another, more serious, error in there. That has been fixed too. :walking:

**Comment by petermatulis** [comment]
Alrighty, both stable and devel are fixed and published. Closing.
