### ISSUE TITLE
authors-charm-writing does not note to install charm-tools package 

### ISSUE THREAD

**Issue by mitechie** [juju/docs#646]
copied from: https://github.com/CanonicalLtd/jujucharms.com/issues/148

authors-charm-writing does not note that it is required to install charm-tools to use commands like 'juju charm create vanilla'

Should the doc have a step to install charm-tools? otherwise, the first command using 'juju charm create' will fail with 'unrecognized command' which doesn't make it quite clear that the charm-tools package is missing.

$ juju charm create vanilla
ERROR unrecognized command: juju charm

**Comment by mitechie** [comment]
@raema moved the issue to the docs repo here:

**Comment by evilnick** [comment]
this is the 2nd paragraph on the page:
"Although it is possible to create a charm without using anything other than a text editor, we are also going to make use of the very excellent timesaving plugin for Juju, Charm Tools. Find out how to get and install charm tools here . Then hurry back."

Right above the command it says:
"Using the charm tools plugin, we can create the directory structure we need for our charm quickly and easily:
    juju charm create vanilla
