### ISSUE TITLE
link from charms-bundles page is broken

### ISSUE THREAD

**Issue by bac** [juju/docs#663]
The following bug was opened by @kwmonroe on a different project but I'm moving it to here:
------

The link to "search the store for bundles" in the 2nd paragraph here is broken:

https://jujucharms.com/docs/stable/charms-bundles

It's trying to go here, but I'm not sure what the correct URL would be:

https://jujucharms.com/sidebar/search/?text=bundle

**Comment by bac** [comment]
The correct target for the search should be:

https://jujucharms.com/q/?type=bundle

**Comment by evilnick** [comment]
Hmm, yes, it seems to have changed at some point
