### ISSUE TITLE
Navigation menu disappears when using a link that itself does not appear in the menu

### ISSUE THREAD

**Issue by evilnick** [juju/docs#667]
load the page: https://jujucharms.com/docs/stable/config-LXC
nav menu is missing

**Comment by petermatulis** [comment]
I thought this to be expected behaviour due to the page itself not existing within the menu. I agree the menu should still appear somehow though.

**Comment by mitechie** [comment]
Looks like a JS error there:

Uncaught TypeError: Cannot read property 'addClass' of null

Is there any sort of mismatch in the name there that would case it to come up empty? 
/me digs some more

**Comment by petermatulis** [comment]
As I said, every page that does not itself appear in the menu will not have the menu shown.

**Comment by evilnick** [comment]
Yes, it looks like the collapsing JS thing is having a wobbly because it can't find the current page in the navigation. Not all pages are in the menu - it would require sub sub sub menus to catch them all and really it is full enough as it is. I guess in these cases it should just pretend it is on the getting-started page or something

**Comment by mitechie** [comment]
Yes, we'll work on some sort of fallback for those pages.

**Comment by evilnick** [comment]
:cake:

**Comment by pmatulis** [comment]
Confirmed to be fixed.
