### ISSUE TITLE
deprecate 1.18 and 1.20 

### ISSUE THREAD

**Issue by mitechie** [juju/docs#669]
Per the cross team call today we need to deprecate 1.18 and 1.20 and move them to the archived versions. However, we should have a visible note some place that says that trusty shipped 1.18 by default, however it's not upgraded to 1.22 and so is deprecated.

**Comment by mitechie** [comment]
@AlexisBruemmer please comment if you have a suggested method of communicating the 1.18 deprecation path into a place that makes sense for Juju users. Maybe something in release notes? or some other page that's 'across versions'?

**Comment by evilnick** [comment]
I will fix 1.20 now, but leave 1.18 for a while pending what we want to do about notification.

**Comment by evilnick** [comment]
The branches for 'old' versions still exist and are listed in the 'srchives' file, but no longer published
