### ISSUE TITLE
Charm Store Policy link 404

### ISSUE THREAD

**Issue by chrisjohnston** [juju/docs#673]
On https://jujucharms.com/docs/stable/reference-reviewers there is a link to the "Charm Store Policy" that 404s.

**Comment by petermatulis** [comment]
Referring to this no doubt:

https://jujucharms.com/docs/stable/authors-charm-policy

**Comment by petermatulis** [comment]
The correction for stable and devel went live only just **now** due to a bug in our publishing mechanism.
