### ISSUE TITLE
Check Vagrant Workflow page for consistency issues

### ISSUE THREAD

**Issue by chrisjohnston** [juju/docs#678]
https://jujucharms.com/docs/stable/howto-vagrant-workflow

There are capitalization issues in multiple places on this page. Ex:
When referred to by proper name,
juju should be Juju
vagrant should be Vagrant

Charm-Tools vs Charm Tools - should pick one
Juju-Gui I believe should either be Juju GUI 

There are very possibly other examples I missed.

**Comment by petermatulis** [comment]
Thanks Chris.
