### ISSUE TITLE
juju dependency misspelt - `uvtool-libvivrt`

### ISSUE THREAD

**Issue by mitechie** [juju/docs#691]
Copied from https://github.com/CanonicalLtd/jujucharms.com/issues/157 submitted by @kunal15595  

In documentaion for configuring juju for KVM at https://jujucharms.com/docs/devel/config-KVM, there's a typo.
uvtool-libvivrt --> uvtool-libvirt

**Comment by petermatulis** [comment]
The correction has been made. Closing.
