### ISSUE TITLE
charm tools docs out-of-date

### ISSUE THREAD

**Issue by bac** [juju/docs#692]
The doc tools-charm-tools is out-of-date with respect to the current version of charm-tools (1.6.1-0ubuntu) as packaged in vivid.

Specifically the Python Example section is known to be wrong.  It currently creates a tree structure like the following, rather than the one documented:

```
my-charm/
├── config.yaml
├── hooks
│   ├── actions.py
│   ├── config-changed
│   ├── install
│   ├── services.py
│   ├── setup.py
│   ├── start
│   ├── stop
│   └── upgrade-charm
├── icon.svg
├── metadata.yaml
├── README.example
├── templates
│   └── upstart.conf
├── tests
│   ├── 00-setup
│   └── 10-deploy
└── unit_tests
    └── test_actions.py
```

**Comment by evilnick** [comment]
thanks for the report, that didn't seem to be in the release notes for 1.6. I guess we should check over the whole page.

**Comment by tvansteenburgh** [comment]
The python template was moved to python-basic, i.e.:

    juju charm create -t python-basic my-charm

Even that output differs from the doc slightly though, as new things have been added to charmhelpers since the doc was written.
