### ISSUE TITLE
Charm compose documentation for local layers

### ISSUE THREAD

**Issue by galgalesh** [juju/docs#703]
The Charm compose doesn't mention how to use layers that are stored locally. I think this is one of the first things a dev will try when starting to work with Charm compose, so I think this should be included in the docs.

**Comment by marcoceppi** [comment]
@johnsca @bcsaller could you outline this workflow?

**Comment by bcsaller** [comment]
Yes, some additional docs would be helpful here. Setting COMPOSER_PATH to a directory containing the local layers will allow them to resolve. If this is set they will resolve there before looking online using the webservice. 

Likewise, for interface stubs, INTERFACE_PATH can be set.

**Comment by AdamIsrael** [comment]
I believe this has been addressed in the new developer guide's [Getting Started](https://github.com/juju/docs/blob/master/src/en/developer-getting-started.md) page, under the `Creating a new layer` section.

**Comment by galgalesh** [comment]
I think it's best if this documentation briefly mentions where the layers in "layers.yaml" come from; explain the order of where `charm build` searches for layers: First local then interfaces.juju.solutions..

**Comment by matthewhelmke** [comment]
Closed via #991 and #1322
