### ISSUE TITLE
Validate Azure instructions

### ISSUE THREAD

**Issue by pmatulis** [juju/docs#704]
We've received a report that [Azure instructions](https://jujucharms.com/docs/stable/config-azure.html) are out of date. We'll need to look this over.

**Comment by petermatulis** [comment]
@evilnick 
Can you add the information you have on this?

**Comment by evilnick** [comment]
pasted from jujucharms:


andrewdmcleod commented 2 hours ago

https://jujucharms.com/docs/stable/config-azure

Location: West US

is no longer valid - Central US (or others?) is. Trying to use West US gives:

2015-10-09 17:00:39 ERROR juju.cmd supercommand.go:430 failed to bootstrap environment: cannot get available role sizes: location "West US" not found

Also further down on this page, instructions referring to where/what to click for creating the storage domain seem a bit outdated (you no longer necessarily need to click anything as it is on "Quick Create" by default, and Disabling "Enable Geo-Replication" is no longer worded as such.

Furthermore, First 'note' box is not clear and may appear to conflict with last 'note' box.
------------

**Comment by evilnick** [comment]
This turned out to be wrong in parts - the region was unavailable to trial accounts, but is still valid. the rest of the issue needs to be looked at though

**Comment by petermatulis** [comment]
This has turned out to be quite a beast.

**Comment by pmatulis** [comment]
Backported to 1.24 via #895

**Comment by pmatulis** [comment]
Backported to 1.22 via #898

**Comment by pmatulis** [comment]
@evilnick You mentioned 1.18. No one even created a GH label for that version. Is this really needed?

**Comment by pmatulis** [comment]
Even 1.24 is EOL. Closing this!
