### ISSUE TITLE
Need to resolve where screenshots live

### ISSUE THREAD

**Issue by castrojo** [juju/docs#71]
Right now screenshots live in htmldocs/media. Since we plan to gitignore this directory I recommend we put them in src/en/media so that contributors don't have to copy them to the generated directory, which we want them to not use anyway.

**Comment by chuckbutler** [comment]
Does it make sense to share them across languages? Dont' we want to capture them in their correct localization?

**Comment by evilnick** [comment]
That may be more relevant if juju etc had different language versions. As it is, having the images in one place doesn't proclude having different language versions where desired ( if you want to have install1.jpg and fr_install1.jpg for example). It does mean there is a consistent reference point and a single place to update which is more useful.

**Comment by petermatulis** [comment]
src/media sounds good to me. what's the next step?

**Comment by evilnick** [comment]
this seems more or less resolved for now - they live in htmldocs/media until such a time as we can sync with the website code and move everything around
