### ISSUE TITLE
Clarification on disable-network-management option for MAAS

### ISSUE THREAD

**Issue by cherylj** [juju/docs#717]
https://jujucharms.com/docs/stable/config-maas

"There is one case where an additional configuration option should be
made: when MAAS is managing the bridge and bringing networks up and
down, set the "disable-network-management" option in environments.yaml
to "true":"

This setting actually prevents lxc from properly setting up a bridge for
juju to deploy successfully and should be removed or appended to reflect
the proper use for network disable.

(opened for launchpad bug: https://bugs.launchpad.net/juju-core/+bug/1511090   If additional information is needed, dimitern is probably a good resource to ask)

**Comment by evilnick** [comment]
I'm just going to go ahead and remove this for now. The explanation is one that was provided previously but clearly doesn't match reality
