### ISSUE TITLE
Charm Tools need usage of commands updated

### ISSUE THREAD

**Issue by mbruzek** [juju/docs#725]
The usage section of the Charm Tools document should include the usage of the `charm build` command.  

Charm Tools 1.8.0 has the `charm build` command and that is not included in the docs.

We should add that section.

**Comment by evilnick** [comment]
does this eco-team label get things added to the review queue yet?

**Comment by marcoceppi** [comment]
No. This likely won't be a feature until April

**Comment by marcoceppi** [comment]
We will be updating all these docs in the coming weeks though as we clean
house and move the upstream docs for tooling here

**Comment by evilnick** [comment]
I don't think this was ever addressed. Charm tools docs seem to point to also out of date offsite docs

**Comment by pmatulis** [comment]
Actually, as of 2.2, these need to be added:

```
build
push-term
release-term
show-term
```

and these need to be removed:

```
pull-source
test
```
