### ISSUE TITLE
env var for changing default status output not documented

### ISSUE THREAD

**Issue by mitechie** [juju/docs#728]
https://jujucharms.com/docs/master/reference-environment-variables doesn't have it. There's some env var to make tabular the default format for instance.

**Comment by evilnick** [comment]
@kat-co did you by any chance add an environment variable for status-type things? And if so, what is it?

**Comment by kat-co** [comment]
Someone did, but I don't remember what it is. I know JUJU_CLI_VERSION works, but I'm not sure that's specific to the tabular format.

**Comment by evilnick** [comment]
cool. I feel a general email coming on.

**Comment by evilnick** [comment]
thanks for filing this @mitechie - still no clue on mythical tabular variable, but my investigations in the source code have turned up at least 4 other variables which need docs

**Comment by pmatulis** [comment]
I asked the Juju team on this today and there is no way to set a default.

@evilnick Please open a separate issue for the undocumented variables you found.
