### ISSUE TITLE
Change the hook-tools reference to be more scannable.

### ISSUE THREAD

**Issue by kat-co** [juju/docs#730]
I suggest something like this:

| Name | 1.20 | 1.21 | 1.22 | 1.23 | 1.24 | 1.25 |
| --- | --- | --- | --- | --- | --- | --- |
| [status-set](#status-set) | red | red | red | red | green | green |

<div id="status-set"><dd><strong>status-set</strong></dd> <dt>Blah blah blah</dr></div>

**Comment by evilnick** [comment]
Perhaps I am not seeing some use case that makes this sensible to me. I agree wholeheartedly that it should be easier to navigate. I would prefer to do this either using foldouts (as used for the commands) or having a table of contents at the top (there actually may be too many entries to make this work sensibly). Both of these options, currently, require work outside of docs to implement properly (foldouts are broken wrt code examples pending the plugin being fixed, a proper toc implementation requires updates to the blues-browser code)

The thing I don't get about the table option is this -  say i am looking at the 1.20 version of the docs - status set wouldn't actually be in those docs at all.
If i am reading the current version of the docs, why do I care that the feature I want to use wasn't available in 1.20?
