### ISSUE TITLE
commands page code samples

### ISSUE THREAD

**Issue by evilnick** [juju/docs#732]
need workaround for https://github.com/marcoceppi/mdx_foldouts/issues/1

**Comment by marcoceppi** [comment]
I'm taking a look at fixing this in the plugin. I'll report back on Monday with my findings

**Comment by evilnick** [comment]
thanks! i'm sure you have plenty of better things to do, but it is annoying not being able to get code samples rendering properly in foldouts

**Comment by evilnick** [comment]
if it helps any, I noticed that it only matters to fenced samples - old style indented code works fine (but the highlighting doesn't work properly on those)
