### ISSUE TITLE
Undocumented Environment variables 

### ISSUE THREAD

**Issue by tvansteenburgh** [juju/docs#742]
Inside an executing action, this env var is set and contains the uuid of the currently executing action (e.g., d4044c7e-7fd1-4566-8aee-c574d3dedd5d). There is no mention of this var in the docs.

**Comment by marcoceppi** [comment]
@chuckbutler @mbruzek ^

**Comment by evilnick** [comment]
Thanks for this. There are currently about 8 undocumented env vars i discovered by grepping through the source, I'll make sure this is on my list

**Comment by chuckbutler** [comment]
@evilnick - do you have a list of those ENV Vars handy? I'll get that in our branch we're working on

**Comment by evilnick** [comment]
these are the ones I have collected which are not mentioned on the reference page. Some may be 'internal use only' 

 - [ ] JUJU_CONTAINER_TYPE
 - [ ] JUJU_DUMMY_DELAY
 - [ ] JUJU_NOTEST_MONGOJS
 - [ ] JUJU_LOGGING_CONFIG
 - [ ] JUJU_ACTION_NAME
 - [ ] JUJU_ACTION_TAG
 - [ ] JUJU_ACTION_UUID
 - [ ] JUJU_AVAILABILITY_ZONE
 - [ ] JUJU_MACHINE_ID
 - [ ] JUJU_CHARM_DIR
 - [ ] JUJU_DEV_FEATURE_FLAGS
 - [ ] JUJU_STARTUP_LOGGING_CONFIG 
 - [ ] JUJU_CLI_VERSION

**Comment by chuckbutler** [comment]
Nice, we had some of these and stripped them out, such as JUJU_AVAILABILITY_ZONE as it seems tightly knit with the internals and not quite useful when charming, but i'll get these represented and we can trim if required. TA I'll ping you in the commit.

**Comment by evilnick** [comment]
I think it may be worth appending a list of these with suitable 'not for use' warnings, if only to prevent us from pointlessly coming across them again and not knowing what they are.

**Comment by chuckbutler** [comment]
https://github.com/chuckbutler/docs/commit/292ae248bcd046daf38f247aad56ee385f9764fb

Prelim work done here. If this needs to be pushed @ current docs I can export and patch whats in master.k Otherwise i'm 43 commits diverged and this would be a hairy update :P
