### ISSUE TITLE
juju upgrade docs are too technical/deep for an overview of 'how to upgrade juju' 

### ISSUE THREAD

**Issue by mitechie** [juju/docs#750]
The current upgrade docs read more like "Upgrade Details" vs a general "How to upgrade" document. 

https://jujucharms.com/docs/stable/juju-upgrade

**Comment by evilnick** [comment]
I agree they need some work. I believe @petermatulis had no small amount of difficulty in getting reliable consistent information on how upgrades were *supposed* to work, so the result is more a sort of essay/description of what happens. 
There is a branch https://github.com/juju/docs/pull/737 from @mjs which addresses some of this, but goes a little too far the other way and loses some useful information.

**Comment by mitechie** [comment]
I've asked the QA team to get me notes on how we test upgrades and we'll
work to get a better clear path on how they should work.

Thanks for helping on this end Nick.

**Comment by evilnick** [comment]
No problem, we want to get it fixed too. Please also note this bug - https://bugs.launchpad.net/juju-core/+bug/1403655 which I think is a big problem for UX

**Comment by petermatulis** [comment]
@mitechie Let me know when you get the extra information that will help push this bug forward.

**Comment by pmatulis** [comment]
I'm working on this page, including converting it to Juju 2.0. I'm blocked on the latter because I don't know what to replace the deprecated 'sync-tools' command with.
