### ISSUE TITLE
Juju authorized-keys add key format not explained

### ISSUE THREAD

**Issue by galgalesh** [juju/docs#752]
[The documentation about adding public ssh keys to a Juju environment](https://jujucharms.com/docs/1.25/juju-misc) doesn't specify what the key format is.

**Comment by galgalesh** [comment]
I made a pull request for this: https://github.com/juju/docs/pull/753

**Comment by galgalesh** [comment]
Closing since brach is merged

**Comment by evilnick** [comment]
thanks!
