### ISSUE TITLE
Document cloudimg-base-url option

### ISSUE THREAD

**Issue by cherylj** [juju/docs#757]
Bug https://bugs.launchpad.net/juju-core/+bug/1357045 introduced cloudimg-base-url, but docs were never created for it.  The comment from the code around this setting is:

cloudimg-base-url allows a user to override the default url that the 'ubuntu-cloudimg-query' executable uses to find container images. This is primarily for enabling Juju to work cleanly in a closed network.

**Comment by pmatulis** [comment]
Closed via #3273.
