### ISSUE TITLE
update-status hook

### ISSUE THREAD

**Issue by cherylj** [juju/docs#758]
Opened from lp bug # 1524190:

There appears to be a new update-status hook in juju stable, and it is not mentioned at https://jujucharms.com/docs/stable/authors-charm-hooks . Maybe it is still experimental.

**Comment by evilnick** [comment]
Cool. Well, it doesn't appear in any release notes so I guess either it is expermental as you say or somebody forgot to mention it. I will call a meeting of the "documentation detectives"

**Comment by cherylj** [comment]
Horacio should be able to help you out, as I believe he did that work.

**Comment by marcoceppi** [comment]
It's not experimental, it's something that just runs.

**Comment by evilnick** [comment]
Ah yes - I vaguely remember this from excessively verbose logs - this is the thing that runs to ascertain the status of the charm, rather than a hook which needs to be implemented by the user? In which case is there any point in documenting it?

**Comment by marcoceppi** [comment]
Yes, it is important and we've documented this in our new branch already.

**Comment by msplival** [comment]
This is still undocumented in current stable-juju documentation.

**Comment by evilnick** [comment]
apologies, we just need to backport the fix

**Comment by pmatulis** [comment]
I could not find this in the devel [authors-charm-hooks](https://jujucharms.com/docs/devel/authors-charm-hooks) but I did in [developer-event-cycle](https://jujucharms.com/docs/devel/developer-event-cycle). Should the first page be removed? It is obviously outdated.

**Comment by pmatulis** [comment]
Merged from #1107
