### ISSUE TITLE
actions documentation uses MySQL as example, but MySQL has no actions

### ISSUE THREAD

**Issue by marcoceppi** [juju/docs#759]
this is confusing because if you follow along in the docs the MySQL charm doesn't have actions which means what's in the doc is not the same as reality. Another service should be used as an example

**Comment by petermatulis** [comment]
> ... Another service should be used as an example

The more details you can provide the quicker these kinds of bugs can get fixed.

**Comment by degville** [comment]
fixed with #1086.
