### ISSUE TITLE
azure configuration options out-of-date and don't match 'juju generate-config' output

### ISSUE THREAD

**Issue by bac** [juju/docs#760]
It looks like a number of configuration items have changed.  Following the instructions on this azure page leads to an environment that is rejected by 'juju bootstrap'.

**Comment by evilnick** [comment]
I think the template is also wrong in which case
@petermatulis you were looking for something useful to do

**Comment by evilnick** [comment]
Hmm. my config still seems to work, but the page has changed anyhow so it is worth updating the graphics at least

**Comment by bac** [comment]
As @marcoceppi pointed out, I should've noted this is for 1.26/2.0 not 1.25.

**Comment by petermatulis** [comment]
Blocked like #780

**Comment by petermatulis** [comment]
Closing. MP #837 merged.
