### ISSUE TITLE
Storage Placement needs clarification

### ISSUE THREAD

**Issue by AdamIsrael** [juju/docs#766]
In `charms-storage.md`, the Placement block says:

```
Not all providers support dynamic storage; for example, MAAS provides an interface to physical hardware.
```

It isn't clear how MAAS providing an interface to the physical storage relates to dynamic storage. I suspect it's that MAAS hardware is generally static, in a what-you-get-is-what-you-get way, but I think there's a better way to relay that here.

**Comment by axw** [comment]
@AdamIsrael Just confirming, that is what it means.

Storage in Juju can be "static" or "dynamic": static storage is storage that can only be requested when starting the machine it is to be attached to. Dynamic storage can be added to an existing machine.

**Comment by pmatulis** [comment]
There have been a few revisions of this stuff. Closing.
