### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by evilnick** [juju/docs#769]
There seem to be a lot of broken and partially broken links, particularly in the new charm dev docs.
By partially broken, i mean targets not matching anchors

e.g. in developer-layer-example there is a link to the reference-environment variables page
the link says https://jujucharms.com/docs/devel/reference-environment-variables#juju-repository
but the actual anchor is https://jujucharms.com/docs/devel/reference-environment-variables#juju_repository

rather than fix all these one by one, it is probably wiser if someone were to lint all the new pages (and all the existing ones for bonus points - there are probably some outdated links in the rest of the docs)

**Comment by marcoceppi** [comment]
I could have sworn we built a linting tool, but maybe not. If not, adding one is a good idea. If we were to find broken anchors, would it be best to do that as a request per page, or one merge request fixing them all?

**Comment by chuckbutler** [comment]
https://www.dropbox.com/s/1smfczg35nbcbf2/flat-links-crawled-report.csv?dl=0

I did a quick crawl using integrity which doesn't check anchors, but we get a fairly clean report on the links. there's 8 bad ones caught in this cursory scan. But in alignment with @evilnick's comments, there's certainly dragons in there :disappointed:

**Comment by evilnick** [comment]
@marcoceppi there was a lint tool, but that was for the old HTML5 version of docs. Checking links in md source isn't that tricky, but checking that anchors match up is going to be unpleasant.

**Comment by evilnick** [comment]
this is moot as link checking will be built in to the new build tool
