### ISSUE TITLE
Individual errors in /devel/ pages

### ISSUE THREAD

**Issue by malevasquez** [juju/docs#777]
The following errors can be found within the /devel/ pages and are local to each individual page	:	
		
Page https://jujucharms.com/docs/devel/getting-started

	Line 655 <h2 id="windows">Windows<a class="anchor" href="#windows"></a></h2>
	Line 665 <h2 id="windows">Windows<a class="anchor" href="#windows"></a></h2>
		The anchor windows is duplicated, one of them needs to be modified or removed

Page https://jujucharms.com/docs/devel/charms-working-with-units

	Line 634 <h2 id="the-">The <code>juju ssh</code> command<a class="anchor" href="#the-"></a></h2>
	Line 646 <h2 id="the-">The <code>juju scp</code> command<a class="anchor" href="#the-"></a></h2>
	Line 666 <h2 id="the-">The <code>juju run</code> command<a class="anchor" href="#the-"></a></h2>
		The anchor #the- is repeated, two of them needs to be modified or removed
 
Page https://jujucharms.com/docs/devel/developer-getting-started

	Line 422 <a class="stable" href="/docs/stable/developer-getting-started">stable</a>
		Page ídeveloper getting startedí does not exist, should it exist within stable?

Page https://jujucharms.com/docs/devel/reference-hook-tools

	Line 880 <a href="reference-environment-variables#juju-remote-unit"><code>JUJU_REMOTE_UNIT</code></a>
		The anchor #juju-remote-unit does not appear in the referred page. However the anchor #juju_remote_unit does

Page https://jujucharms.com/docs/devel/developer-event-cycle

	Line 422 <a class="stable" href="/docs/stable/developer-event-cycle">stable</a>
		Page ëdeveloper event cycleí does not exist, should it within stable?

	Line 763 <a href="https://interfaces.jujusolutions.com">
		Links to a page that cannot be accessed 

Page https://jujucharms.com/docs/devel/developer-testing

	Line 422 <a class="stable" href="/docs/stable/developer-testingî>stable</a>
		Page ëdeveloper testingí does not exist, should it exist within stable?

Page https://jujucharms.com/docs/devel/developer-layers-interfaces

	Line 422 <a class="stable" href="/docs/stable/developer-layers-interfacesî>stable</a>
		Page ëdeveloper layers interfacesí does not exist, should it exist within stable?

Page https://jujucharms.com/docs/devel/developer-leadership

	Line 422 <a class="stable" href="/docs/stable/developer-leadershipî>stable</a>
		Page ëdeveloper-leadershipí does not exist, should it within stable?

	Line 655 <a href="refence-hook-tools#is-leader"><code>is-leader</code></a>
		Links to ëreference hooks toolí page which does not exist, the page is reference-hook-tools
		<a href="reference-hook-tools#is-leader"><code>is-leader</code></a>

	Line 669 <a href="refrence-hook-tools#leader-set"><code>leader-set</code></a>
		Links to ëreference hook toolsí page which does not exist, the page is reference-hook-tools
		<a href="reference-hook-tools#leader-set"><code>leader-set</code></a>

Page https://jujucharms.com/docs/devel/charms-storage

	Line 422 <a class="stable" href="/docs/stable/charms-storageî>stable</a>
		Page ëcharms storageí does not exist, should it within stable?

	Line 686 
		The anchor #Known-limitations does not exist in referred page, but can be find in charms-storage.

Page https://jujucharms.com/docs/devel/juju-upgrade

	Line 674 <a href="./juju-backup-restore">Backup and restore</a>
		Links to ëjuju backup restoreí page which does not exist, the page juju-backups does exist. If this is the correct one, the line should be
		<a href="./juju-backups">Backup and restore</a>

Page https://jujucharms.com/docs/devel/howto-charm-with-docker

	Line 422 <a class="stable" href="/docs/stable/howto-charm-with-dockerî>stable</a>
		Page íhow to charm with dockerí does not exist, should it within stable?

	Line 636 concept so you should <a href="get-started">get started</a>
		Links to ëget startedí page which does not exist, however the page getting-started does exist, if this is the right one, then the line should be
		concept so you should <a href="getting-started">get started</a>

	Lines 713, 751
		Anchor #the-reactive-directory repeats itself in these Lines

	Line 667 <h4 id="layer-docker-charm">layer-docker charm<a class="anchor" href="#layer-docker-charm"></a></h4>
	Line 698 <h2 id="layer-docker-charm">layer-docker charm<a class="anchor" href="#layer-docker-charm"></a></h2>
		Anchor #layer-docker-charm repeats itself in these Lines, one of them should be removed or modified

Page https://jujucharms.com/docs/devel/actions

	Line 631 <a href="howto-gui-management">Juju web UI</a>. Parameters for an action are passed as
		Links to ëhowto-gui-managementí a page that does not exist, however the page juju-gui-management does exist

Page https://jujucharms.com/docs/devel/troubleshooting

	Line 631 <a href="./troubleshooting-juju">Troubleshooting Juju itself</a>
		Links to ëtroubleshooting-jujuí a page which does not exist, however there is a page called troubleshooting which is a good candidate

Page https://jujucharms.com/docs/devel/config-scaleway

	Line 646 <li>You have configured your <a href="https://www.scaleway.com/docs/configure_new_ssh_key">SSH Key</a></li>
		Links to a page which does not exist. The only one similar is https://www.scaleway.com/docs/configure-new-ssh-key/ , then it would be
		<li>You have configured your <a href="https://www.scaleway.com/docs/configure-new-ssh-key/">SSH Key</a></li>

Page https://jujucharms.com/docs/devel/developer-debug-dhx

	Line 422 <a class="stable" href="/docs/stable/developer-debug-dhx">stable</a>
		Page https://jujucharms.com/docs/stable/developer-debug-dhx does not exist,should it within stable?

Page https://jujucharms.com/docs/devel/charms-destroy

	Line 692 <a href="charms-relations#removing">Charm relations</a>.</p>
		The anchor #removing does not exist in the referred page, however the anchor #removing-relations does, therefore it could be
		<a href="charms-relations#removing-relations">Charm relations</a>.</p>

Page https://jujucharms.com/docs/devel/developer-actions

	Line 422 <a class="stable" href="/docs/stable/developer-actions">stable</a>
		Page https://jujucharms.com/docs/stable/developer-actions does not exist,should it within stable?
		
Page https://jujucharms.com/docs/devel/developer-howto

	Line 422 <a class="stable" href="/docs/stable/developer-howto">stable</a>
		Page https://jujucharms.com/docs/stable/developer-howto does not exist,should it within stable?
	
Page https://jujucharms.com/docs/devel/developer-debugging

	Line 422 <a class="stable" href="/docs/stable/developer-debugging">stable</a>
		Page https://jujucharms.com/docs/stable/developer-debugging does not exist,should it within stable?
		
Page https://jujucharms.com/docs/devel/charms-scaling

	Line 731/2 <p>See <a href="charms-deploying#deploying-to-machines">deploying to specific machines</a>.</p>
		The anchor #deploying-to-machines does not exist in the referred page, however the anchor #deploying-to-specific-machines-and-			containers does, it could be
		<p>See <a href="charms-deploying#deploying-to-specific-machines-and-containers">deploying to specific machines</a>.</p>

Page https://jujucharms.com/docs/devel/reference-charm-hooks

	Line 422 <a class="stable" href="/docs/stable/reference-charm-hooks">stable</a>
		Page https://jujucharms.com/docs/stable/reference-charm-hooks does not exist,should it within stable?
			
Page https://jujucharms.com/docs/devel/developer-storage		

	Line 422 <a class="stable" href="/docs/stable/developer-storage">stable</a>
		Page https://jujucharms.com/docs/stable/developer-storage does not exist,should it within stable?
			
	Line 689 <p><a href=".reference-charm-hooks#[name]-storage-detaching">[name]-storage-detaching</a></p>
		there is a mistake in the script it should be <p><a href="./reference-charm-hooks#[name]-storage-detaching">[name]-storage-detaching</a></p>

Page https://jujucharms.com/docs/devel/charms-environments

	Line 739 <a href="./charms-destroy#destroying-environments">on removing things with Juju</a></p>
		The anchor #destroying-environments does not exist in the referred page, however the anchor #destroying-the-environment does, it could 		be <a href="./charms-destroy#destroying-the-environment">on removing things with Juju</a></p>
		
Page https://jujucharms.com/docs/devel/authors-relations

	Line 712 <a href="authors-charm-subordinates">Subordinate</a> charms are only valid if they
		Page https://jujucharms.com/docs/devel/authors-charm-subordinates/ does not exist
		
Page https://jujucharms.com/docs/devel/reference-reviewers	

	Line 663 <li><a href="http://manage.jujucharms.com/tools/review-queue">http://manage.jujucharms.com/tools/review-queue</a></li>
		Page http://manage.jujucharms.com/tools/review-queue returns an Internal Server Error	

Page https://jujucharms.com/docs/devel/developer-layer-example	

	Line 422 <a class="stable" href="/docs/stable/developer-layer-example">stable</a>
		Page https://jujucharms.com/docs/stable/developer-layer-example does not exist,should it within stable?
		
	Line 640 variable: <a href="reference-environment-variables#juju-repository"><code>$JUJU_REPOSITORY</code></a></p>
		The anchor #juju-repository does not exist in the referred page, however the anchor #juju_repository does, it could be
		variable: <a href="reference-environment-variables#juju_repository"><code>$JUJU_REPOSITORY</code></a></p>

Page https://jujucharms.com/docs/devel/developer-layers	

	Line 422 <a class="stable" href="/docs/stable/developer-layers">stable</a>
		Page https://jujucharms.com/docs/stable/developer-layers does not exist,should it within stable?

	Line 689 <p>There's more on programming interface layers in the <a href="developers-interface-layers">Developing Interface
		Page https://jujucharms.com/docs/devel/developers-interface-layers does not exist however https://jujucharms.com/docs/devel/developer-		layers-interfaces does if this is the right one, then the Line should be<p>There's more on programming interface layers in the <a href="developer-	layers-interfaces">Developing Interface

Page https://jujucharms.com/docs/devel/tools-amulet

	Line 712 <h4 id="class:">Class:<a class="anchor" href="#class:"></a></h4>
	Line 879 <h4 id="class:">Class:<a class="anchor" href="#class:"></a></h4>
		Repeated anchor -  not clear which one is valid
			
	Line 715 <h4 id="methods:">Methods:<a class="anchor" href="#methods:"></a></h4>
	Line 887 <h4 id="methods:">Methods:<a class="anchor" href="#methods:"></a></h4>
		Repeated anchor -  not clear which one is valid

**Comment by evilnick** [comment]
thanks for this, now we just need someone to fix it :)

**Comment by mbruzek** [comment]
I addressed these issues in #804.  However the errors that reads:
'Page X does not exist,should it within stable?' should be reduced to a warning as some of these docs only exist in "devel" at this time.
