### ISSUE TITLE
Docs needed: Azure changes

### ISSUE THREAD

**Issue by evilnick** [juju/docs#780]
The azure provider is rewritten for 2.0, particularly important are the support for placement and resources.

**Comment by petermatulis** [comment]
I need help from Juju team to get this provider to work.

**Comment by petermatulis** [comment]
I'm re-writing [config-azure.md](https://github.com/juju/docs/blob/master/src/en/config-azure.md) but I don't believe that it's the place to put usage of the Azure provider's features such as 'placement'. My understanding of these config-* pages is that their objective is to supply the minimum information to get started with a provider.

A random examination of some other config-* pages do not show provider-specific features either. How should we deal with this in general? Perhaps sub-pages for each provider is the best way.

I'm not sure what is meant by 'resources' (description of this issue).

**Comment by petermatulis** [comment]
Closing. MP #837 merged.
