### ISSUE TITLE
Windows/Centos streams

### ISSUE THREAD

**Issue by evilnick** [juju/docs#783]

**Comment by petermatulis** [comment]
> A new simplestreams search path is supported when looking up the id of
> images to run. As well as searching published Ubuntu images found on
> http://cloud-images.ubuntu.com, Windows and Centos image metadata will be
> published to https://streams.canonical.com/juju/images. This will allow
> Windows and Centos workloads to be deployed to AWS and other supported
> clouds.

**Comment by petermatulis** [comment]
Dunno, this URL doesn't work for me:

https://streams.canonical.com/juju/images

**Comment by evilnick** [comment]
Nope, I just take the info I am given :( 
Possibly not there yet...

**Comment by cherylj** [comment]
@sinzui @wallyworld Can either of you help with this issue?

**Comment by sinzui** [comment]
Juju supports streams for windows and centos, but the streams have not yet been made.

**Comment by evilnick** [comment]
btw, I believe the Windows images will only work with Azure

**Comment by sinzui** [comment]
evilnick is correct. Only the new Azure provider will support windows images by default. Owners with their own MAAS or OpenStack can register their windows images. Centos will be supported in clouds where there are Centos images with cloud-init.
