### ISSUE TITLE
bootstrap constraints separated from environment constraints

### ISSUE THREAD

**Issue by evilnick** [juju/docs#784]
### Bootstrap constraints, series, image ID

While bootstrapping, you can now specify constraints for the bootstrap machine independently of the environment constraints:

juju bootstrap --constraints <environment-cons>
               --bootstrap-constraints <bootstrap-machine-cons>

You can also specify the series of the bootstrap machine:

juju bootstrap --bootstrap-series vivid

And finally, you can now specify the image ID of the bootstrap machine on the command line. This is only available for the bootstrap machine; after bootstrapping you have access to the new “structured metadata” feature for managing images. To specify the image ID for the bootstrap machine, you must also specify the architecture and series of the machine; it is assumed that they match the image, so take care to set them correctly:

juju bootstrap --bootstrap-constraints arch=amd64
               --bootstrap-series trusty

**Comment by axw** [comment]
@evilnick The image ID bits are now behind a feature flag, and being called experimental. I think that particular bit should just go undocumented for now.

**Comment by evilnick** [comment]
thanks for the update, if that particular bit isn't going to be stable for 2.0 we will probably just leave it in dev docs for now

**Comment by pmatulis** [comment]
@axw I assume this all works now? Any new information to share before documenting? Re 'image ID', is this like an EC2 cloud image ID? Will all providers have one?

**Comment by axw** [comment]
@pmatulis support for specifying the image ID never graduated out of the feature flag. Best to imagine it doesn't exist at all, I think.

**Comment by pmatulis** [comment]
Sent internal mail regarding all valid values for `--bootstrap-constraints`. On standby.

**Comment by pmatulis** [comment]
I learned that the eligible values are the same for `--constraints` and `--bootstrap-constraints`.
