### ISSUE TITLE
Commands have pretty much all changed

### ISSUE THREAD

**Issue by evilnick** [juju/docs#786]
The new command syntax is more natural, but changes pretty much every example in the docs.

Master bug: #901

**Comment by evilnick** [comment]
This is blocked pending confirmation of what the commands actually are

**Comment by pmatulis** [comment]
Please be more precise. What is needed to have this resolved?

**Comment by evilnick** [comment]
^^ It says up there. The commands all changed but at that time we didn't know what they were. I should have closed this, as it is superseded by #827 and #857
