### ISSUE TITLE
developer-hook-tools.md needs more robust examples

### ISSUE THREAD

**Issue by AdamIsrael** [juju/docs#792]
The `developer-hook-tools.md` page needs the examples shown to be more consistent (verbage, single vs. double quote, etc), more useful (more complete examples), and cover python, bash, and powershell in all cases.

**Comment by chuckbutler** [comment]
This is really a multi-item issue... I wonder if we split this by language and divvy out the request to a few people if we can't hammer this out in short order

**Comment by AdamIsrael** [comment]
I suggested to @marcoceppi that this might be a good task for one of the people we have from the Google code thing.

**Comment by chuckbutler** [comment]
Great minds think alike, thats what I'm thinking too

**Comment by evilnick** [comment]
where is the developer-hook-tools.md page linked to in the current navigation?

I think someone needs to really actually try testing and using all the tools, and it would be nice for example for the more complicated hook tools that we mentioned caveats/limitations.

**Comment by evilnick** [comment]
this has been done for python/bash/powershell. I think if we want others added we should raise an issue per language
