### ISSUE TITLE
Outdated language in Developer guide

### ISSUE THREAD

**Issue by evilnick** [juju/docs#802]
The charm developer guide uses 1.x terms and should be updated to reflect new terms in Juju 2.0, e.g. 'controller' and 'model'

**Comment by mbruzek** [comment]
@evilnick Can you be more specific on the terms that need to be replaced or in which files you see this problem? I did a search and find "controller" in many of the documents.

I read introducing-2.md and understand "state server" is replaced with "controller" and there are several models per controller. I don't see "state sever" in the developer documentation either.

**Comment by evilnick** [comment]
I think some instances have been updated due to other changes . The things to watch out for are:

environment - in a lot of cases this should be updated to reference a model
state-server - we prefer to use 'controller' now. I think it may be refernced a few times in the old 'authors' docs.
the big one is 'services', which are now 'applications'

i changed many of these myself, but there are loads of references to services, understandably.

**Comment by mbruzek** [comment]
I will need @johnsca 's help deciphering developer-layers-interfaces.md that document uses the word "service" 39 times!
