### ISSUE TITLE
Charm developer docs need to mention Juju min version

### ISSUE THREAD

**Issue by evilnick** [juju/docs#806]
a new feature in 2.0, min version is simply a value stored in metadata which allows the charm to specify the minimum version of Juju it needs to run

> > "min-version is just a version number in the charm metadata.
> >  Have charms be able to specify the minimum version of Juju that they will operate on. Especially 
> >  useful for charms that expect to be able to make use of new feature such as leader election and storage.
> > Attempting to deploy a charm on an earlier version which supports min-version will fail with a nice message.
> > When a new version of a charm is available, but requires a newer version of Juju, we will tell them that the new version is available, but also that they will need a new Juju version."

**Comment by matthewhelmke** [comment]
Closed via #1213
