### ISSUE TITLE
[2.0 docs] More explanation of `export JUJU_REPOSITORY` statements

### ISSUE THREAD

**Issue by galgalesh** [juju/docs#808]
First of all: The getting started page looks good. It's very focused, and provides a lot of links to other examples. The creating your charm repo instructions are a great addition Creating the local repo was my first big hurdle when I first started using Juju about a year ago. I'ts nice to see this problem tackled. 

However, I think the environment variables need a little bit more explanation. I think you overestimate the skills of a lot of newcomers. Stuff that I think should be explained here:

 - JUJU_REPOSITORY will only be available in the current console. When you open a new console, the environment variables will 'disappear'. Other existing consoles will not have the var.
 - Where to put the environment variables so that every new console will have them.

Problems like this are hard to figure out when you start using Linux as a dev environment.

**Comment by mbruzek** [comment]
For what it is worth we did have the section about [preparing your workspace](https://jujucharms.com/docs/devel/developer-layer-example#prepare-your-workspace) in the developer documentation. 

But I have added notes to the other sections that use the environment variables.
