### ISSUE TITLE
[2.0 docs] Why build from layers too much focused on existing users

### ISSUE THREAD

**Issue by galgalesh** [juju/docs#810]
> "When creating a charm, you always have the option of doing it the traditional way by creating each hook, implementing each side of the interface you need for each relation your charm requires or provides, manage the dependencies, such as charm-helpers, that your charm uses, et cetera."

This text is selling Charm layers to people who are already familiar with the "old" way of Charming. I don't think this should be the first sentence on that page. While the documentation should include statements like this, I think it might be confusing for new users.

**Comment by evilnick** [comment]
I think this is endemic to the a lot of the new pages - they assume a knowledge of how charms work/were built before

**Comment by galgalesh** [comment]
Great! Thanks!

Op woensdag 6 april 2016 heeft Nick Veitch <notifications@github.com> het
volgende geschreven:
> Closed #810 via #960.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub<
https://ci4.googleusercontent.com/proxy/W4fCYkoUHJyogNL4bcAV9i7gQygeMhTtv47ad_YwWdxcfDOZkR46G-_tNrVF1B0f1HqbczGLDm2mBgyvZv_BVAVocPEdI8qgPXGxTvaVMR-lYJwOdKbaIiNtRDifUbNVQvr4dcSv5IucJmdyTkux_m1wNHUJZA=s0-d-e1-ft#https://github.com/notifications/beacon/ABbH9RqEDov9kdBCvFm9r2_ofZ27CmmJks5p09ccgaJpZM4HJiM_.gif
>
