### ISSUE TITLE
GCE docs are a bit off

### ISSUE THREAD

**Issue by tych0** [juju/docs#811]
referring to: https://jujucharms.com/docs/1.25/config-gce

The screenshots for where to click and such are off, since google has (yet again, I'm sure :) changed the interface. You need to create a "Service Account" instead of just an Oauth 2.0 Client account as it says; only a service account gets the private key that juju understands.

Once you have the service account json, you need to go through and change all the _s in the key name to -s, e.g. `sed -i 's/project_id/project-id' foo.json` (and for everything else as well) if you want to pass juju the filepath. Alternatively, copying the values from the json into your environments.yaml still seems to work just fine.

**Comment by petermatulis** [comment]
Closing. Using #747 instead.

Migrating comment.

**Comment by tych0** [comment]
Whoops, thanks, sorry for the noise!

**Comment by arosales** [comment]
@tych0 thanks for making sure we had an issue, @petermatulis thanks for linking to current issue.
