### ISSUE TITLE
LXD Initial Config Incorrect 

### ISSUE THREAD

**Issue by jamesbeedy** [juju/docs#820]
When applying the instructions specified [here](https://github.com/juju/docs/blob/master/src/en/config-LXD.md) on a freshly deployed xenial host, this is what I see: http://paste.ubuntu.com/14598656/

**Comment by petermatulis** [comment]
Yeah, the lxd package is in the Xenial archive. The PPA should only be used for Wily.

**Comment by petermatulis** [comment]
This has been fixed. Thanks for pointing it out.
