### ISSUE TITLE
Need an old command -> new command conversion guide

### ISSUE THREAD

**Issue by evilnick** [juju/docs#827]
Master bug: #901

**Comment by evilnick** [comment]
started with #828

**Comment by pmatulis** [comment]
So finish [command-changes.md](https://github.com/juju/docs/blob/master/src/en/command-changes.md)?

**Comment by evilnick** [comment]
all the commands are not completed yet, so it is rather difficult to complete the table documenting them :)

**Comment by matthewhelmke** [comment]
Superceded by #1361
