### ISSUE TITLE
[2.0 docs] Hook errors advice needs to be updated 

### ISSUE THREAD

**Issue by cmars** [juju/docs#831]
Since we now retry hooks on error automatically [in Juju 2.0], this has implications for the advice we give charm developers on [hook errors](https://jujucharms.com/docs/devel/authors-hook-errors).

While nothing really changes in terms of the importance of avoiding hook errors due to charm defects (badly-written charms won't heal themselves!), I think it does have potential impact on how hooks should deal with unexpected externalities such as a temporary network connectivity issue during package installs, etc.

The current docs advise the charm author to "wait a moment and retry a couple of times" in the event of a transient error. I think this advice now adds needless complexity -- it would be better for the hook to fail and retry in such cases where basic assumptions on the state of the system become invalid.

Thoughts? Where do we draw the line on this?

(Thanks @jrwren for bringing this to my attention!)

**Comment by chuckbutler** [comment]
Ah so this did indeed happen? Juju now retries units in error regardless of the last hook execution?

**Comment by evilnick** [comment]
As I recall at the sprint there was some debate about what actually should happen. ISTR there was talk of trying x times before failing.  Haven't tested to see what current alpha does...

**Comment by cmars** [comment]
This behavior landed in Juju 1.26-alpha / 2.0-alpha, see [announcement](https://lists.ubuntu.com/archives/juju-dev/2015-November/004897.html).

This sparked some discussion recently on [juju-devel](https://lists.ubuntu.com/archives/juju-dev/2016-January/005001.html). tl;dr Juju might provide some way to limit the auto-retrying under some cases (see the thread for details) but in general I think this is going in 2.0.

**Comment by chuckbutler** [comment]
I recall the thread, but i was unaware it had already landed. Thanks for the reminder @cmars and hattip @jrwren
