### ISSUE TITLE
tmux documentation uses ctl-a

### ISSUE THREAD

**Issue by codersquid** [juju/docs#835]
The tmux section lists ctl-a for the keybinding rather than the default, ctl-b. Double check the keybindings.

**Comment by codersquid** [comment]
Rather, I should say that I used the debug-hooks command today, and it was using ctl-b. Docs/Code need to agree.

**Comment by evilnick** [comment]
The byobu/tmux settings certainly had a different key binding, as explained in the relevant section https://jujucharms.com/docs/stable/authors-hook-debug#key-bindings so it is certainly news to us if this has changed. I will check.

**Comment by codersquid** [comment]
Btw, I'm using juju version 1.24.7-trusty-amd64

**Comment by codersquid** [comment]
Oh very weird. I just attempted to doublecheck that it is happening, and it is not. ctl-a binding works. Sorry for the false alarm. If I catch it happening again I will try to figure out what the heck is going on.

**Comment by evilnick** [comment]
This is very curious - I just tried in the default trusty 1.25 version and it is most definitely Ctrl-A, just as the docs currently say. The version of juju doesn't matter as much as the image that is being used I suspect: could you tell us what provider and/or image type you are using

**Comment by evilnick** [comment]
heh :) No problem. Thanks for caring enough to file an issue - if you can replicate the cricumstances again in the future we may be able to work out what caused it, but more likely an image/juju bug than a docs one in this case
