### ISSUE TITLE
https://jujucharms.com/docs/stable/getting-started should match https://jujucharms.com/get-started

### ISSUE THREAD

**Issue by arosales** [juju/docs#836]
I have had a few users note that https://jujucharms.com/get-started and do not match and have conflicting information. 

With the merge of https://code.launchpad.net/~marcoceppi/juju-quickstart/recommend-juju/+merge/283745 and the update to jujucharms.com to direct folks to get-started suggest we update the docs to follow https://jujucharms.com/get-started specifically for the client install instructions

**Comment by evilnick** [comment]
That path still doesn't work for some edge cases, and if we remove the actual instructions on how to make things work currently in getting started, there will be nowhere for people to find the info to solve their problems.

We will be reviewing the getting started page anyway for 2.0, so will update to best practice at that time
