### ISSUE TITLE
Devel Docs: Charm Generate Process Not Found

### ISSUE THREAD

**Issue by arosales** [juju/docs#838]
I wasn't able to easily find the "charm generate" process. Specifically the commands I should run to build my charm, inspect my charm, review a generated charm.

Also the following links are 404:
https://jujucharms.com/docs/devel/developers-layers-interfaces/
https://jujucharms.com/docs/devel/developer-debugging-layers/

**Comment by ns950** [comment]
I fixed the broken URls and the first has already been pulled, the second pending. Not yet addressed the first point here.

**Comment by marcoceppi** [comment]
It should also be noted that `charm generate` is now `charm build`

**Comment by mbruzek** [comment]
@arosales This appears to be a duplicate of #913 which I fixed in #1212.

The first link is not developer**s** but developer.

Also the last link changed to https://jujucharms.com/docs/devel/developer-debug-layers so it looks like "ing" was removed.
