### ISSUE TITLE
Devel docs need more charm examples

### ISSUE THREAD

**Issue by evilnick** [juju/docs#840]
Juju currently claims, in various places:
"Can I use Juju with Puppet or Chef or Ansible?
Yes! Puppet, Chef, and Ansible are great tools for writing configuration files. Juju works a layer above that by focusing on the service the application delivers, regardless of the machine on which it runs. So the Juju charm for a service includes (amongst other things) all the logic for writing configuration files for that service - that logic itself can be written in whatever language or tool the author of the charm prefers."

It is not easy to see how to write a puppet, chef or ansible charm with the delevoper docs

**Comment by marcoceppi** [comment]
These examples don't exist yet.

**Comment by evilnick** [comment]
@nottrobin i believe you may be able to help with this

**Comment by nottrobin** [comment]
@evilnick you mean, could I write some examples of how to create charms to deploy puppet, chef, or ansible? Not off the top of my head. With some thought I could maybe write an outline. I'll try to find time to give it a go.

**Comment by evilnick** [comment]
@nottrobin I may have been the recipient of some erroneous information from Mr Mahnke, who seems to believe you already have ansible charms at the least - I don't expect you to write anything new specifically!

**Comment by nottrobin** [comment]
@evilnick We have a charm which uses ansible in what is in my opinion a
slightly misguided way, and not for what it's meant to be used for at all
really. It would take thought for me to create as example which is actually
useful to real people.
