### ISSUE TITLE
Troubleshooting docs need a starting point

### ISSUE THREAD

**Issue by mattyw** [juju/docs#842]
The link to juju troubleshooting says "coming soon"
https://jujucharms.com/docs/devel/troubleshooting

I'd suggest as an interim we use this post from @castrojo 's blog

http://www.jorgecastro.org/2014/05/29/real-world-juju-troubleshooting/

**Comment by evilnick** [comment]
dupe of #833

**Comment by mattyw** [comment]
@evilnick not sure I'm happy about it just being marked as dup. #833 is just observations about the page in general. I'm stating something specific we can do to fix one of the links
