### ISSUE TITLE
Version numbered of docs should not be indexed by Google

### ISSUE THREAD

**Issue by castrojo** [juju/docs#848]
In GA we're seeing people coming into google hitting versioned URLs like so: jujucharms.com/docs/1.24/pagetitle. 

Google should only be indexing the /stable/ series so when people do a search they end up at the latest stable release docs and not an older version. Probably some combination of robots.txt and sitemap.xml

**Comment by evilnick** [comment]
- This doesn't seem like a docs bug, more a jujucharms one
 - There are some instances where you *do* want to find results in a particular version. Moreso after the 2.0 release, because a lot of 1.x stuff won't be searchable at all otherwise, so simply not indexing those pages isn't an option

**Comment by evilnick** [comment]
Addendum:  I just checked the analytics. This seems to account for around 0.0015% of searches and they seem to have searched specifically for those urls. Am I missing something?

**Comment by evilnick** [comment]
Although, when I do a search for e.g. 'juju cloud provider' I do get references to specific versions, so something is screwy. I thought this was supposed to be solved by the 'canonical' metatag?

**Comment by castrojo** [comment]
We're at a sprint so we weren't able to dig into GA, so I filed this in the middle of the guy's lightning talk where I saw the result; mostly as a placeholder that we should investigate. Should I close here and refile under jujucharms.com?

**Comment by marcoceppi** [comment]
This issue was moved to CanonicalLtd/jujucharms.com#209

**Comment by marcoceppi** [comment]
This needs to be handled at a jujucharms.com level. I have migrated it.
