### ISSUE TITLE
Juju Charm Developer: Add links to bottom of page to progress to the next logical section

### ISSUE THREAD

**Issue by arosales** [juju/docs#852]
User feedback is after they get done reading say developer-getting-started page at the bottom there is no instructions on what to do next.

The flow should be I can start at developer-getting-started and progress by clicking "next" at the bottom and end up on say "submitting your charm to the charm store." Meaning anyone who steps through the pages should be able to write a layered charm from scratch, covering the common use cases, ready for submission to the recommended space of the charm store.

**Comment by evilnick** [comment]
We will add individual - "Next steps" style links to pages that would benefit
