### ISSUE TITLE
Juju: Charm Developer getting started writing layers guide is missing the creation of INTERFACE_PATH

### ISSUE THREAD

**Issue by chuckbutler** [juju/docs#853]
same as title

**Comment by jrwren** [comment]
+1

the `mkdir $JUJU_REPOSITORY/{interfaces,layers}` is easy, but I don't actually know how I'm supposed to populate those spaces with interfaces I want to use in my charm.

The docs are severely lacking in this area. Does the charm build automatically pull these things? Does some other command? Am I supposed to put them there myself?

**Comment by evilnick** [comment]
can we close this now?

**Comment by chuckbutler** [comment]
I think we're g2g on this @evilnick
