### ISSUE TITLE
Need openstack provider storage example!

### ISSUE THREAD

**Issue by jamesbeedy** [juju/docs#859]
I hear rumors that storage capability exists for the openstack provider, but the are no examples for how to use storage for the openstack provider. Can we have this knowledge portrayed in juju's storage documentation?

Thanks!

**Comment by evilnick** [comment]
There are (AFAIK) no specific special settings for OpenStack/Cinder

Do the generic pool creation tools not work for you? (https://jujucharms.com/docs/1.25/storage#preparing-storage)

**Comment by jamesbeedy** [comment]
Thats correct, they do not, possibly I am missing something (like example usage). Would you mind sharing the command that you use to provision storage using the openstack provider?

**Comment by evilnick** [comment]
Hmm, no, it isn't very helpful on that front. I will do some digging and get some examples for you. I believe you need to create a pool, but there isn't a clear indication of how to do that.

**Comment by axw** [comment]
@jamesbeedy the OpenStack provider's default storage is just called "cinder", and there should be a pool called that by default. You can either specify the pool name "cinder" in the `--storage` constraints, or you can just leave it off and it'll be used as the default.

As Nick says, there is configuration for the cinder storage provider in Juju. You should still be able to create a pool, I think, but you may as well just use the default one.

**Comment by jamesbeedy** [comment]
@axw What your depicting is slightly concerning on multiple fronts..... Would you mind sharing such a command that works for you as an example? And for a huge +1 for an example addition to the documentation for storage for openstack provider.

**Comment by jamesbeedy** [comment]
@axw per @evilnick and the docs --> "The OpenStack/Cinder provider does not currently have any configuration."

**Comment by jamesbeedy** [comment]
@evilnick @axw Cinder provides block storage devices, not pools .....

**Comment by evilnick** [comment]
Thanks @jamesbeedy. i think there are 2 issues here:

 - 1. Juju doesn't actually behave as expected with cinder/OS storage. E.g. the command:  
```juju storage pool list```
      does not actually return any pools for OpenStack at all, even though, as @axw suggests, there is a default 'pool' called cinder, so for example: ```juju deploy cs:~axwalk/postgresql --storage data=cinder,10G``` does work, allocating a 10G volume in cinder which does show up with ```juju storage volumes list``` and with ```cinder list```
 - 2. The current instructions do not show
       * This particular case for OpenStack
       * an example of ```juju storage add <unit>``` for OpenStack
       * A general case of how the ```juju storage pool create``` command would work in any circumstances (I could add this if I knew the answer)

**Comment by jamesbeedy** [comment]
@evilnick Props for the example usage! And yes, now it seems ^ 1 and 2 are dead on! 

To add to your existing list:

- 3. Cinder storage is block/volume based, allocating a "pool" of cinder storage is misleading, and doesn't match the actual use case.

On top of all this, I feel like the storage usage is very limited here, what about availability zone sensitivity? The model breaks if your instances live in an availability zone other than nova! I understand you can add config flags to the cinder charm to provision "cross_az_attach = true", but this also isn't helpful in a real world use case where we want to be az sensitive.

**Comment by jamesbeedy** [comment]
Possibly a storage feature/bug for juju-core?

**Comment by jamesbeedy** [comment]
Looks like I have previously crossed this trail--> https://bugs.launchpad.net/juju-core/+bug/1536819

**Comment by axw** [comment]
@jamesbeedy There's some missing code, but what's *meant* to happen is that Juju will create the volume in the same availability zone as the instance that the volume is going to be attached to. A volume is always created attached to an instance.

We can definitely look at supporting multiple volume types. I'm surprised we missed that.

**Comment by axw** [comment]
> A general case of how the juju storage pool create command would work in any circumstances (I could add this if I knew the answer)

In the future, when we support configuring the type, you would create a pool with a command like, e.g.

    juju storage pool create cinder-lvm cinder volume-type=lvm

**Comment by matthewhelmke** [comment]
Closed via #1323
