### ISSUE TITLE
docs needed: upgrade-juju command and general upgrade procedure

### ISSUE THREAD

**Issue by evilnick** [juju/docs#89]

**Comment by petermatulis** [comment]
@marcoceppi 
What bug is this a duplicate of?

**Comment by petermatulis** [comment]
I'm planning on a dedicating a new and substantial page to upgrading Juju in general, including best practices and so on.

**Comment by petermatulis** [comment]
@evilnick
Take note!

**Comment by petermatulis** [comment]
Fixed in PR #679 . Closing
