### ISSUE TITLE
resolved vs set-resolved/retry-hook

### ISSUE THREAD

**Issue by stub42** [juju/docs#896]
https://jujucharms.com/docs/devel/command-changes tells us there are set-resolved and retry-hook commands. However, https://jujucharms.com/docs/devel/commands still only lists the old error prone 'resolved' command.

**Comment by evilnick** [comment]
The commands page is auto generated from the current juju help text, and has been updated for the latest alpha. If the commands aren't in `juju help` then they won't appear in the commands page either.

I will leave this open but I expect it will resolve itself when we generate the page for release.
