### ISSUE TITLE
docs/devel/developer-layers-interfaces typo: get_remove

### ISSUE THREAD

**Issue by cherylj** [juju/docs#905]
Opened from: https://bugs.launchpad.net/juju-core/+bug/1546272

https://jujucharms.com/docs/devel/developer-layers-interfaces
contains a typo, says 'get_remove' where it should say 'get_remote',
for consistency, suggest fully syncing those excerpts with
https://github.com/juju-solutions/interface-http

Also the excerpt for the reactive file stanza is wrong for:
            hookenv.log('{} has a unit {}:{}'.format(
                services['service_name'],

, it should be:
            hookenv.log('{} has a unit {}:{}'.format(
                service['service_name'],

**Comment by seman** [comment]
@cherylj both of the excerpts mentioned at the bottom are exactly the same. Please clarify what it should be changed to.

**Comment by cherylj** [comment]
@seman the change is services -> service (remove the 's')

**Comment by evilnick** [comment]
@seman you fail on the eagle-eye proofreading badge this time :)

**Comment by seman** [comment]
@cherylj  Thanks,  I mostly focused on the first line but I could have just cut&paste and let `git diff` tell me the difference.

**Comment by cherylj** [comment]
@seman no worries, it took me WAY too long to spot the difference (I copy/pasted from a lp bug so it didn't come from me originally)
