### ISSUE TITLE
Creating and using bundles doesn't include juju/stable ppa

### ISSUE THREAD

**Issue by urosj** [juju/docs#907]
And thus on trusty, version of quickstart is 1.3.1 instead of 2.2.4. The old version of quickstart does not support new bundle format. 

We should add instructions to add juju/stable PPA on all pages where quickstart is being offered as a solution to deploy bundles.

**Comment by evilnick** [comment]
nowhere in the instructions do we recommend installing Juju in any way other than from the PPA.

The bundles page is also being rewritten to rely on native Juju bundle support for 2

**Comment by evilnick** [comment]
Although, perhaps there could be some clarity on that pages for the 1.25 docs

**Comment by evilnick** [comment]
Fixed in 1.25
