### ISSUE TITLE
Lack of layer.yaml, charm build examples

### ISSUE THREAD

**Issue by stub42** [juju/docs#913]
~~There seems to be no documentation on how to declare that a layer requires an interface.~~ (Found one example)

There is information on writing layers, but seems to be no mention of how to run 'charm build' to generate a charm that can actually be used.

**Comment by chuckbutler** [comment]
https://jujucharms.com/docs/devel/developer-getting-started#assemble-the-layers

Maybe this needs to be duplicated elsewhere?

**Comment by chuckbutler** [comment]
@johnsca and i riffed on this a bit, This breaks down into a few things that need to be documented:

### Baselayer

> The baselayer has a [Readme](https://github.com/juju-solutions/layer-basic/blob/master/README.md), and we should leverage that for documenting its role in the pipeline.

- Wheelhouse support
- config states @when('config.changed')
- layer options for custom packages
- venv support 

### Layer.yaml

- Layer Options
- Yaml modifications (Deletes)
- Custom Tactics
- File Ignores

# Builder

- CLI Args
- Env Vars
- ?
