### ISSUE TITLE
No package "juju2"

### ISSUE THREAD

**Issue by tomck** [juju/docs#920]
https://jujucharms.com/docs/devel/getting-started

Commands to install:
```
sudo add-apt-repository ppa:juju/stable
sudo apt-get update && sudo apt-get install juju2
```

Attempt (plus extra data to show what OS I'm on):
```
user@lubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
@lubuntu:~$ sudo add-apt-repository ppa:juju/stable
 Stable release of Juju for Ubuntu 12.04 and above.
 More info: https://launchpad.net/~juju/+archive/ubuntu/stable
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmplqs_ilrv/secring.gpg' created
gpg: keyring `/tmp/tmplqs_ilrv/pubring.gpg' created
gpg: requesting key C8068B11 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmplqs_ilrv/trustdb.gpg: trustdb created
gpg: key C8068B11: public key "Launchpad Ensemble PPA" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
pb@pb-lubuntu:~$ sudo apt-get update && sudo apt-get install juju2
[snip]
E: Unable to locate package juju2
```

Bit of an issue, right? I assume?  Trying to get juju2 because of issues installing rails charm: juju/juju-gui#1286

**Comment by bz2** [comment]
See the box at the top:

> Note: These instructions are currently transitional. They will become the standard instructions for the stable 2.0 release, but as not all features of that release are fully finalised, some parts may change. If you are currently using a pre-release version of Juju, please also refer to the release notes for caveats and install information. There are many broken links etc, this is all work in progress

We're not providing juju2 for wily in the stable ppa just yet. If you really want to try it out, you'll need to use the devel ppa per the release notes:

<https://lists.ubuntu.com/archives/juju/2016-February/006618.html>

Note that a new beta will be out with the juju2 packaging Shortly™.

**Comment by evilnick** [comment]
thanks @bz2
