### ISSUE TITLE
docs/devel/charms-deploying#deploying-to-specific-machines-and-containers incorrect example

### ISSUE THREAD

**Issue by arosales** [juju/docs#921]
The example on this page shows:

    juju deploy --to 0 mysql
    juju deploy --to 0 rabbitmq-server

However, in Juju 1.25 a user gets the following error when trying to co-locate services onto the bootstrap node:

> $ juju deploy local:helloworld --to 0
> ERROR machine 0 is the state server for a local environment and cannot host units

This bug is to update the example to _not_ deploy to the bootstrap node, machine 0.

**Comment by evilnick** [comment]
Thanks for this, it further underlines my desire to deliver testing for the docs examples.

I didn't see anything in the release notes about not co-locating with machine 0...

**Comment by marcoceppi** [comment]
The key here is "local", in 1.25 you can't do this because 0 is your
machine, in 2.0 this will be fine.

**Comment by evilnick** [comment]
Ah, okay, so we are saying that people using local provider are falling foul of this. Rather than changing the example, or perhaps in addition to it, it is probably better to add a note explicitly explaining this
