### ISSUE TITLE
Charm layer:basic needs representation in the docs

### ISSUE THREAD

**Issue by chuckbutler** [juju/docs#924]
Baselayer

The baselayer has a Readme, and we should leverage that for documenting its role in the pipeline.
Wheelhouse support
config states @when('config.changed')
layer options for custom packages
venv support

xpost from #923.

**Comment by chuckbutler** [comment]
Im not sure where else this has been documented but I know that @mbruzek and I worked on this yesterday. I think it was either duplicated or missed in the commit message.

**Comment by evilnick** [comment]
Ok
