### ISSUE TITLE
No mention of storage or payloads on metadata.yaml page

### ISSUE THREAD

**Issue by tvansteenburgh** [juju/docs#927]
Storage and payloads are both available in 1.25, but neither are mentioned here: https://jujucharms.com/docs/1.25/authors-charm-metadata

There is a page devoted to storage here: https://jujucharms.com/docs/1.25/storage. Perhaps we could link to that.

There is some info about payloads in the 1.25.0 release notes here: https://jujucharms.com/docs/1.25/reference-release-notes

**Comment by AdamIsrael** [comment]
I've opened pull request #969 to address the missing storage documentation. Payload documentation is currently blocked on [Launchpad bug #1567518](https://bugs.launchpad.net/juju-core/+bug/1567518).
