### ISSUE TITLE
missing docs for implementing Resources and Terms

### ISSUE THREAD

**Issue by kwmonroe** [juju/docs#935]
In the Developer Guide section here:

https://jujucharms.com/docs/devel/developer-getting-started

I see "Implementing [Leadership|Actions|Storage]" which is really helpful in understanding how to use these cool features.  I would like similar sections for implementing Juju Resources and Terms, as I have not been able to find good examples on supporting either of these.

**Comment by arosales** [comment]
+1 This is needed for the commercial charms we have in flight such as the IBM Charms.

**Comment by AdamIsrael** [comment]
PR #1048 documents the Terms functionality. Feedback on that doc would be appreciated.

**Comment by mbruzek** [comment]
It looks like we still need documentation on resources which is separate than storage.

**Comment by mbruzek** [comment]
PR #1122 documents the Resource feature. Please have a look.

**Comment by chuckbutler** [comment]
@evilnick this is triaged. plz close :cake:

**Comment by evilnick** [comment]
ok
