### ISSUE TITLE
getting-started devel docs 404 on credential guide

### ISSUE THREAD

**Issue by pmatulis** [juju/docs#938]
@kwmonroe
Migrating from CanonicalLtd/jujucharms.com

> https://jujucharms.com/docs/devel/getting-started
> 
> Section 3, "Enter your credentials" has a link at the very end that tells the reader to "see this guide to credentials". It points here:
> 
> https://jujucharms.com/docs/devel/credentials/
> 
> And that 404s.

**Comment by evilnick** [comment]
fixed by #961
