### ISSUE TITLE
Charm command workflow: Need docs on workflow commands such as pull, pull-source, logout

### ISSUE THREAD

**Issue by arosales** [juju/docs#943]
This bug is for documentng the workflow a user should be aware of to interact with the 'charm' command with developing charms.

Ie, how one can pull the source and or charm. It should also point out how to get the upstream URL so users can collaborate there.

This documentation should also outline the process a user should follow to get their charm published in the charm store (ie development, stable, acls). It should also include steps to propose the charm for recommendation.

**Comment by marcoceppi** [comment]
this is a duplicate of #937
