### ISSUE TITLE
jujucharms docs has inconsistency in clouds yaml Edit

### ISSUE THREAD

**Issue by mitechie** [juju/docs#944]
On https://jujucharms.com/docs/devel/clouds#specifying-additional-clouds we see mention of:

    auth-types: <[access-key, oauth, userpass]>

And then:

     auth-types: [access-key, userpass]

These differences aren't explained or clarified.

Copied from https://bugs.launchpad.net/juju-gui/+bug/1564101

**Comment by pmatulis** [comment]
Fixed.
