### ISSUE TITLE
The juju devel docs should remove all links to the local KVM provider

### ISSUE THREAD

**Issue by mbruzek** [juju/docs#946]
Against my numerous objections Juju 2.0 no longer supports the local KVM provider, and the docs in devel need to be removed as Juju users will no longer be able to bootstrap a KVM provider.

This is actually the provider I *was* using on a daily basis and it makes me extremely sad, so I probably can not work on resolving this issue without incredible bias and bitter remorse.

**Comment by mbruzek** [comment]
ubuntu@warhorse:~$ juju version
2.0-beta2-trusty-amd64
ubuntu@warhorse:~$ juju bootstrap kvm kvm
ERROR unknown cloud "kvm", please try "juju update-clouds"

**Comment by evilnick** [comment]
I used kvm a lot too, because I could 'local' deploy to the big-box-upstairs-somewhere-haven't-seen-it-in-years. 

:'(

**Comment by marcoceppi** [comment]
KVM will be back as it's own provider in 2.1

**Comment by mbruzek** [comment]
I believe they will come back but I suspect that will be a while.  Currently juju 2.0 will not be able to bootstrap KVM. So what should we do with the devel docs until that time?

**Comment by evilnick** [comment]
oh it's okay, all the 'providers' are due for a slash and burn.

What are we going to do about all the eco-team bugs though?

On 31 March 2016 at 20:06, Matt Bruzek <notifications@github.com> wrote:

> I believe they will come back but I suspect that will be a while.
> Currently juju 2.0 will not be able to bootstrap KVM. So what should we do
> with the devel docs until that time?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/juju/docs/issues/946#issuecomment-204083375>
>



-- 
Nick Veitch,
CDO Documentation
Canonical

**Comment by chuckbutler** [comment]
We're sprinting next week so there's a good chance a lot of those eco-team bugs will get addressed during that time
