### ISSUE TITLE
The devel docs should install the devel ppa

### ISSUE THREAD

**Issue by mbruzek** [juju/docs#950]
A partner had problems installing juju 2.0 because the devel docs still use the stable ppa. 

I can fix this if that is OK to point to ppa:juju/ppa

**Comment by marcoceppi** [comment]
ppa:juju/devel *

**Comment by evilnick** [comment]
I will stick a note in. it is easier to remove a note than to rewrite all the pages once again after 2.0 is released. 
We don't have resources/people to publish new docs for each alpha/beta release at the moment.

**Comment by marcoceppi** [comment]
We don't need to, it's two line change. Having it as it is and then moving back that two line change is better than a note, IMO for UX.
