### ISSUE TITLE
tools-charm-tools needs some language tweaks

### ISSUE THREAD

**Issue by evilnick** [juju/docs#967]
@castrojo has done some excellent work bringing this page up to date, but it could do with a once-over for language/spelling.

**Comment by evilnick** [comment]
@matthewhelmke I thought you might be able to load up your English(British) dictionary and have a look over this.

**Comment by matthewhelmke** [comment]
#968 has been merged. Closing.

**Comment by evilnick** [comment]
@matthewhelmke I think if you put "fixes #967" in the PR it automatically closes

**Comment by matthewhelmke** [comment]
I didn't know that! Thanks.
