### ISSUE TITLE
Juju 2.0 upgrade doc

### ISSUE THREAD

**Issue by gemagomez** [juju/docs#989]
I am trying to upgrade juju from 1.25.3 to 2.0.0 on a test environment as explained in:
https://jujucharms.com/docs/devel/introducing-2

I am not allowed unless I am in juju 1.25.4 or higher according to the command line (unlike the documentation indicates):
$ juju version
1.25.3-trusty-amd64
$ juju upgrade-juju --version=2.0.0
Upgrades to juju 2.0 must first go through juju 1.25.4 or higher.
ERROR cannot upgrade to version incompatible with CLI

**Comment by evilnick** [comment]
Upgrades are currently (i.e. with beta versions of 2.0) **not supported at all**.
We will adjust the instructions accordingly when upgrades are actually supported
