### ISSUE TITLE
Docs: HA logging

### ISSUE THREAD

**Issue by voidspace** [juju/docs#99]
A note on logging for HA. This should be part of the HA docs, when we have them.

Logging with HA
===============

When running JuJu with HA (ensure-availability) logging is done to all state servers. "juju debug-log" connects to a random state server, but you'll still see logs from all the state servers and all units. This means that if your master (term?) state server dies, you'll still have logs on the other state servers and still see new logging.Essentially this means that logging works the same with HA as it does without HA. You can use "juju debug-log", or ssh into a state server and view the log file directly, to see all the logs.

Logging to a state server starts once a new state server comes online, i.e. after running ensure-availability. So if your master state server dies you will lose the logs from before new state servers were started.This will be fixed at some point, so new state servers will have all existing logs synced to them when they come online. This is not currently the case.

**Comment by petermatulis** [comment]
@voidspace 

not clear (to me):

> Logging to a state server starts once a new state server comes online [...]. So if your master state
> server dies you will lose the logs from before new state servers were started.

1. does the logging to all state servers depend on the master?
1. for HA there are already multiple state servers so why say "before new state servers were started"?
1. i do, however, understand the point of a newly started state server not having cluster logs synced.  has this been fixed?
1. has any of this been blogged/referenced anywhere else?

**Comment by petermatulis** [comment]
Reminder to talk about this here:

- [juju-ha](https://jujucharms.com/docs/devel/juju-ha.html)
- [troubleshooting-debug-log](https://jujucharms.com/docs/devel/troubleshooting-debug-log.html)

**Comment by petermatulis** [comment]
I removed label 'bug' because this feature (syncing past logs to new state servers) was never implemented. Someone can open such a bug if they want.

**Comment by petermatulis** [comment]
How does the Juju master get associated with the Mongodb master? Is it random (among the ones which are about to be created) or is it always the initial single state server?

**Comment by evilnick** [comment]
i believe the latter, but i am sure someone on #juju could tell you

**Comment by petermatulis** [comment]
PR #604 merged. Closing.
