### ISSUE TITLE
Charm push/publish fails against restricted teams

### ISSUE THREAD

**Issue by AdamIsrael** [juju/docs#993]
The `charm push` and `charm publish` commands will fail when pushing to a team on Launchpad if the team's membership is set to restricted, due to a limitation in the launchpad api.

```
$ charm push . cs:~restricted-team/trusty/mycharm
ERROR cannot post archive: unauthorized: access denied for user "myuser"
```

The docs describing these commands should be updated to reflect this limitation.

**Comment by matthewhelmke** [comment]
This will require further research at this point. For example, 'charm publish' is now 'charm release'. I don't know what, if any, other changes have occurred that will also impact this issue.
